<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Admin\**" />
    <EmbeddedResource Remove="Admin\**" />
    <None Remove="Admin\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Contracts\IApexLoginService.cs" />
    <Compile Remove="Contracts\IAssetRegisterDocumentControlService.cs" />
    <Compile Remove="Contracts\IFormAService.cs" />
    <Compile Remove="Contracts\ILoginDetailService.cs" />
    <Compile Remove="Contracts\ITVC.cs" />
    <Compile Remove="Contracts\TEST.cs" />
    <Compile Remove="Services\ApexLoginService.cs" />
    <Compile Remove="Services\AssetRegisterDocumentControlService.cs" />
    <Compile Remove="Services\FormAService.cs" />
    <Compile Remove="Services\LoginDetailService.cs" />
    <Compile Remove="Services\TEST1.cs" />
    <Compile Remove="Services\TVCService.cs" />   
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.12.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ePortal.Domain\ePortal.DomainClasses.csproj" />
    <ProjectReference Include="..\ePortal.Infrastructure\ePortal.Infrastructure.csproj" />
    <ProjectReference Include="..\ePortal.Persistence\ePortal.Persistence.csproj" />
    <ProjectReference Include="..\ePortal.ViewModels\ePortal.ViewModels.csproj" />
  </ItemGroup>

</Project>