<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Admin\ManageSelfPending.cs" />
    <Compile Remove="CommonFunctions.cs" />
    <Compile Remove="ConnectionString.cs" />
    <Compile Remove="DataManagement.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Oracle.ManagedDataAccess" Version="23.8.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.12.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ePortal.Domain\ePortal.DomainClasses.csproj" />
    <ProjectReference Include="..\ePortal.Shared\ePortal.Shared.csproj" />
    <ProjectReference Include="..\ePortal.ViewModels\ePortal.ViewModels.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="BAPIFunction\" />
  </ItemGroup>

</Project>
