<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Admin\**" />
    <EmbeddedResource Remove="Admin\**" />
    <None Remove="Admin\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Repositories\LoginDetailRepository.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="EntityFramework" Version="6.5.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Oracle.EntityFrameworkCore" Version="9.23.80" />
    <PackageReference Include="Spire.PDF" Version="11.6.18" />
    <PackageReference Include="Spire.XLS" Version="15.6.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ePortal.Domain\ePortal.DomainClasses.csproj" />
    <ProjectReference Include="..\ePortal.Persistence\ePortal.Persistence.csproj" />
    <ProjectReference Include="..\ePortal.Shared\ePortal.Shared.csproj" />
    <ProjectReference Include="..\ePortal.ViewModels\ePortal.ViewModels.csproj" />
  </ItemGroup>

</Project>
