<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
	    <CopyRefAssembliesToPublishDirectory>true</CopyRefAssembliesToPublishDirectory>

	  <EnablePreviewFeatures>true</EnablePreviewFeatures>
	  <Features>experimental-data-section-string-literals</Features>

  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="wwwroot\Uploads\AssetDisposal\Approval\**" />
    <Content Remove="wwwroot\Uploads\AssetDisposal\Approval\**" />
    <EmbeddedResource Remove="wwwroot\Uploads\AssetDisposal\Approval\**" />
    <None Remove="wwwroot\Uploads\AssetDisposal\Approval\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Uploads\LCODD\NewFolder\**" />
    <Content Remove="Uploads\LCODD\NewFolder\**" />
    <EmbeddedResource Remove="Uploads\LCODD\NewFolder\**" />
    <None Remove="Uploads\LCODD\NewFolder\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Controllers\IOMService.cs" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="Views\AssetTransfer\NonCapitalizeEdit1.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Views\Dreamteam\fw3n1sbj.vcx~" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BouncyCastle.Cryptography" Version="2.6.0" />
    <PackageReference Include="BuildBundlerMinifier" Version="3.2.449" />
    <PackageReference Include="ClosedXML" Version="0.105.0" />
    <PackageReference Include="itext7" Version="9.2.0" />
    <PackageReference Include="itext7.bouncy-castle-adapter" Version="9.2.0" />
    <PackageReference Include="iTextSharp" Version="5.5.13.4" />
    <PackageReference Include="itextsharp.xmlworker" Version="5.5.13.4" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="8.0.16" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.ViewFeatures" Version="2.3.0" />
    <PackageReference Include="Microsoft.Office.Interop.Excel" Version="15.0.4795.1001" />
    <PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="9.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageReference Include="System.Drawing.Common" Version="9.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ePortal.Application\ePortal.Application.csproj" />
    <ProjectReference Include="..\ePortal.Infrastructure\ePortal.Infrastructure.csproj" />
    <ProjectReference Include="..\ePortal.Persistence\ePortal.Persistence.csproj" />
    <ProjectReference Include="..\ePortal.Shared\ePortal.Shared.csproj" />
    <ProjectReference Include="..\ePortal.ViewModels\ePortal.ViewModels.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Uploads\Includes\Xslt\" />
    <Folder Include="Uploads\LCODD\TEMPLATE\" />
    <Folder Include="Uploads\NewFolder\" />
    <Folder Include="wwwroot\app\css\riskassessment\" />
    <Folder Include="wwwroot\app\js\riskassessment\" />
    <Folder Include="wwwroot\ASPXView\images\" />
    <Folder Include="wwwroot\ASPXView\Styles\" />
    <Folder Include="wwwroot\Includes\Xslt\" />
    <Folder Include="wwwroot\NewFolder\" />
    <Folder Include="wwwroot\Uploads\AT\AT PDF\" />
    <Folder Include="wwwroot\Uploads\AT\MISReport\" />
    <Folder Include="wwwroot\Uploads\Communication\Template\" />
    <Folder Include="wwwroot\Uploads\LCODD\TEMPLATE\" />
    <Folder Include="wwwroot\Uploads\SerilogLogs\" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="itextsharp">
      <HintPath>bin\Debug\net8.0\itextsharp.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Content Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
