//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class A00_DEFICIENCY
    {
        [Key]
        public decimal ID { get; set; }
        public long A00DTLTBID { get; set; }
        public decimal SYKIID { get; set; }
        public string REMARKS { get; set; }
        public string ATTACHMENTNOTE { get; set; }
        public decimal ACTIONBY { get; set; }
        public System.DateTime ACTIONON { get; set; }
        public decimal ACTIONFOR { get; set; }
        public short STATUS { get; set; }
        public short ACTIVE { get; set; }
    
        //public A00DTLTB A00DTLTB { get; set; }
        //public A00SYKI A00SYKI { get; set; }
    }
}
