//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class A00_ALLOCATION
    {
        [Key]
        public long ID { get; set; }
        public long A00DTLTBID { get; set; }
        public decimal SYKIID { get; set; }
        public Nullable<decimal> APPLICATIONPIC { get; set; }
        public Nullable<decimal> INFRASTRUCTUREPIC { get; set; }
        public string OTHERMEMBERS { get; set; }
        public Nullable<decimal> ALLOCATEDBY { get; set; }
        public Nullable<System.DateTime> ALLOCATEDON { get; set; }
        public Nullable<short> STATUS { get; set; }
        public Nullable<short> ACTIVE { get; set; }
        public Nullable<decimal> MainPIC { get; set; }
    }
}
