//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class A00ALLOCATION
    {
        [Key]
        public long A00ALLOCATIONID { get; set; }
        public long A00ID { get; set; }
        public Nullable<long> APPLICATIONPICECODE { get; set; }
        public Nullable<long> INFRAPICECODE { get; set; }
        public Nullable<short> MAINPIC { get; set; }
        public Nullable<long> ADDEDBY { get; set; }
        public Nullable<System.DateTime> ADDEDDATE { get; set; }
        public Nullable<long> LASTUPDATEDBY { get; set; }
        public Nullable<System.DateTime> LASTUPDATEDATE { get; set; }
    
        //public A00DTLTB A00DTLTB { get; set; }
    }
}
