//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class A00APPROVAL
    {
        [Key]
        public long A00APPROVALID { get; set; }
        public long A00DTLTBID { get; set; }
        public Nullable<long> DEPTHDID { get; set; }
        public Nullable<System.DateTime> DEPTHDAPPDATE { get; set; }
        public string DEPTHDAPPTXT { get; set; }
        public Nullable<long> COORDDID { get; set; }
        public Nullable<System.DateTime> COORDAPPDATE { get; set; }
        public string COORDAPPTXT { get; set; }
        public Nullable<long> DIVHDHDID { get; set; }
        public Nullable<System.DateTime> DIVHDAPPDATE { get; set; }
        public string DIVHDAPPTXT { get; set; }
        public Nullable<long> EXECOHDID { get; set; }
        public Nullable<System.DateTime> EXECOAPPDATE { get; set; }
        public string EXECOAPPTXT { get; set; }
        public Nullable<long> OHID { get; set; }
        public Nullable<System.DateTime> OHAPPDATE { get; set; }
        public string OHAPPTXT { get; set; }
        public Nullable<long> PPCHOOHID { get; set; }
        public Nullable<System.DateTime> PPCHOOHDATE { get; set; }
        public string PPCHOOHTXT { get; set; }
    
        //public A00DTLTB A00DTLTB { get; set; }
    }
}
