//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class A00CONVERTTOCR
    {
        [Key]
        public decimal A00DTLTBID { get; set; }
        public decimal CHANGEDBY { get; set; }
        public System.DateTime CHANGEDON { get; set; }
        public string CONVERTTOCRREMARKS { get; set; }
    }
}
