//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class A00DTLTB
    {
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        //public A00DTLTB()
        //{
        //    this.A00_DEFICIENCY = new HashSet<A00_DEFICIENCY>();
        //    this.A00ALLOCATION = new HashSet<A00ALLOCATION>();
        //    this.A00APPROVAL = new HashSet<A00APPROVAL>();
        //    this.A00INVFORCAST = new HashSet<A00INVFORCAST>();
        //}
        [Key]
        public long A00DTLTBID { get; set; }
        public Nullable<decimal> SYKIID { get; set; }
        public string PRJCTTLE { get; set; }
        public string PRJCTTXT { get; set; }
        public string BUKPITXT { get; set; }
        public string PURPSTXT { get; set; }
        public string TRGTINDCD { get; set; }
        public string RQUMTTXT { get; set; }
        public short BUDGETFLG { get; set; }
        public Nullable<decimal> BUDGETSYKIID { get; set; }
        public Nullable<short> ADORGLEVELID { get; set; }
        public Nullable<System.DateTime> STARTDT { get; set; }
        public Nullable<System.DateTime> ENDDT { get; set; }
        public string FRCSTOTHER { get; set; }
        public string ATTACHMENT { get; set; }
        public short STATUSCD { get; set; }
        public short ACTIVE { get; set; }
        public long ADDEDBY { get; set; }
        public System.DateTime DATEADDEDID { get; set; }
        public Nullable<long> LSTMODBYID { get; set; }
        public Nullable<System.DateTime> LASTMODDATE { get; set; }
        public Nullable<int> OPERATION { get; set; }
        public Nullable<int> DIVISION { get; set; }
        public Nullable<int> DEPARTMENT { get; set; }
        public Nullable<int> SECTION { get; set; }
    
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public ICollection<A00_DEFICIENCY> A00_DEFICIENCY { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public ICollection<A00ALLOCATION> A00ALLOCATION { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public ICollection<A00APPROVAL> A00APPROVAL { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public ICollection<A00INVFORCAST> A00INVFORCAST { get; set; }
        //public A00SYKI A00SYKI { get; set; }
    }
}
