//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class A00DEFICIENCY_1
    {
        public long A00DEFICIENCYID { get; set; }
        public Nullable<long> A00ID { get; set; }
        public string DEFICIENCYTEXT { get; set; }
        public string ATTACHMENT { get; set; }
        public Nullable<long> ADDEDBY { get; set; }
        public Nullable<System.DateTime> ADDEDDATE { get; set; }
        public Nullable<long> LASTUPDATEDBY { get; set; }
        public Nullable<System.DateTime> LASTUPDATEDATE { get; set; }
        public Nullable<short> STATUS { get; set; }
    }
}
