//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class A00ITCONFIRMATION
    {
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        //public A00ITCONFIRMATION()
        //{
        //    this.A00ITCONFAPPROVALHISTORY = new HashSet<A00ITCONFAPPROVALHISTORY>();
        //}
        [Key]
        public long ID { get; set; }
        public long A00ID { get; set; }
        public decimal SYKIID { get; set; }
        public string PROJECTCODE { get; set; }
        public Nullable<System.DateTime> PROJECTDATE { get; set; }
        public string PROJECTNAME { get; set; }
        public Nullable<decimal> IMPACTEDOPERATIONS { get; set; }
        public Nullable<decimal> USERPL { get; set; }
        public string USERDEPT { get; set; }
        public Nullable<decimal> ITPL { get; set; }
        public string ITDEPT { get; set; }
        public string SAA { get; set; }
        public string LWEA { get; set; }
        public Nullable<decimal> DEVELOPMENT { get; set; }
        public Nullable<decimal> LICENSEREQUIRED { get; set; }
        public string LRIFYES { get; set; }
        public Nullable<decimal> IREQUIREMENT { get; set; }
        public string IRIFYES { get; set; }
        public string TONETIMECOST { get; set; }
        public string TRECURRINGCOST { get; set; }
        public string TTIMELINE { get; set; }
        public Nullable<decimal> APPLICATION { get; set; }
        public Nullable<decimal> NOOFSCREEN { get; set; }
        public string HSDMCR { get; set; }
        public string U0TARGETDATE { get; set; }
        public string REMARKS { get; set; }
        public Nullable<short> AppTeamSTATUS { get; set; }
        public Nullable<short> ACTIVE { get; set; }
        public Nullable<decimal> ITCONFIRMATIONTOAPPTEAM { get; set; }
        public Nullable<decimal> ITCONFIRMATIONTOINFRATEAM { get; set; }
        public Nullable<decimal> ITCONFIRMATIONFILLEDBY { get; set; }
        public Nullable<System.DateTime> ITCONFIRMATIONFILLEDON { get; set; }
        public Nullable<short> INFRATEAMSTATUS { get; set; }
        public Nullable<long> ADDEDBY { get; set; }
        public Nullable<System.DateTime> ADDEDDATE { get; set; }
        public Nullable<long> LSTMODBYID { get; set; }
        public Nullable<System.DateTime> LASTMODDATE { get; set; }
        public Nullable<decimal> A00ALLOCATIONID { get; set; }
        public Nullable<short> MAINPIC_ID { get; set; }
        public string ATTACHMENT { get; set; }
    
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<A00ITCONFAPPROVALHISTORY> A00ITCONFAPPROVALHISTORY { get; set; }
    }
}
