//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class A00INVFORCAST
    {
        [Key]
        public long A00INVFORCASTID { get; set; }
        public long A00DTLTBID { get; set; }
        public short ACTIVE { get; set; }
        public long ADDEDBY { get; set; }
        public System.DateTime DATEADDEDID { get; set; }
        public Nullable<long> LSTMODBYID { get; set; }
        public Nullable<System.DateTime> LASTMODDATE { get; set; }
        public long INVFORCASTID { get; set; }
    
        //public A00DTLTB A00DTLTB { get; set; }
        //public INVFORCAST INVFORCAST { get; set; }
    }
}
