//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class A00ITCONFAPPROVALHISTORY
    {
        [Key]
        public decimal ID { get; set; }
        public Nullable<decimal> A00ITCONFIRMATIONID { get; set; }
        public Nullable<long> A00ID { get; set; }
        public Nullable<decimal> SYKIID { get; set; }
        public Nullable<short> ACTIONTYPE { get; set; }
        public Nullable<short> STATUS { get; set; }
        public string REMARKS { get; set; }
        public Nullable<decimal> ACTIONBY { get; set; }
        public Nullable<System.DateTime> ACTIONON { get; set; }
        public Nullable<short> ACTIVE { get; set; }
        public Nullable<short> USERTYPE { get; set; }
        public Nullable<decimal> ITCONFIRMATIONSUBMITTEDTO { get; set; }
        public Nullable<short> ITCONFSUBMITTEDTOUSERTYPE { get; set; }
        public Nullable<short> ITCONFIRMATIONSUBMITTEDSTATUS { get; set; }
    
        //public virtual A00ITCONFIRMATION A00ITCONFIRMATION { get; set; }
    }
}
