//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class A00SYKI
    {
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        //public A00SYKI()
        //{
        //    A00_DEFICIENCY = new HashSet<A00_DEFICIENCY>();
        //    A00DTLTB = new HashSet<A00DTLTB>();
        //}
        [Key]
        public decimal SYKIID { get; set; }
        public string KICODE { get; set; }
        public string FINANCIALYEAR { get; set; }
        public decimal ACTIVE { get; set; }
        public System.DateTime DATEADDED { get; set; }
        public decimal ADDEDBY { get; set; }
        public Nullable<System.DateTime> DATELSTMOD { get; set; }
        public Nullable<decimal> MODIFIEDBY { get; set; }
        public string REMARKS { get; set; }
    
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public ICollection<A00_DEFICIENCY> A00_DEFICIENCY { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public ICollection<A00DTLTB> A00DTLTB { get; set; }
    }
}
