//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class AD_EMERGENCYNO_TRN
    {
        [Key]
        public long EMERGENCY_ID { get; set; }
        public string OPERATION { get; set; }
        public long SITE { get; set; }
        public short? STD_CODE { get; set; }
        public int? TELEPHONE_NO { get; set; }
        public long? MOBILE_NO { get; set; }
        public short STATUS { get; set; }
        public long CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public long? MODIFIED_BY { get; set; }
        public DateTime? MODIFIED_DATE { get; set; }
    
        //public virtual SYSITE SYSITE { get; set; }
    }
}
