//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class AD_FAMOUSPERSONALITY_MST
    {
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        //public AD_FAMOUSPERSONALITY_MST()
        //{
        //    this.AD_PERSONALITYQUOTES_TRN = new HashSet<AD_PERSONALITYQUOTES_TRN>();
        //}
        [Key]
        public long PERSONALITY_ID { get; set; }
        public string NAME { get; set; }
        public DateTime? BORN { get; set; }
        public DateTime? DIED { get; set; }
        public string NATIONALITY { get; set; }
        public string OCCUPATION { get; set; }
        public byte[] BACKGROUND_IMAGE { get; set; }
        public short STATUS { get; set; }
        public long CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public long? MODIFIED_BY { get; set; }
        public DateTime? MODIFIED_DATE { get; set; }
        public string IMAGE_CONTENTTYPE { get; set; }
        public string IMAGE_NAME { get; set; }
    
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<AD_PERSONALITYQUOTES_TRN> AD_PERSONALITYQUOTES_TRN { get; set; }
    }
}
