//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class AD_PERSONALITYQUOTES_TRN
    {
        [Key]
        public long QUOTES_ID { get; set; }
        public string QUOTES { get; set; }
        public long PERSONALITY_ID { get; set; }
        public short STATUS { get; set; }
        public long CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public long? MODIFIED_BY { get; set; }
        public DateTime? MODIFIED_DATE { get; set; }
    
        //public virtual AD_FAMOUSPERSONALITY_MST AD_FAMOUSPERSONALITY_MST { get; set; }
    }
}
