//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class AD_USERMENU_LOG
    {
        public decimal ID { get; set; }
        public decimal MENUID { get; set; }
        public long ECODE { get; set; }
        public System.DateTime CREATEDDATE { get; set; }
    }
}
