//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("ADDESIGNATION")]
    public partial class ADDESIGNATION_LC
    {
        [Key]
        public long ADDESIGNATIONID { get; set; }
        public string DESCRIP { get; set; }
        public string INITIALDESCRIP { get; set; }
        public short ACTIVE { get; set; }
        public System.DateTime DATEADDED { get; set; }
        public Nullable<System.DateTime> DATELSTMOD { get; set; }
        public long ADDEDBY { get; set; }
        public Nullable<long> MODIFIEDBY { get; set; }
        public string LEVELDESCRIP { get; set; }
        public Nullable<long> GROUPLEVEL { get; set; }
        public Nullable<long> DISPLAYORDER { get; set; }
        public string LEVELNUMBER { get; set; }
    }
}
