//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ADEMAIL_GROUPHISTORY
    {
        [Key]
        public long EMAILGROUPHISID { get; set; }
        public string? GROUP_NAME { get; set; }
        public short? GROUP_TYPE { get; set; }
        public string? GROUP_VALUE { get; set; }
        public long? ACTION_BY { get; set; }
        public DateTime ACTION_DATE { get; set; }
        public string REMARK { get; set; }
        public long? ACTIONID { get; set; }
    }
}
