//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADEMPLOGIN
    {
        public long ADEMPCODE { get; set; }
        public string PASSWORD { get; set; }
        public DateTime? LASTLOGONTIME { get; set; }
        public DateTime? LASTLOGOUTTIME { get; set; }
        public short ISLOGGED { get; set; }
        public short ACTIVE { get; set; }
        public DateTime DATEADDED { get; set; }
        public DateTime? DATELSTMODE { get; set; }
        public long ADDEDBY { get; set; }
        public long? MODIFIEDBY { get; set; }
        public long SYUSERTYPEID { get; set; }
        public short ISFIRSTLOGIN { get; set; }
        public DateTime? PWDCHANGEDATE { get; set; }
        public decimal? INVALIDATTEMPT { get; set; }
        public DateTime? LOGINEXPIRYDATE { get; set; }
        public short? POPUPSTATUS { get; set; }
    
        //public virtual ADLOGINUSER ADLOGINUSER { get; set; }
        //public virtual SYUSERTYPE SYUSERTYPE { get; set; }
    }
}
