//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ADEMAIL_GROUPMAPPING
    {
        [Key]
        public long EMAILGROUPMAPID { get; set; }
        public long GROUP_VALUE { get; set; }
        public long EMAILGROUPMSTID { get; set; }
        public short? STATUS { get; set; }
        public long? ADDED_BY { get; set; }
        public DateTime? ADDED_DATE { get; set; }
        public long? UPDATED_BY { get; set; }
        public DateTime? UPDATED_DATE { get; set; }
    }
}
