//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADEMPLOGINEXPIRYDETAILS
    {
        public decimal ADEMPLOGINEXPIRYDETAILSID { get; set; }
        public long ADEMPCODE { get; set; }
        public System.DateTime LOGINEXPIRYDATE { get; set; }
        public System.DateTime DATEADDED { get; set; }
        public Nullable<long> ADDEDBY { get; set; }
        public long GENERATEDBY { get; set; }
    
        public virtual ADLOGINUSER ADLOGINUSER { get; set; }
    }
}
