//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ADEMPDIVDEPTSECT
    {
        [Key]
        public long ADEMPCODE { get; set; }
        public long? ADDIVISIONID1 { get; set; }
        public long? ADDEPARTMENTID1 { get; set; }
        public long? ADMODULEID1 { get; set; }
        public long? ADSECTIONID1 { get; set; }
        public long? SUPERVISOREMPCODE { get; set; }
        public short ACTIVE { get; set; }
        public System.DateTime DATEADDED { get; set; }
        public DateTime? DATELSTMOD { get; set; }
        public long ADDEDBY { get; set; }
        public long? MODIFIEDBY { get; set; }
        public long? ADVPID1 { get; set; }
        public long? SUPSUPERVISOREMPCODE { get; set; }
        public string ZONE { get; set; }
        public long? SYKI { get; set; }
        public long? ADDESIGNATIONID { get; set; }
        public string FUNCTIONALDESIGNATION { get; set; }
        public long? SYSITEID { get; set; }
        public long? SYPLANTID { get; set; }
        public long? SYLOCATIONID { get; set; }
        public long? ADFUNCTIONALDESIGNATIONID { get; set; }
        public long? ADORGLEVELID { get; set; }
        public long? POSID { get; set; }
    
    }
}
