//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ADFUNCTIONALDESIGNATION
    {
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        //public ADFUNCTIONALDESIGNATION()
        //{
        //    this.ADEMPDIVDEPTSECT = new HashSet<ADEMPDIVDEPTSECT>();
        //}

        [Key]
        public long ADFUNCTIONALDESIGNATIONID { get; set; }
        public string DESCRIP { get; set; }
        public string INITIALDESCRIP { get; set; }
        public short? ACTIVE { get; set; }
        public DateTime? DATEADDED { get; set; }
        public DateTime? DATELSTMOD { get; set; }
        public long? ADDEDBY { get; set; }
        public long? MODIFIEDBY { get; set; }
        public short? EVALFLAG { get; set; }
    
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<ADEMPDIVDEPTSECT> ADEMPDIVDEPTSECT { get; set; }
    }
}
