//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADLOGINPASSHISTORY
    {
        public long ADEMPCODE { get; set; }
        public short SYUSERTYPEID { get; set; }
        public string PASSWORD1 { get; set; }
        public string PASSWORD2 { get; set; }
        public string PASSWORD3 { get; set; }
        public string PASSWORD4 { get; set; }
        public string PASSWORD5 { get; set; }
        public Nullable<System.DateTime> DATEADDED { get; set; }
        public Nullable<long> ADDEDBY { get; set; }
        public Nullable<System.DateTime> DATELSTMODE { get; set; }
        public Nullable<long> MODIFIEDBY { get; set; }
    }
}
