//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ADMENUPARAMMAPPING_TRN
    {
        [Key]
        public long MAPPINGID { get; set; }
        public decimal MENUID { get; set; }
        public string PARAM_VALUE { get; set; }
        public short STATUS { get; set; }
        public string OPERATOR { get; set; }
        public long CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public long? MODIFIED_BY { get; set; }
        public DateTime? MODIFIED_DATE { get; set; }
        public long MENUPARAMID { get; set; }
    
        public ADMENUPARAM_MST? ADMENUPARAM_MST { get; set; }
        public virtual ADMENU_MST ADMENU_MST { get; set; }
    }
}
