//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class ADMENU_MST
    {
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ADMENU_MST()
        {
            //ADMENUROLE_MAPPING_MST = new HashSet<ADMENUROLE_MAPPING_MST>();
            ADMENUPARAMMAPPING_TRN = new HashSet<ADMENUPARAMMAPPING_TRN>();
        }
        [Key]
        public decimal MENU_ID { get; set; }
        public decimal MENU_LEVEL { get; set; }
        public decimal? MENU_PARENT_ID { get; set; }
        public decimal MENU_DISPLAY_ORDER { get; set; }
        public string MENU_TEXT { get; set; }
        public string MENU_TOOLTIP { get; set; }
        public string MENU_URL { get; set; }
        public string MENU_CONTROLLER { get; set; }
        public string MENU_ACTION { get; set; }
        public decimal MENU_TYPE { get; set; }
        public decimal STATUS { get; set; } 
        public long CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
       
        public long? MODIFIED_BY { get; set; }
        public DateTime? MODIFIED_DATE { get; set; }
        public short? MENU_DISPLAY { get; set; }
        public short MENU_TARGET { get; set; }
        public short ISDEFAULTMENU { get; set; }
        public byte[] MENUICON { get; set; }
        public string MENUICON_CONTENT_TYPE { get; set; }
        public string MENUICON_FILENAME { get; set; }
        public short? INTERNET { get; set; }
        public short? ISUPGRADED { get; set; }
        public string NEW_MENU_URL { get; set; }

        //public virtual ADLOGINUSER ADLOGINUSER { get; set; }
        //public virtual ADLOGINUSER ADLOGINUSER1 { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<ADMENUROLE_MAPPING_MST> ADMENUROLE_MAPPING_MST { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public ICollection<ADMENUPARAMMAPPING_TRN>? ADMENUPARAMMAPPING_TRN { get; set; }
    }
}
