//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("ADORGLEVEL")]
    public partial class ADORGLEVEL_LC
    {
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        //public ADORGLEVEL_LC()
        //{
        //    this.ADORGLEVELHEADs = new HashSet<ADORGLEVELHEAD_LC>();
        //}
        [Key]
        public long ADORGLEVELID { get; set; }
        public string LEVELDESCRIP { get; set; }
        public Nullable<long> PARENTLEVELID { get; set; }
        public long ADORGLEVELTYPEID { get; set; }
        public Nullable<short> SYKIID { get; set; }
        public Nullable<short> ACTIVE { get; set; }
        public Nullable<System.DateTime> DATEADDED { get; set; }
        public Nullable<long> ADDEDBY { get; set; }
        public Nullable<System.DateTime> LSTMODDATE { get; set; }
        public Nullable<long> LSTMODBY { get; set; }
        public Nullable<decimal> ADORGLEVELSAPID_old { get; set; }
        public string COSTCENTRE { get; set; }
        public Nullable<decimal> ADORGLEVELSAPID { get; set; }
        public Nullable<long> PARENTLEVELID1 { get; set; }
    
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<ADORGLEVELHEAD_LC> ADORGLEVELHEADs { get; set; }
    }
}
