//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ADORGLEVEL
    {
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        //public ADORGLEVEL()
        //{
        //    this.ADORGLEVELHEAD = new HashSet<ADORGLEVELHEAD>();
        //    this.SIS_AST_APPAUTH_MST = new HashSet<SIS_AST_APPAUTH_MST>();
        //    this.SIS_AST_OPMAPPING_MST = new HashSet<SIS_AST_OPMAPPING_MST>();
        //    this.DGIT_SMOPERATION_MAP = new HashSet<DGIT_SMOPERATION_MAP>();
        //    this.DGIT_PRADDAPP_MST = new HashSet<DGIT_PRADDAPP_MST>();
        //}

        [Key]
        public long ADORGLEVELID { get; set; }
        public string LEVELDESCRIP { get; set; }
        public long? PARENTLEVELID { get; set; }
        public long ADORGLEVELTYPEID { get; set; }
        public byte? SYKIID { get; set; }
        public short? ACTIVE { get; set; }
        public DateTime? DATEADDED { get; set; }
        public long? ADDEDBY { get; set; }
        public DateTime? LSTMODDATE { get; set; }
        public long? LSTMODBY { get; set; }
        public decimal? ADORGLEVELSAPID_old { get; set; }
        public string COSTCENTRE { get; set; }
        public decimal? ADORGLEVELSAPID { get; set; }
    
        //public virtual ADORGLEVELTYPE ADORGLEVELTYPE { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<ADORGLEVELHEAD> ADORGLEVELHEAD { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<SIS_AST_APPAUTH_MST> SIS_AST_APPAUTH_MST { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<SIS_AST_OPMAPPING_MST> SIS_AST_OPMAPPING_MST { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<DGIT_SMOPERATION_MAP> DGIT_SMOPERATION_MAP { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<DGIT_PRADDAPP_MST> DGIT_PRADDAPP_MST { get; set; }
    }
}
