//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADORGLEVELTYPE_DGIT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ADORGLEVELTYPE_DGIT()
        {
            this.ADORGLEVEL = new HashSet<ADORGLEVEL_DGIT>();
        }
    
        public long ADORGLEVELTYPEID { get; set; }
        public string LEVELTYPE { get; set; }
        public Nullable<short> ACTIVE { get; set; }
        public Nullable<System.DateTime> DATEADDED { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ADORGLEVEL_DGIT> ADORGLEVEL { get; set; }
    }
}
