//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ADORGLEVELTYPE
    {
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ADORGLEVELTYPE()
        {
            this.ADORGLEVEL = new HashSet<ADORGLEVEL>();
        }
        [Key]
        public long ADORGLEVELTYPEID { get; set; }
        public string LEVELTYPE { get; set; }
        public short?  ACTIVE { get; set; }
        public DateTime? DATEADDED { get; set; }
    
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ADORGLEVEL> ADORGLEVEL { get; set; }
    }
}
