//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("ADORGLEVELHEAD")]
    public partial class ADORGLEVELHEAD_LC
    {
        [Key]
        public long ADORGLEVELHEADID { get; set; }
        public long ADORGLEVELID { get; set; }
        public long ADEMPCODE { get; set; }
        public short ISACTIVE { get; set; }
        public System.DateTime DATEADDED { get; set; }
        public long ADDEDBY { get; set; }
        public Nullable<System.DateTime> DATELSTMOD { get; set; }
        public Nullable<long> LSTMODBY { get; set; }
    
        //public virtual ADORGLEVEL_LC ADORGLEVEL { get; set; }
    }
}
