//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ADORGCOORDINATOR_DGIT
    {
        [Key]
        public long ADORGCOORDINATORID { get; set; }
        public long ADORGLEVELID { get; set; }
        public long? OPHEAD { get; set; }
        public long? COORDINATOR { get; set; }
        public long? EXECOORDINATOR { get; set; }
        public long? DIRECTOR { get; set; }
        public short ISACTIVE { get; set; }
        public System.DateTime DATEADDED { get; set; }
        public long ADDEDBY { get; set; }
        public DateTime? DATELSTMOD { get; set; }
        public long? LSTMODBY { get; set; }
        public long? ADORGLEVELID1 { get; set; }
        public short? ISSKIP { get; set; }
        public long? DIRECTOR2 { get; set; }
    }
}
