//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ADPROCESS_MST
    {

        

        [Key]
        public decimal PROCESS_ID { get; set; }
        public string PROCESS_NAME { get; set; }
        public decimal CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public short STATUS { get; set; }
    
      
        //public virtual ICollection<ADROLE_MST> ADROLE_MST { get; set; }
    }
}
