//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ADROLEUSER_MAPPING_TRN
    {
        [Key]
        public decimal MAPPING_ID { get; set; }
        public decimal ROLE_ID { get; set; }
        public long USER_ID { get; set; }
        public decimal STATUS { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public long CREATED_BY { get; set; }
        public DateTime? MODIFIED_DATE { get; set; }
        public long? MODIFIED_BY { get; set; }

        //public virtual ADLOGINUSER ADLOGINUSER { get; set; }
        //public virtual ADLOGINUSER ADLOGINUSER1 { get; set; }
        //public virtual ADLOGINUSER ADLOGINUSER2 { get; set; }
        //public virtual ADROLE_MST ADROLE_MST { get; set; }
    }
}
