//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class ADROLE_MST
    {
        //public ADROLE_MST()
        //{
        //    this.ADMENUROLE_MAPPING_MST = new HashSet<ADMENUROLE_MAPPING_MST>();
        //    this.ADROLEUSER_MAPPING_TRN = new HashSet<ADROLEUSER_MAPPING_TRN>();
        //}

        [Key]
        public decimal ROLE_ID { get; set; }
        public string ROLE_NAME { get; set; }
        [ForeignKey("ADPROCESS_MST")]
        public decimal PROCESS_ID { get; set; }
        [ForeignKey("ADEMPLOYEE")]
        public long ROLE_BPO { get; set; }
        public decimal STATUS { get; set; }
        public DateTime CREATED_DATE { get; set; }
        [ForeignKey("ADLOGINUSER")]
        public long CREATED_BY { get; set; }
        public DateTime? MODIFIED_DATE { get; set; }
        [ForeignKey("ADLOGINUSER1")]
        public long? MODIFIED_BY { get; set; }
    
        //public virtual ADEMPLOYEE ADEMPLOYEE { get; set; }
        //public virtual ADLOGINUSER ADLOGINUSER { get; set; }
        //public virtual ADLOGINUSER ADLOGINUSER1 { get; set; }
        
        //public virtual ICollection<ADMENUROLE_MAPPING_MST> ADMENUROLE_MAPPING_MST { get; set; }
        //public virtual ADPROCESS_MST ADPROCESS_MST { get; set; }
     
        //public virtual ICollection<ADROLEUSER_MAPPING_TRN> ADROLEUSER_MAPPING_TRN { get; set; }
    }
}
