//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ADUAR_TRANS
    {
        [Key]
        public int UARID { get; set; }
        public Nullable<long> ECODE { get; set; }
        public string EMPLOYEE { get; set; }
        public Nullable<long> OPERATIONID { get; set; }
        public Nullable<long> DIVISIONID { get; set; }
        public Nullable<long> DEPARTMENTID { get; set; }
        public Nullable<long> REVIEWER1 { get; set; }
        public Nullable<long> REVIEWER2 { get; set; }
        public Nullable<long> USERTYPE { get; set; }
        public Nullable<System.DateTime> ADDEDON { get; set; }
        public Nullable<long> ADDEDBY { get; set; }
        public Nullable<long> SELECTED_REVIEWER { get; set; }
        public Nullable<long> STATUS { get; set; }
        public string REMARKS { get; set; }
        public Nullable<System.DateTime> REVIEWED_ON { get; set; }
        public Nullable<System.DateTime> SELF_REVIEWED_ON { get; set; }
        public Nullable<long> SYKIID { get; set; }
        public string SELF_REMARKS { get; set; }
        public string REVIEWER_REMARKS { get; set; }     

    }
}
