//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class APEX_LOGIN_VALIDATE
    {
        public long ID { get; set; }
        public Nullable<long> USERNAME { get; set; }
        public string TOKEN { get; set; }
        public Nullable<System.DateTime> CREATED_AT { get; set; }
        public Nullable<System.DateTime> USED_AT { get; set; }
        public Nullable<long> STATUS { get; set; }
    }
}
