//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASR_FORMA_DETAIL
    {
        public long FORMADTLID { get; set; }
        public long FORMAHEADERID { get; set; }
        public Nullable<System.DateTime> DATE_OF_NOTICE { get; set; }
        public Nullable<System.DateTime> DATE_OF_DISCHARGE { get; set; }
        public Nullable<System.DateTime> DATE_OF_PREGNANCY { get; set; }
        public Nullable<System.DateTime> DATE_OF_CHILD_BIRTH { get; set; }
        public Nullable<System.DateTime> DATE_OF_DMD { get; set; }
        public Nullable<System.DateTime> DATE_OF_ILLNESS { get; set; }
        public string AMT_MATERNITY_BENEFIT { get; set; }
        public string AMT_SUBSEQUENT { get; set; }
        public string AMT_BONUS { get; set; }
        public string AMT_WAGES { get; set; }
        public string GRANTED_LEAVE_PERIOD { get; set; }
        public string NOMINEE_NAME { get; set; }
        public string DEATH_DATE { get; set; }
        public string MATERNITY_BENEFIT_PAYMENT { get; set; }
        public string INSPECTOR_REMARK { get; set; }
        public short STATUS { get; set; }
        public long ADDEDBY { get; set; }
        public System.DateTime DATEADDED { get; set; }
        public Nullable<System.DateTime> DATELSTMOD { get; set; }
        public Nullable<long> MODIFIEDBY { get; set; }
    
        public virtual ASR_FORMA_HEADER ASR_FORMA_HEADER { get; set; }
    }
}
