//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ASR_BENEVOLENT_DT
    {
        [Key]
        public long ASR_BENEVOLENT_DTID { get; set; }
        public long ASR_BENEVOLENTID { get; set; }
        public decimal AMOUNT { get; set; }
        public long CONSENTBYEMPLOYEE { get; set; }
        public short STATUS { get; set; }
        public System.DateTime DATEADDED { get; set; }
        public long ADDEDBY { get; set; }
        public Nullable<System.DateTime> DATELSTMOD { get; set; }
        public Nullable<long> MODIFIEDBY { get; set; }
    }
}
