//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASR_FORMA_HEADER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ASR_FORMA_HEADER()
        {
            this.ASR_FORMA_DETAIL = new HashSet<ASR_FORMA_DETAIL>();
        }
    
        public long FORMAHEADERID { get; set; }
        public long ADEMPCODE { get; set; }
        public System.DateTime FROMDATE { get; set; }
        public System.DateTime TODATE { get; set; }
        public long SIGN_AUTHORITY { get; set; }
        public short STATUS { get; set; }
        public long ADDEDBY { get; set; }
        public System.DateTime DATEADDED { get; set; }
        public Nullable<System.DateTime> DATELSTMOD { get; set; }
        public Nullable<long> MODIFIEDBY { get; set; }
        public Nullable<short> PRINT_FORMA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASR_FORMA_DETAIL> ASR_FORMA_DETAIL { get; set; }
    }
}
