//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ASRCALOPMAPPING_DGIT
    {
        [Key]
        public long ASRCALOPMAPPINGID { get; set; }
        public long CALOPERATIONID { get; set; }
        public long CALSITEID { get; set; }
        public Nullable<short> ACTIVE { get; set; }
        public Nullable<System.DateTime> DATEADDED { get; set; }
        public Nullable<long> ADDEDBY { get; set; }
        public Nullable<System.DateTime> DATELSTMOD { get; set; }
        public Nullable<long> MODIFIEDBY { get; set; }
        public Nullable<long> EMPSITE { get; set; }
    }
}
