//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class ASRWFH_APPROVALHIS
    {
        [Key]
        public long ASRWFHAPPROVALHIS { get; set; }
        public Nullable<long> ASRWFHID { get; set; }
        public Nullable<long> RECADEMPCODE { get; set; }
        public Nullable<short> ISRECAPPROVED { get; set; }
        public Nullable<System.DateTime> RECAPPROVEDDATE { get; set; }
        public string RECREMARKS { get; set; }
        public Nullable<long> APPADEMPCODE { get; set; }
        public Nullable<short> ISAPPAPPROVED { get; set; }
        public Nullable<System.DateTime> APPAPPROVEDDATE { get; set; }
        public string APPREMARKS { get; set; }
        public Nullable<short> SAPUPDATESTATUS { get; set; }
        public string SAPUPDATEREMARKS { get; set; }
        public Nullable<long> MODIFIEDBY { get; set; }
        public Nullable<System.DateTime> DATEISTMOD { get; set; }

        [ForeignKey("ASRWFHID")]
        public virtual ASRWFH_HEADER ASRWFH_HEADER { get; set; }
    }
}
