//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class ASRWFH_HEADER
    {
        // [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        //

        [Key]
        public long ASRWFHID { get; set; }
        public long ADEMPCODE { get; set; }
        public Nullable<short> REQUESTTYPE { get; set; }
        public Nullable<short> APPLYFOR { get; set; }
        public Nullable<short> DURATION { get; set; }
        public Nullable<long> WEHSHIFTID { get; set; }
        public Nullable<System.DateTime> STARTDATE { get; set; }
        public Nullable<System.DateTime> ENDDATE { get; set; }
        public string STARTTIME { get; set; }
        public string ENDTIME { get; set; }
        public string REMARKS { get; set; }
        public long ADDEDBY { get; set; }
        public System.DateTime DATEADDED { get; set; }
        public Nullable<System.DateTime> DATELSTMOD { get; set; }
        public Nullable<long> MODIFIEDBY { get; set; }
        public string EMPCANCELREMARK { get; set; }
        public short STATUS { get; set; }
        public Nullable<short> AUTO_WFH_STATUS { get; set; }
        public Nullable<short> WFH_REQUESTTYPE { get; set; }

         public string WFH_REQUESTTYPEREMARKS { get; set; }

        // [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

        public virtual ICollection<ASRWFH_APPROVALHIS> ASRWFH_APPROVALHIS { get; set; }
    }
}
