//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ASSETAPP_LOG
    {
        [Key]
        public long ASTAPPROVALLOGID { get; set; }
        public long ADORGLEVELID { get; set; }
        public string EMPCODE { get; set; }
        public string SYSITEID { get; set; }
        public string APPROVALTYPE { get; set; }
        public string ACTIVE { get; set; }
        public System.DateTime UPDATEDON { get; set; }
        public string UPDATEDBY { get; set; }
        public string TRANSACTIONTYPE { get; set; }
        public long APPROVALMASTERKEY { get; set; }
    }
}
