//------------------------------------------------------------------------------
// <auto-generated?
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated?
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class ASSET_REGISTER_ORG_MAPPING
    {
        [Key]
        public decimal ID { get; set; }
        public decimal? CURRENT_SYKIID { get; set; }
        public int? CURRENT_OPERATIONID { get; set; }
        public int? CURRENT_DIVISIONID { get; set; }
        public decimal? PREVIOUS_SYKIID { get; set; }
        public int? PREVIOUS_OPERATIONID { get; set; }
        public int? PREVIOUS_DIVISIONID { get; set; }
        public int? CREATED_BY { get; set; }
        public System.DateTime? CREATED_DATE { get; set; }
        public int? UPDATED_BY { get; set; }
        public System.DateTime? UPDATED_DATE { get; set; }
        public short? STATUS { get; set; }
        [ForeignKey("CURRENT_SYKIID")]
        public virtual SYKI SYKI { get; set; }
        [ForeignKey("PREVIOUS_SYKIID")]
        public virtual SYKI SYKI1 { get; set; }
    }
}
