//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ASSET_USER_MAPPING
    {
        [Key]
        public decimal ASSETUSERMAPPINGID { get; set; }
        public decimal?SYKIID { get; set; }
        public decimal?DIVISIONID { get; set; }
        public decimal?OLDDIVISIONEMPCODE { get; set; }
        public decimal?NEWDIVISIONEMPCODE { get; set; }
        public decimal?OPERATIONID { get; set; }
        public decimal?OLDOPERATIONHEADCODE { get; set; }
        public decimal?NEWOPRATIONHEADEMPCODE { get; set; }
        public decimal?CREATEDBY { get; set; }
        public System.DateTime?CREATEDDATE { get; set; }
        public decimal?MODIFIEDBY { get; set; }
        public System.DateTime?MODIFIEDDATE { get; set; }
        public decimal?OLDISSC_MEMBERCODE { get; set; }
        public decimal?NEWISSC_MEMBERCODE { get; set; }
    }
}
