//------------------------------------------------------------------------------
// <auto-generated?
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated?
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ASSETREGISTERDOCUMENTCONTROL
    {
        [Key]
        public long SRNO { get; set; }
        public long? SYKIID { get; set; }
        public string DOCUMENT_TITLE { get; set; }
        public System.DateTime? DATE_OF_RELEASE { get; set; }
        public string DOC_VERSION_NO { get; set; }
        public string DOCUMENT_NUMBER { get; set; }
        public long? CREATED_BY { get; set; }
        public System.DateTime? CREATED_DATE { get; set; }
        public long? MODIFIED_BY { get; set; }
        public System.DateTime? MODIFIED_DATE { get; set; }
        public string AMENDMENT { get; set; }
    }
}
