//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ASSET_REGISTER_ASSETDETAILS
    {
        [Key]
         public decimal ID { get; set; }
        public decimal SKIID { get; set; }
        public string PRIMARY { get; set; }
        public string SECONDARY { get; set; }
        public decimal? ASSETID { get; set; }
        public string LOCATION { get; set; }
        public string OWNER { get; set; }
        public string CUSTODIAN { get; set; }
        public string ASSETUSER { get; set; }
        public decimal? CLASSIFICATIONID { get; set; }
        public string RETENTION { get; set; }
        public decimal? CREATEDBY { get; set; }
        public System.DateTime? CREATIONDATE { get; set; }
        public decimal? UPDATEDBY { get; set; }
        public System.DateTime? UPDATIONDATE { get; set; }
        public decimal? ACTIONTYPE { get; set; }
        public decimal? ACTIVE { get; set; }
        public decimal? SAVE { get; set; }
        public decimal? ISSCMEMBER_STATUS { get; set; }
        public decimal? DIVISIONHEAD_ID { get; set; }
        public decimal? DIVISION_STATUS { get; set; }
        public decimal? OPERATINGHEAD_ID { get; set; }
        public decimal? OPERATIONG_STATUS { get; set; }
        public System.DateTime? FINALSUBMITDATE_ISSCMEMBER { get; set; }
        public System.DateTime? FINALSUBMITDATE_DIVISIONHEAD { get; set; }
        public System.DateTime? FINALSUBMITDATE_OPERATINGHEAD { get; set; }
        public string REVIEW_REMARKS_DIVISIONHEAD { get; set; }
        public string REVIEW_REMARKS_OPERATINGHEAD { get; set; }
        public string ISSC_MEMBER_REASON { get; set; }
        public string RETENTION_REMARK { get; set; }
        public decimal? AMENDMENT_NO { get; set; }
        public decimal? ITGRC_ID { get; set; }
        public decimal? ITGRC_STATUS { get; set; }
        public System.DateTime? FINALSUBMITDATE_ITGRCHEAD { get; set; }
        public string REVIEW_REMARKS_ITGRCHEAD { get; set; }
    }
}
