//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class ASSET_REGISTER_MEMNOMINATION
    {
        [Key]
        public decimal ID { get; set; }
        public decimal? PERIODSETTINGID { get; set; }
        public decimal SYKIID { get; set; }
        public decimal DIVISIONID { get; set; }
        public decimal OPERATIONID { get; set; }
        public decimal ISSCEMPCODE { get; set; }
        public short STATUS { get; set; }
        public short? ACTIVE { get; set; }
        public decimal? ADDEDBY { get; set; }
        public System.DateTime ADDEDDATE { get; set; }
        public decimal? UPDATEDBY { get; set; }
        public System.DateTime? UPDATEDDATE { get; set; }

        [ForeignKey("SYKIID")]
        public virtual SYKI SYKI { get; set; }
       //[ForeignKey("PERIODSETTINGID")]
        //public virtual ASSET_REGISTER_PERIODSETTING ASSET_REGISTER_PERIODSETTING { get; set; }
    }
}
