//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ASSET_REGISTER_COMMON_ASSET
    {
        [Key]
        public decimal ID { get; set; }
        public string PRIMARY { get; set; }
        public string SECONDARY { get; set; }
        public decimal?ASSETID { get; set; }
        public decimal?CLASSIFICATIONID { get; set; }
        public decimal?ACTIVE { get; set; }
        public decimal?CREATEDBY { get; set; }
        public System.DateTime?CREATIONDATE { get; set; }
        public decimal?UPDATEDBY { get; set; }
        public System.DateTime?UPDATIONDATE { get; set; }
    }
}
