//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class ASSET_REGISTER_PERIODSETTING
    {
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ASSET_REGISTER_PERIODSETTING()
        {
            //this.ASSET_REGISTER_MEMNOMINATION = new HashSet<ASSET_REGISTER_MEMNOMINATION>();
        }

        [Key]
        public decimal ID { get; set; }
        public decimal SYKIID { get; set; }
        public System.DateTime STARTDATE { get; set; }
        public System.DateTime ENDDATE { get; set; }
        public short ACTIVE { get; set; }
        public long ADDEDBY { get; set; }
        public System.DateTime ADDEDDATE { get; set; }
        public long? UPDATEDBY { get; set; }
        public System.DateTime? UPDATEDDATE { get; set; }
    
       // [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<ASSET_REGISTER_MEMNOMINATION> ASSET_REGISTER_MEMNOMINATION { get; set; }
        [ForeignKey("SYKIID")]
        public virtual SYKI SYKI { get; set; }
    }
}
