//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ASSET_REGISTER_COMMONEXIST
    {
        [Key]
        public decimal ID { get; set; }
        public decimal? SYKIID { get; set; }
        public decimal? USERID { get; set; }
        public decimal? ACTIVE { get; set; }
        public System.DateTime? CREATIONDATE { get; set; }
        public decimal? ACTIONTYPE { get; set; }
    }
}
