//------------------------------------------------------------------------------
// <auto-generated?
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated?
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ASSET_REGISTE_D_ASSET
    {
        [Key]
        public decimal ID { get; set; }
        public decimal? OPERATIOID { get; set; }
        public decimal? DIVISIONID { get; set; }
        public decimal? PRIMARYASSETID { get; set; }
        public string SECONDARYASSET { get; set; }
        public string FEEDBACK { get; set; }
        public decimal? ISSCEMPCODE { get; set; }
        public System.DateTime? CREATIONDATE { get; set; }
        public decimal? CREATEDBY { get; set; }
    }
}
