//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class AT_APPROVAL_OPERATION_MAPPING
    {
        [Key]
        public int SRNO { get; set; }
        public string APPROVAL_TYPE { get; set; }
        public string OPERATION { get; set; }
        public long OPERATION_ID { get; set; }
        public string SYKI { get; set; }
        public long SYKIID { get; set; }
        public long ADDBY { get; set; }
        public System.DateTime ADDON { get; set; }
        public long UPDATEDBY { get; set; }
        public System.DateTime UPDATEDON { get; set; }
        public string DIVISION { get; set; }
        public long DIVISION_ID { get; set; }
        public long EVP_AUTHORITY { get; set; }
    }
}
