//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class AT_ASSSET_TRANSFER_HEADER
    {
        [Key]
        public int SRNO { get; set; }
        public string TRAN_TYPE { get; set; }
        public long TRAN_NO { get; set; }
        public string TRANSFEROR { get; set; }
        public string APPROVAL_TYPE { get; set; }
        public string TRANSFREE { get; set; }
        public long ADDEDBY { get; set; }
        public System.DateTime ADDEDON { get; set; }
        public long UPDATEDBY { get; set; }
        public System.DateTime UPDATEDON { get; set; }
        public System.DateTime TRAN_DATE { get; set; }
        public string ASSET_TYPE { get; set; }
        public decimal TOTAL { get; set; }
        public long REQ_ECODE { get; set; }
        public string STATUS { get; set; }
        public string PDFPATH { get; set; }
        public string GETOUT_DOC_PATH { get; set; }
        public string GETIN_DOC_PATH { get; set; }
        public string NEW_LOCATION { get; set; }
        public string TRANSFREE_TYPE { get; set; }
        public string REMARKS { get; set; }
        public string COMPANYDEFINE_AUTHORITY { get; set; }
        public string DURATION { get; set; }
        public Nullable<long> GATEOUTSTAMP { get; set; }
    }
}
