//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class AT_APPROVAL_AUTHORITY_LOG
    {
        [Key]
        public int SRNO { get; set; }
        public long TRAN_NO { get; set; }
        public long EMP_CODE { get; set; }
        public string APPROVAL_STATUS { get; set; }
        public string EMP_NAME { get; set; }
        public string DEPARTMENT { get; set; }
        public string DESIGNATION { get; set; }
        public string REMARKS { get; set; }
        public long ADDEDBY { get; set; }
        public System.DateTime ADDEDON { get; set; }
        public long UPDATEDBY { get; set; }
        public System.DateTime UPDATEDON { get; set; }
    }
}
