//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class AT_ASSET_TRANSFER_DETAIL
    {
        [Key]
        public int SRNO { get; set; }
        public int TRAN_NO { get; set; }
        public string ASSET_CODE { get; set; }
        public string PO_NO { get; set; }
        public Nullable<System.DateTime> PO_DATE { get; set; }
        public string FULLY_PARTIAL { get; set; }
        public Nullable<decimal> QTY { get; set; }
        public string CURRENT_LOCATION { get; set; }
        public string NEW_LOCATION { get; set; }
        public decimal ORIGINAL_COST { get; set; }
        public decimal DEPRECIATION { get; set; }
        public decimal NET_BLOCK { get; set; }
        public string INV_NO { get; set; }
        public Nullable<System.DateTime> INV_DATE { get; set; }
        public string ASSET_SERIAL_NO { get; set; }
        public Nullable<long> ASSET_CLASS { get; set; }
        public Nullable<System.DateTime> CAPITALIZED_DATE { get; set; }
        public string VENDER_NAME { get; set; }
        public string VENDOR_CODE { get; set; }
        public string ASSETMAIN_NO_TEXT { get; set; }
        public string LICENSE_NO { get; set; }
        public Nullable<System.DateTime> LICENSE_DATE { get; set; }
        public Nullable<long> HSN_CODE { get; set; }
        public long ADDEDBY { get; set; }
        public System.DateTime ADDEDON { get; set; }
        public long UPDATEDBY { get; set; }
        public System.DateTime UPDATEDON { get; set; }
        public string DESCRIPTION { get; set; }
        public string NEW_ASSET_CODE { get; set; }
        public string ASSET_ATTACH { get; set; }
        public decimal BASIC_PRICE { get; set; }
        public decimal INVOICE_VALUE { get; set; }
        public string ASSET_CLS_DESC { get; set; }
        public string SUBAUCCODE { get; set; }
        public string EODC_CLEAREANSE { get; set; }
    }
}
