//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class BC_ALACARTEFOOD_TRN_DGIT
    {
        [Key]
        public long ALACARTEFOODTRN_ID { get; set; }
        public long ALACARTEFOODHDR_ID { get; set; }
        public short ITEM_QTY { get; set; }
        public short DELIVERY_TYPE { get; set; }
        public short STATUS { get; set; }
        public long ADDEDBY { get; set; }
        public System.DateTime ADDEDDATE { get; set; }
        public Nullable<long> LSTMODIFIEDBY { get; set; }
        public Nullable<System.DateTime> LSTMODDATE { get; set; }
        public long ITEMID { get; set; }
        public decimal ITEM_PRICE { get; set; }
        public short ITEM_STATUS { get; set; }
    
        //public virtual BC_ALACARTEFOOD_HDR_DGIT BC_ALACARTEFOOD_HDR { get; set; }
        //public virtual BC_ALACARTEFOOD_MST_DGIT BC_ALACARTEFOOD_MST { get; set; }
    }
}
