//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class BC_ALACARTEFOOD_MST_DGIT
    {
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        //public BC_ALACARTEFOOD_MST_DGIT()
        //{
        //    this.BC_ALACARTEFOOD_TRN = new HashSet<BC_ALACARTEFOOD_TRN_DGIT>();
        //}

        [Key]
        public long BC_FOODMSTID { get; set; }
        public short ITEM_CATEGORY { get; set; }
        public string ITEM_NAME { get; set; }
        public decimal ITEM_PRICE { get; set; }
        public short LEAD_TIME { get; set; }
        public short TAKE_WAY { get; set; }
        public short DINE_IN { get; set; }
        public short STATUS { get; set; }
        public long ADDEDBY { get; set; }
        public System.DateTime ADDEDDATE { get; set; }
        public long? LSTMODIFIEDBY { get; set; }
        public DateTime? LSTMODDATE { get; set; }
        public byte[] ITEM_PHOTO { get; set; }
        public string ITEM_PHOTO_NAME { get; set; }

        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<BC_ALACARTEFOOD_TRN_DGIT> BC_ALACARTEFOOD_TRN { get; set; }
    }
}
