//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class BC_ADMIN_MEALSBOOKING_TRN
    {
        public long BC_ADMINBOOKING_ID { get; set; }
        public long MEALS_AVAILABILITY_ID { get; set; }
        public long MEALTYPEID { get; set; }
        public System.DateTime MEAL_BOOKED_DATE { get; set; }
        public short MEAL_STATUS { get; set; }
        public long ADDEDBY { get; set; }
        public System.DateTime ADDEDDATE { get; set; }
        public Nullable<long> LSTMODIFIEDBY { get; set; }
        public Nullable<System.DateTime> LSTMODDATE { get; set; }
        public Nullable<long> SLOTID { get; set; }
    
        public virtual BC_MST_MEAL_TYPE BC_MST_MEAL_TYPE { get; set; }
        public virtual BC_MEALS_AVAILABILITY BC_MEALS_AVAILABILITY { get; set; }
    }
}
