//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class BC_ALACARTEFOOD_HDR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BC_ALACARTEFOOD_HDR()
        {
            this.BC_ALACARTEFOOD_TRN = new HashSet<BC_ALACARTEFOOD_TRN>();
        }
    
        public long ALACARTEFOODHDR_ID { get; set; }
        public System.DateTime ORDER_DATE { get; set; }
        public short ORDER_STATUS { get; set; }
        public long ADDEDBY { get; set; }
        public System.DateTime ADDEDDATE { get; set; }
        public Nullable<long> LSTMODIFIEDBY { get; set; }
        public Nullable<System.DateTime> LSTMODDATE { get; set; }
        public Nullable<System.DateTime> ACCEPTED_DATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BC_ALACARTEFOOD_TRN> BC_ALACARTEFOOD_TRN { get; set; }
    }
}
