//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class BC_FMLY_SLOT_MAP
    {
        public long ID { get; set; }
        public System.DateTime ALLOW_DATE { get; set; }
        public long SLOT_ID { get; set; }
        public short STATUS { get; set; }
        public System.DateTime CREATED_ON { get; set; }
        public long CREATED_BY { get; set; }
        public DateTime? UPDATED_ON { get; set; }
        public long? UPDATED_BY { get; set; }
    }
}
