//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("BC_FAMILYMEALBOOKING_TRN")]
    public partial class BC_FAMILYMEALBOOKING_TRN_DGIT
    {
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        //public BC_FAMILYMEALBOOKING_TRN_DGIT()
        //{
        //    this.BC_FAMILYMEALBOOKING_DTL = new HashSet<BC_FAMILYMEALBOOKING_DTL_DGIT>();
        //}

        [Key]
        public long BC_FAMILY_BOOKINGID { get; set; }
        public System.DateTime MEAL_BOOKED_DATE { get; set; }
        public short MEAL_STATUS { get; set; }
        public long ADDEDBY { get; set; }
        public System.DateTime ADDEDDATE { get; set; }
        public long? LSTMODIFIEDBY { get; set; }
        public DateTime? LSTMODDATE { get; set; }
        public long SLOTID { get; set; }
        public string TOKEN_CODE { get; set; }
        public short? ADMIN_STAUS { get; set; }
        public DateTime? ADMIN_DATE { get; set; }
        public long? ADMIN_ECODE { get; set; }

        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<BC_FAMILYMEALBOOKING_DTL_DGIT> BC_FAMILYMEALBOOKING_DTL { get; set; }
    }
}
