//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class BC_FAMILYMEALBOOKING_DTL_DGIT
    {
        [Key]
        public long BC_FAMILYMEALBOOKING_DTLID { get; set; }
        public long BC_FAMILY_BOOKINGID { get; set; }
        public string MEMBER_NAME { get; set; }
        public string RELATION_TYPE { get; set; }
        public long ADDEDBY { get; set; }
        public System.DateTime ADDEDDATE { get; set; }
        public Nullable<long> LSTMODIFIEDBY { get; set; }
        public Nullable<System.DateTime> LSTMODDATE { get; set; }
        public short STATUS { get; set; }
        public Nullable<long> MEALS_AVAILABILITY_ID { get; set; }
        public Nullable<long> MEALTYPEID { get; set; }

        //public virtual BC_FAMILYMEALBOOKING_TRN_DGIT BC_FAMILYMEALBOOKING_TRN { get; set; }
    }
}
