//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class BC_GUESTMEALBOOKING_TRN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BC_GUESTMEALBOOKING_TRN()
        {
            this.BC_GUESTMEALBOOKING_DTL = new HashSet<BC_GUESTMEALBOOKING_DTL>();
        }
    
        public long BC_GUEST_BOOKINGID { get; set; }
        public long MEALS_AVAILABILITY_ID { get; set; }
        public long MEALTYPEID { get; set; }
        public System.DateTime MEAL_BOOKED_DATE { get; set; }
        public short MEAL_STATUS { get; set; }
        public long ADDEDBY { get; set; }
        public System.DateTime ADDEDDATE { get; set; }
        public Nullable<long> LSTMODIFIEDBY { get; set; }
        public Nullable<System.DateTime> LSTMODDATE { get; set; }
        public long APPROVER_ECODE { get; set; }
        public short APPROVE_STATUS { get; set; }
        public Nullable<System.DateTime> APPROVE_DATE { get; set; }
        public string APPROVE_REMARK { get; set; }
        public short PAYMENT_TYPE { get; set; }
        public long SLOTID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BC_GUESTMEALBOOKING_DTL> BC_GUESTMEALBOOKING_DTL { get; set; }
        public virtual BC_MEALS_AVAILABILITY BC_MEALS_AVAILABILITY { get; set; }
        public virtual BC_MST_MEAL_TYPE BC_MST_MEAL_TYPE { get; set; }
    }
}
