//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class BC_GUEST_DTL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BC_GUEST_DTL()
        {
            this.BC_GUESTMEALBOOKING_DTL = new HashSet<BC_GUESTMEALBOOKING_DTL>();
        }
    
        public long BC_GUESTID { get; set; }
        public string GUEST_NAME { get; set; }
        public long MOBILE_NUMBER { get; set; }
        public string COMPANY { get; set; }
        public short STATUS { get; set; }
        public long ADDEDBY { get; set; }
        public System.DateTime ADDEDDATE { get; set; }
        public Nullable<long> LSTMODIFIEDBY { get; set; }
        public Nullable<System.DateTime> LSTMODDATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BC_GUESTMEALBOOKING_DTL> BC_GUESTMEALBOOKING_DTL { get; set; }
    }
}
