//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class BC_GUESTMEALBOOKING_DTL
    {
        public long BC_BOOKINGDTLID { get; set; }
        public long GUESTDTLID { get; set; }
        public string TOKEN_CODE { get; set; }
        public decimal MEAL_PRICE { get; set; }
        public long ADDEDBY { get; set; }
        public System.DateTime ADDEDDATE { get; set; }
        public Nullable<long> LSTMODIFIEDBY { get; set; }
        public Nullable<System.DateTime> LSTMODDATE { get; set; }
        public Nullable<short> ADMIN_STAUS { get; set; }
        public Nullable<System.DateTime> ADMIN_DATE { get; set; }
        public Nullable<long> ADMIN_ECODE { get; set; }
        public long BC_GUESTMEALBOOKINGID { get; set; }
    
        public virtual BC_GUEST_DTL BC_GUEST_DTL { get; set; }
        public virtual BC_GUESTMEALBOOKING_TRN BC_GUESTMEALBOOKING_TRN { get; set; }
    }
}
