//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class BC_HRECODEMAP
    {
        public decimal BC_HRECODEMAPID { get; set; }
        public long EMPCODE { get; set; }
        public long HRIDCODE { get; set; }
        public Nullable<decimal> STATUS { get; set; }
        public decimal CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public Nullable<decimal> MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public Nullable<long> SAVIORCODE { get; set; }
        public Nullable<long> HRIDPAYCODE { get; set; }
    }
}
