//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class BC_MEALSLOTMST
    {
        public long BCSLOTMSTID { get; set; }
        public string SLOT_DESC { get; set; }
        public string SLOT_TIME { get; set; }
        public short CAPACITY { get; set; }
        public long MEALTYPEID { get; set; }
        public short STATUS { get; set; }
        public long ADDEDBY { get; set; }
        public System.DateTime ADDEDDATE { get; set; }
        public Nullable<long> LSTMODIFIEDBY { get; set; }
        public Nullable<System.DateTime> LSTMODDATE { get; set; }
    
        public virtual BC_MST_MEAL_TYPE BC_MST_MEAL_TYPE { get; set; }
    }
}
