//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class BC_MEALSBOOKING_TRN_DGIT
    {
        [Key]
        public long BC_MEALSBOOKING_ID { get; set; }
        public long MEALS_AVAILABILITY_ID { get; set; }
        public long MEALTYPEID { get; set; }
        public System.DateTime MEAL_BOOKED_DATE { get; set; }
        public short MEAL_STATUS { get; set; }
        public long ADDEDBY { get; set; }
        public System.DateTime ADDEDDATE { get; set; }
        public long? LSTMODIFIEDBY { get; set; }
        public DateTime? LSTMODDATE { get; set; }
        public short REQUEST_TYPE { get; set; }
        public long? REQUEST_BY { get; set; }
        public long SLOTID { get; set; }

        //public virtual BC_MEALS_AVAILABILITY_DGIT BC_MEALS_AVAILABILITY { get; set; }
        //public virtual BC_MST_MEAL_TYPE_DGIT BC_MST_MEAL_TYPE { get; set; }
    }
}
