//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class BC_MST_VALIDATION
    {
        public long BC_MST_VALIDATION_ID { get; set; }
        public string MEAL_UPDATE_PERIOD { get; set; }
        public string MEAL_CHANGE_TIME { get; set; }
        public string MEAL_BOOKING_DURATION { get; set; }
        public string MEAL_BOOKING_TIME { get; set; }
        public string MEAL_CANCELLATION_TIME { get; set; }
        public long ADDEDBY { get; set; }
        public System.DateTime ADDEDDATE { get; set; }
        public Nullable<long> LSTMODIFIEDBY { get; set; }
        public Nullable<System.DateTime> LSTMODDATE { get; set; }
        public Nullable<long> INDIANMEAL_QTY { get; set; }
        public Nullable<long> JAPANESEMEAL_QTY { get; set; }
        public string MEAL_BOOKING_DAY { get; set; }
        public Nullable<short> ALACARTESUBSIDY { get; set; }
        public Nullable<decimal> ALACARTESUBSIDY_MAX { get; set; }
        public string ALACARTE_BOOKING_TIME { get; set; }
        public string GUEST_BOOKING_TIME { get; set; }
        public string GUEST_CANCELLATION_TIME { get; set; }
        public string GUEST_BOOKING_DAY { get; set; }
        public string GUEST_BOOKING_SELFAPP { get; set; }
        public string JAPANESEMEAL_BOOKING_DAY { get; set; }
        public string JAPANESEMEAL_BOOKING_TIME { get; set; }
        public string JAPANESEMEAL_CANCELLATION_TIME { get; set; }
    }
}
