//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class BC_MEETINGFOOD_TRN
    {
        [Key]
        public long MEETINGFOODTRN_ID { get; set; }
        public long MEETINGFOODHDR_ID { get; set; }
        public short ITEM_QTY { get; set; }
        public short STATUS { get; set; }
        public long ADDEDBY { get; set; }
        public System.DateTime ADDEDDATE { get; set; }
        public Nullable<long> LSTMODIFIEDBY { get; set; }
        public DateTime? LSTMODDATE { get; set; }
        public long ITEMID { get; set; }
        public decimal ITEM_PRICE { get; set; }
        public short ITEM_STATUS { get; set; }
        public short ITEM_QTY_ADMIN { get; set; }
    }
}
