//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class BC_MENUMST
    {
        public long BCMENUID { get; set; }
        public string MENU_NAME { get; set; }
        public string MENU_DESC { get; set; }
        public string MENU_URL { get; set; }
        public byte[] MENU_ICON { get; set; }
        public string MENUICON_CONTENT_TYPE { get; set; }
        public string MENUICON_FILENAME { get; set; }
        public short STATUS { get; set; }
        public long CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public Nullable<long> MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public Nullable<long> DISPLAY_ORDER { get; set; }
    }
}
