//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class BC_MST_MEALS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BC_MST_MEALS()
        {
            this.BC_MEALS_AVAILABILITY = new HashSet<BC_MEALS_AVAILABILITY>();
        }
    
        public long BC_MEALID { get; set; }
        public long MEALTYPEID { get; set; }
        public string MEAL_NAME { get; set; }
        public string MEAL_DESC { get; set; }
        public decimal MEAL_PRICE { get; set; }
        public short STATUS { get; set; }
        public long ADDEDBY { get; set; }
        public System.DateTime ADDEDDATE { get; set; }
        public Nullable<long> LSTMODIFIEDBY { get; set; }
        public Nullable<System.DateTime> LSTMODDATE { get; set; }
        public byte[] MEAL_PHOTO { get; set; }
        public string MEAL_PHOTO_NAME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BC_MEALS_AVAILABILITY> BC_MEALS_AVAILABILITY { get; set; }
        public virtual BC_MST_MEAL_TYPE BC_MST_MEAL_TYPE { get; set; }
    }
}
