//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class BC_MEALS_AVAILABILITY_DGIT
    {
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        //public BC_MEALS_AVAILABILITY_DGIT()
        //{
        //    this.BC_ADMIN_MEALSBOOKING_TRN = new HashSet<BC_ADMIN_MEALSBOOKING_TRN_DGIT>();
        //    this.BC_GUESTMEALBOOKING_TRN = new HashSet<BC_GUESTMEALBOOKING_TRN_DGIT>();
        //    this.BC_MEALSBOOKING_TRN = new HashSet<BC_MEALSBOOKING_TRN_DGIT>();
        //}
        [Key]
        public long BC_MEALS_AVAILABILITY_ID { get; set; }
        public long MEALS_ID { get; set; }
        public System.DateTime MEAL_MAPPING_DATE { get; set; }
        public short STATUS { get; set; }
        public long ADDEDBY { get; set; }
        public System.DateTime ADDEDDATE { get; set; }
        public long? LSTMODIFIEDBY { get; set; }
        public DateTime? LSTMODDATE { get; set; }

        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<BC_ADMIN_MEALSBOOKING_TRN_DGIT> BC_ADMIN_MEALSBOOKING_TRN { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<BC_GUESTMEALBOOKING_TRN_DGIT> BC_GUESTMEALBOOKING_TRN { get; set; }
        //public virtual BC_MST_MEALS_DGIT BC_MST_MEALS { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<BC_MEALSBOOKING_TRN_DGIT> BC_MEALSBOOKING_TRN { get; set; }
    }
}
