//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class BC_PRICE_VALIDITY_DGIT
    {
        [Key]
        public long BC_PRICE_VALIDITYID { get; set; }
        public long MEALTYPEID { get; set; }
        public decimal MEAL_AMOUNT { get; set; }
        public decimal MEAL_AMT_DEDUCTIBLE { get; set; }
        public System.DateTime FROM_DATE { get; set; }
        public System.DateTime TO_DATE { get; set; }
        public short STATUS { get; set; }
        public long ADDEDBY { get; set; }
        public System.DateTime ADDEDDATE { get; set; }
        public long? LSTMODIFIEDBY { get; set; }
        public DateTime? LSTMODDATE { get; set; }

        //public virtual BC_MST_MEAL_TYPE_DGIT BC_MST_MEAL_TYPE { get; set; }
    }
}
