//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class BC_SUBSIDIZED_MEAL_TOKEN_DGIT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BC_SUBSIDIZED_MEAL_TOKEN_DGIT()
        {
            this.BC_SUSIDIZED_MEAL_TRN = new HashSet<BC_SUSIDIZED_MEAL_TRN_DGIT>();
        }
    
        public long BC_SUBSIDIZED_MEAL_TOKEN_ID { get; set; }
        public Nullable<long> EMPLOYEE_ID { get; set; }
        public string TOKEN_CODE { get; set; }
        public Nullable<System.DateTime> TOKEN_DATE { get; set; }
        public short STATUS { get; set; }
        public long ADDEDBY { get; set; }
        public System.DateTime ADDEDDATE { get; set; }
        public Nullable<long> LSTMODIFIEDBY { get; set; }
        public Nullable<System.DateTime> LSTMODDATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BC_SUSIDIZED_MEAL_TRN_DGIT> BC_SUSIDIZED_MEAL_TRN { get; set; }
    }
}
