//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class BC_SUSIDIZED_MEAL_TRN_DGIT
    {
        public long BC_SUBSIDIZED_MEAL_TRN_ID { get; set; }
        public Nullable<long> BC_SUBSIDIZED_MEAL_TOKEN_ID { get; set; }
        public Nullable<long> EMPLOYEE_ID { get; set; }
        public Nullable<decimal> TOTAL_MEAL_AMOUNT { get; set; }
        public Nullable<decimal> SUBSIDIZED_AMOUNT { get; set; }
        public Nullable<decimal> PAYABLE_AMOUNT { get; set; }
        public short STATUS { get; set; }
        public long ADDEDBY { get; set; }
        public System.DateTime ADDEDDATE { get; set; }
        public Nullable<long> LSTMODIFIEDBY { get; set; }
        public Nullable<System.DateTime> LSTMODDATE { get; set; }
    
        public virtual BC_SUBSIDIZED_MEAL_TOKEN_DGIT BC_SUBSIDIZED_MEAL_TOKEN { get; set; }
    }
}
