//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CALENDARMASTERHEADER
    {
        [Key]
        public long SRNO { get; set; }
        public string CALENDER { get; set; }
        public string LOCATION { get; set; }
        public string FINANCIALYEAR { get; set; }
        public byte[] CALENDER_BLOB { get; set; }
        public string CALENDER_CONTENTTYPE { get; set; }
        public string CALENDER_UPLOAD { get; set; }
        public Nullable<long> APP_AUTH1 { get; set; }
        public string APPAUTH1_REMARKS { get; set; }
        public Nullable<System.DateTime> APPAUTH1_DATE { get; set; }
        public Nullable<long> APP_AUTH2 { get; set; }
        public string APPAUTH2_REMARKS { get; set; }
        public Nullable<System.DateTime> APPAUTH2_DATE { get; set; }
        public Nullable<long> STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    }
}
