//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CALENDARMASTERAPPHIS
    {
        [Key]
        public long CALENDERMAPPINGID { get; set; }
        public Nullable<long> CAL_MAS_SRNO { get; set; }
        public Nullable<long> STATUS { get; set; }
        public Nullable<long> APPAUTH_ECODE { get; set; }
        public Nullable<System.DateTime> APPAUTH_DATE { get; set; }
        public string APPAUTH_REMARKS { get; set; }
        public Nullable<long> CREATEDBY { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public Nullable<long> MODIFIEDBY { get; set; }
        public Nullable<System.DateTime> MODIFIEDDATE { get; set; }
        public Nullable<long> APP_LEVEL { get; set; }
    }
}
