//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CM_COMMUNICATION_HDR
    {
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        //public CM_COMMUNICATION_HDR()
        //{
        //    this.CM_COMMAPPAUTH_SEQ = new HashSet<CM_COMMAPPAUTH_SEQ>();
        //    this.CM_COMMUNICATION_APPHISTORY = new HashSet<CM_COMMUNICATION_APPHISTORY>();
        //    this.CM_COMMUNICATION_DTL = new HashSet<CM_COMMUNICATION_DTL>();
        //}
        [Key]
        public long COMMUNICATIONID { get; set; }
        public long COMM_CATID { get; set; }
        public long COMM_MAILTYPEID { get; set; }
        public string SUBJECT { get; set; }
        public string CONTENT { get; set; }
        public DateTime? START_DATE { get; set; }
        public DateTime? END_DATE { get; set; }
        public short STATUS { get; set; }
        public short PROCESS_STATUS { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public long CREATED_BY { get; set; }
        public long? MODIFIED_BY { get; set; }
        public DateTime? MODIFIED_DATE { get; set; }
        public string FUNCTIONAL_DESIGNATION { get; set; }
        public string DESIGNATION { get; set; }
        public string SITE { get; set; }
        public string REQUESTNO { get; set; }
        public short EMAILSTATUS { get; set; }
        public short RECIPIENT { get; set; }
        public short MAIL_SENT_STATUS { get; set; }
        public short REQUEST_TYPE { get; set; }
        public string EMAIL_CONTENT { get; set; }
        public string OPERATION { get; set; }
        public string DIVISION { get; set; }
        public string DEPARTMENT { get; set; }
        public string SUBJECT_ORIG { get; set; }
        public string CONTENT_ORIG { get; set; }
        public string EMAIL_CONTENT_ORIG { get; set; }
    
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<CM_COMMAPPAUTH_SEQ> CM_COMMAPPAUTH_SEQ { get; set; }
        //public virtual CM_COMMCATEGORY_MST CM_COMMCATEGORY_MST { get; set; }
        //public virtual CM_COMMTYPE_MST CM_COMMTYPE_MST { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<CM_COMMUNICATION_APPHISTORY> CM_COMMUNICATION_APPHISTORY { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<CM_COMMUNICATION_DTL> CM_COMMUNICATION_DTL { get; set; }
    }
}
