//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CM_COMMCATEGORY_MST
    {
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        //public CM_COMMCATEGORY_MST()
        //{
        //    this.CM_COMMUNICATION_HDR = new HashSet<CM_COMMUNICATION_HDR>();
        //}
        [Key]
        public long COMMCATEGORYID { get; set; }
        public string CATEGORY_NAME { get; set; }
        public short STATUS { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public long CREATED_BY { get; set; }
        public long? MODIFIED_BY { get; set; }
        public DateTime? MODIFIED_DATE { get; set; }
        public byte APP_REQUIRED_TILL { get; set; }
        public short ISREQ_TEMPLATE { get; set; }
        public short ISREQ_BANNER { get; set; }
        public short ISREQ_OTHER { get; set; }
    
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<CM_COMMUNICATION_HDR> CM_COMMUNICATION_HDR { get; set; }
    }
}
