//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CM_COMMREQ_VIEWEMPMAPP
    {
        [Key]
        public long COMMVIEW_MAPPID { get; set; }
        public long COMMUNICATIONID { get; set; }
        public long ADEMPCODE { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public long CREATED_BY { get; set; }
        public Nullable<long> MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    }
}
