//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CM_PRESIDENT_MST
    {
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        //public CM_PRESIDENT_MST()
        //{
        //    this.CM_PRESIDENTMSG_TRN = new HashSet<CM_PRESIDENTMSG_TRN>();
        //}
        [Key]
        public long PRESIDENT_ID { get; set; }
        public string PRESIDENT_NAME { get; set; }
        public byte[] PRESIDENT_PHOTO { get; set; }
        public string PRESIDENT_TITLE { get; set; }
        public System.DateTime ACTIVE_FROM { get; set; }
        public DateTime? ACTIVE_TO { get; set; }
        public short STATUS { get; set; }
        public string REMARKS { get; set; }
        public long CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public long? MODIFIED_BY { get; set; }
        public DateTime? MODIFIED_DATE { get; set; }
        public string PHOTO_CONTENTTYPE { get; set; }
        public string PHOTO_NAME { get; set; }
    
        //public virtual ADLOGINUSER ADLOGINUSER { get; set; }
        //public virtual ADLOGINUSER ADLOGINUSER1 { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<CM_PRESIDENTMSG_TRN> CM_PRESIDENTMSG_TRN { get; set; }
    }
}
