//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CM_PRESIDENTMSGAPP_TRN
    {
        [Key]
        public long MESSAGEAPP_ID { get; set; }
        public long PRESIDENTMSG_ID { get; set; }
        public long STATUS { get; set; }
        public string INITIATOR_REMARKS { get; set; }
        public long CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public Nullable<long> APPROVED_BY { get; set; }
        public Nullable<System.DateTime> APPROVED_DATE { get; set; }
        public string APPAUTH_REMARKS { get; set; }
    
        //public virtual ADLOGINUSER ADLOGINUSER { get; set; }
        //public virtual ADLOGINUSER ADLOGINUSER1 { get; set; }
        //public virtual CM_PRESIDENTMSG_TRN CM_PRESIDENTMSG_TRN { get; set; }
    }
}
