//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CM_PRESIDENTMSG_TRN
    {
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        //public CM_PRESIDENTMSG_TRN()
        //{
        //    this.CM_PRESIDENTMSGAPP_TRN = new HashSet<CM_PRESIDENTMSGAPP_TRN>();
        //}
        [Key]
        public long PRESIDENTMSG_ID { get; set; }
        public long PRESIDENT_ID { get; set; }
        public string BRIEF { get; set; }
        public string? MESSAGE { get; set; }
        public byte[] ATTACHMENT { get; set; }
        public System.DateTime VALID_FROM { get; set; }
        public System.DateTime VALID_TO { get; set; }
        public short STATUS { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public long CREATED_BY { get; set; }
        public DateTime? MODIFIED_DATE { get; set; }
        public long? MODIFIED_BY { get; set; }
        public decimal SYKIID { get; set; }
        public string? ATTACHMENT_CONTENTTYPE { get; set; }
        public string? ATTACHMENT_NAME { get; set; }
    
        //public virtual ADLOGINUSER ADLOGINUSER { get; set; }
        //public virtual ADLOGINUSER ADLOGINUSER1 { get; set; }
        //public virtual CM_PRESIDENT_MST CM_PRESIDENT_MST { get; set; }
        //public virtual SYKI SYKI { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<CM_PRESIDENTMSGAPP_TRN> CM_PRESIDENTMSGAPP_TRN { get; set; }
    }
}
