//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CM_PROCESSATTACHMENTAPPMAPPING_TRN
    {
        
        public long ATTACHMENTID { get; set; }
        public short? STATUS { get; set; }
        public long? APPAUTH_ECODE { get; set; }
        public System.DateTime? APPAUTH_DATE { get; set; }
        public string APPAUTH_REMARKS { get; set; }
        public long? CREATED_BY { get; set; }
        public System.DateTime? CREATED_DATE { get; set; }
        public long? MODIFIED_BY { get; set; }
        public System.DateTime? MODIFIED_DATE { get; set; }
        [Key]
        public long MAPPINGATTACHMENTID { get; set; }
        public long? APP_LEVEL { get; set; }
    }
}
