//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class CM_PROCESS_MST
    {
        [Key]
        [Column("MSTPROCESSID")]
        public long MSTPROCESSID { get; set; }
        public string PROCESS_NAME { get; set; }
        public short STATUS { get; set; }
        public DateTime CREATED_DATE { get; set; }
        public long CREATED_BY { get; set; }
        public long? MODIFIED_BY { get; set; }
        public DateTime? MODIFIED_DATE { get; set; }
        public byte[] PROCESS_BANNER { get; set; }
        public string? BANNER_CONTENTTYPE { get; set; }
        public string? BANNER_NAME { get; set; }

        //public ICollection<CM_PROCESSATTACHMENT_TRN> CM_PROCESSATTACHMENT_TRN { get; set; } = new List<CM_PROCESSATTACHMENT_TRN>();
    }
}
