//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CM_PROCESSSCREENSAVER_MST
    {
        [Key]
        public int SAVERID { get; set; }
        public string DEPARTNAME { get; set; }
        public string FILE_CONTENTTYPE { get; set; }
        public string FILE_NAME { get; set; }
        public Nullable<int> STATUS { get; set; }
        public Nullable<System.DateTime> LASTREVISEDDATE { get; set; }
        public Nullable<int> ADDEDBY { get; set; }
        public Nullable<System.DateTime> ADDEDON { get; set; }
        public Nullable<int> MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_ON { get; set; }
    }
}
