//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CSD_GUESTMEALBOOKING_DTL
    {
        [Key]
        public long CSD_BOOKINGDTLID { get; set; }
        public long GUESTDTLID { get; set; }
        public string TOKEN_CODE { get; set; }
        public decimal MEAL_PRICE { get; set; }
        public long ADDEDBY { get; set; }
        public System.DateTime ADDEDDATE { get; set; }
        public long? LSTMODIFIEDBY { get; set; }
        public DateTime? LSTMODDATE { get; set; }
        public short? ADMIN_STAUS { get; set; }
        public DateTime? ADMIN_DATE { get; set; }
        public long? ADMIN_ECODE { get; set; }
        public long CSD_GUESTMEALBOOKINGID { get; set; }

        //public virtual BC_GUEST_DTL_DGIT BC_GUEST_DTL { get; set; }
        //public virtual CSD_GUESTMEALBOOKING_TRN CSD_GUESTMEALBOOKING_TRN { get; set; }
    }
}
