//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CSD_MEALOPTION_MST
    {
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        //public CSD_MEALOPTION_MST()
        //{
        //    this.CSD_MEAL_AVAILABILITY = new HashSet<CSD_MEAL_AVAILABILITY>();
        //    this.CSD_MEALTIME_MAP = new HashSet<CSD_MEALTIME_MAP>();
        //}

        [Key]
        public long CSDMEAL_OPTIONID { get; set; }
        public string MEAL_OPTION { get; set; }
        public short STATUS { get; set; }
        public long ADDEDBY { get; set; }
        public System.DateTime ADDEDON { get; set; }
        public long? UPDATEDBY { get; set; }
        public DateTime? UPDATEDON { get; set; }
    
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<CSD_MEAL_AVAILABILITY> CSD_MEAL_AVAILABILITY { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<CSD_MEALTIME_MAP> CSD_MEALTIME_MAP { get; set; }
    }
}
