//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CSD_MEAL_AVAILABILITY
    {
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        //public CSD_MEAL_AVAILABILITY()
        //{
        //    this.CSD_GUESTMEALBOOKING_TRN = new HashSet<CSD_GUESTMEALBOOKING_TRN>();
        //    this.CSD_MEALBOOKING_TRN = new HashSet<CSD_MEALBOOKING_TRN>();
        //}

        [Key]
        public long CSD_MEAL_AVAILABILITY_ID { get; set; }
        public long MEALS_ID { get; set; }
        public System.DateTime MEAL_MAPPING_DATE { get; set; }
        public short STATUS { get; set; }
        public long ADDEDBY { get; set; }
        public System.DateTime ADDEDDATE { get; set; }
        public long? LSTMODIFIEDBY { get; set; }
        public DateTime? LSTMODDATE { get; set; }
        public long MEAL_OPTIONID { get; set; }

        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<CSD_GUESTMEALBOOKING_TRN> CSD_GUESTMEALBOOKING_TRN { get; set; }
        //public virtual CSD_MEALOPTION_MST CSD_MEALOPTION_MST { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<CSD_MEALBOOKING_TRN> CSD_MEALBOOKING_TRN { get; set; }
        //public virtual CSD_MEALMST CSD_MEALMST { get; set; }
    }
}
