//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CSD_MEALTIME_MAP
    {
        [Key]
        public long CSD_TIMEMAPID { get; set; }
        public long MEALTYPEID { get; set; }
        public long MEAL_OPTIONID { get; set; }
        public short MEAL_BOOKING_DURATION { get; set; }
        public short BOOKING_DAY { get; set; }
        public short CANCELLATION_DAY { get; set; }
        public string BOOKING_TIME { get; set; }
        public string CANCELLATION_TIME { get; set; }
        public short GUEST_BOOKING_DAY { get; set; }
        public short GUEST_CANCELLATION_DAY { get; set; }
        public string GUEST_BOOKING_TIME { get; set; }
        public string GUEST_CANCELLATION_TIME { get; set; }
        public short STATUS { get; set; }
        public long ADDEDBY { get; set; }
        public System.DateTime ADDEDDATE { get; set; }
        public long? LSTMODIFIEDBY { get; set; }
        public DateTime? LSTMODDATE { get; set; }

        //public virtual CSD_MEALOPTION_MST CSD_MEALOPTION_MST { get; set; }
        //public virtual CSD_MEALTYPE_MST CSD_MEALTYPE_MST { get; set; }
    }
}
