//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CSD_MEALMST
    {
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        //public CSD_MEALMST()
        //{
        //    this.CSD_MEAL_AVAILABILITY = new HashSet<CSD_MEAL_AVAILABILITY>();
        //}

        [Key]
        public long CSD_MEALID { get; set; }
        public long MEALTYPEID { get; set; }
        public string MEAL_NAME { get; set; }
        public string MEAL_DESC { get; set; }
        public decimal MEAL_PRICE { get; set; }
        public short STATUS { get; set; }
        public long ADDEDBY { get; set; }
        public System.DateTime ADDEDDATE { get; set; }
        public Nullable<long> LSTMODIFIEDBY { get; set; }
        public Nullable<System.DateTime> LSTMODDATE { get; set; }
        public byte[] MEAL_PHOTO { get; set; }
        public string MEAL_PHOTO_NAME { get; set; }

        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<CSD_MEAL_AVAILABILITY> CSD_MEAL_AVAILABILITY { get; set; }
        //public virtual CSD_MEALTYPE_MST CSD_MEALTYPE_MST { get; set; }
    }
}
