//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CSD_CANTEENMEALTYPE_MAP
    {
        [Key]
        public long CSD_CMTMAPID { get; set; }
        public long MEALTYPE_ID { get; set; }
        public long CANTEENID { get; set; }
        public short STATUS { get; set; }
        public long ADDEDBY { get; set; }
        public System.DateTime ADDEDDATE { get; set; }
        public long? LSTMODIFIEDBY { get; set; }
        public DateTime? LSTMODDATE { get; set; }
    
        //public virtual CSD_CANTEEN_MST CSD_CANTEEN_MST { get; set; }
        //public virtual CSD_MEALTYPE_MST CSD_MEALTYPE_MST { get; set; }
    }
}
