//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CSD_MEALTYPE_MST
    {
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        //public CSD_MEALTYPE_MST()
        //{
        //    this.CSD_CANTEENMEALTYPE_MAP = new HashSet<CSD_CANTEENMEALTYPE_MAP>();
        //    this.CSD_GUESTMEALBOOKING_TRN = new HashSet<CSD_GUESTMEALBOOKING_TRN>();
        //    this.CSD_MEALBOOKING_TRN = new HashSet<CSD_MEALBOOKING_TRN>();
        //    this.CSD_MEALMST = new HashSet<CSD_MEALMST>();
        //    this.CSD_MEALTIME_MAP = new HashSet<CSD_MEALTIME_MAP>();
        //    this.CSD_PRICE_VALIDITY = new HashSet<CSD_PRICE_VALIDITY>();
        //    this.CSD_READER_MAPP = new HashSet<CSD_READER_MAPP>();
        //}

        [Key]
        public long CSD_MEALTYPEID { get; set; }
        public string MEAL_TYPE_DESC { get; set; }
        public short STATUS { get; set; }
        public long ADDEDBY { get; set; }
        public System.DateTime ADDEDDATE { get; set; }
        public long? LSTMODIFIEDBY { get; set; }
        public DateTime? LSTMODDATE { get; set; }
        public long MEAL_QTY { get; set; }

        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<CSD_CANTEENMEALTYPE_MAP> CSD_CANTEENMEALTYPE_MAP { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<CSD_GUESTMEALBOOKING_TRN> CSD_GUESTMEALBOOKING_TRN { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<CSD_MEALBOOKING_TRN> CSD_MEALBOOKING_TRN { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<CSD_MEALMST> CSD_MEALMST { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<CSD_MEALTIME_MAP> CSD_MEALTIME_MAP { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<CSD_PRICE_VALIDITY> CSD_PRICE_VALIDITY { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<CSD_READER_MAPP> CSD_READER_MAPP { get; set; }
    }
}
