//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CSD_GUESTMEALBOOKING_TRN
    {
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        //public CSD_GUESTMEALBOOKING_TRN()
        //{
        //    this.CSD_GUESTMEALBOOKING_DTL = new HashSet<CSD_GUESTMEALBOOKING_DTL>();
        //}

        [Key]
        public long CSD_GUEST_BOOKINGID { get; set; }
        public long MEALS_AVAILABILITY_ID { get; set; }
        public long MEALTYPEID { get; set; }
        public System.DateTime MEAL_BOOKED_DATE { get; set; }
        public short MEAL_STATUS { get; set; }
        public long APPROVER_ECODE { get; set; }
        public short APPROVE_STATUS { get; set; }
        public DateTime? APPROVE_DATE { get; set; }
        public string APPROVE_REMARK { get; set; }
        public short PAYMENT_TYPE { get; set; }
        public long SLOTID { get; set; }
        public long ADDEDBY { get; set; }
        public System.DateTime ADDEDDATE { get; set; }
        public long? LSTMODIFIEDBY { get; set; }
        public DateTime? LSTMODDATE { get; set; }
        public string VISIT_PURPOSE { get; set; }
        public long MEALOPTIONID { get; set; }

        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<CSD_GUESTMEALBOOKING_DTL> CSD_GUESTMEALBOOKING_DTL { get; set; }
        //public virtual CSD_MEALTYPE_MST CSD_MEALTYPE_MST { get; set; }
        //public virtual CSD_MEAL_AVAILABILITY CSD_MEAL_AVAILABILITY { get; set; }
    }
}
