//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CSD_MEALBOOKING_TRN
    {
        [Key]
        public long CSD_MEALSBOOKING_ID { get; set; }
        public long MEAL_AVAILABILITY_ID { get; set; }
        public long MEALTYPEID { get; set; }
        public System.DateTime MEAL_BOOKED_DATE { get; set; }
        public short MEAL_STATUS { get; set; }
        public long ADDEDBY { get; set; }
        public System.DateTime ADDEDDATE { get; set; }
        public long? LSTMODIFIEDBY { get; set; }
        public DateTime? LSTMODDATE { get; set; }
        public long MEALOPTIONID { get; set; }

        //public virtual CSD_MEAL_AVAILABILITY CSD_MEAL_AVAILABILITY { get; set; }
        //public virtual CSD_MEALTYPE_MST CSD_MEALTYPE_MST { get; set; }
    }
}
