//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class D_TMPL_HEADER
    {
        public string SRNO { get; set; }
        public string TMPL_CODE { get; set; }
        public Nullable<long> USER_CODE { get; set; }
        public string REMARKS { get; set; }
        public string STATUS { get; set; }
        public string EMAILID { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
    }
}
