//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class D_TRANSACTION_STATUS
    {
        public long ID { get; set; }
        public string TMPL_CODE { get; set; }
        public string D_TMPL_HEADERID { get; set; }
        public string SEQID { get; set; }
        public string NATURE { get; set; }
        public Nullable<System.DateTime> RECEIVEDATE { get; set; }
        public string STATUS { get; set; }
        public string URL { get; set; }
        public string REMARKS { get; set; }
        public string USERID { get; set; }
        public string EMAILID { get; set; }
        public string TMPL_NAME { get; set; }
        public string USERNAME { get; set; }
    }
}
