//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class D_TRAN
    {
        public long STAGEID { get; set; }
        public string SEQID { get; set; }
        public string ROUTE { get; set; }
        public string DEPARTMENT { get; set; }
        public string DEPENDENT { get; set; }
        public string MANDATORY { get; set; }
        public string MANDATORYCOND { get; set; }
        public string ENTRYAUTHORITYBY { get; set; }
        public string APPROVALAUTHORITYBY { get; set; }
        public string APPROVALAUTHORITYAPI { get; set; }
        public string STATUSLIST { get; set; }
        public string SENDBACKTO { get; set; }
        public string ALWAYSMOVEFORWARD { get; set; }
        public string FILEUPLOADREQ { get; set; }
        public Nullable<long> MAXDURATION { get; set; }
        public string DEPTHEADNOTIFY { get; set; }
        public Nullable<long> DEPTHEADESCALATION { get; set; }
        public string DIVHEADNOTIFY { get; set; }
        public string DIVHEADESCALATION { get; set; }
        public string DYNAMICFORMSCHEMA { get; set; }
        public string FORMURL { get; set; }
        public string ENTRYUSER { get; set; }
        public string APPROVALUSER { get; set; }
        public string DEPTHEAD { get; set; }
        public string DIVHEAD { get; set; }
        public string OTHER { get; set; }
        public string KEY1 { get; set; }
        public string KEY2 { get; set; }
        public string KEY3 { get; set; }
        public Nullable<System.DateTime> RECEIVEDDATE { get; set; }
        public Nullable<System.DateTime> NOTIONALFINISHDATE { get; set; }
        public Nullable<System.DateTime> ACTUALFINISHDATE { get; set; }
        public string ISSTARTED { get; set; }
        public string ISFINISHED { get; set; }
        public string ISCURRENT { get; set; }
        public string ENTRUSTAGESTATUS { get; set; }
        public string APPROVALSTAGESTATUS { get; set; }
        public string DCNSTATUS { get; set; }
        public string FORM { get; set; }
        public decimal ID { get; set; }
        public string FILEDETAIL { get; set; }
        public string TMPLHEADERID { get; set; }
        public string CANHOLD { get; set; }
        public string DOCUMENTTYPE { get; set; }
        public string FORMDISPTMPL { get; set; }
        public string ENTRYAUTHORITYDETAIL { get; set; }
        public string APPROVALAUTHORITYDETAIL { get; set; }
        public string D_SCRIPT { get; set; }
        public string HOLDJSON { get; set; }
    }
}
