//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DGIT_PRAPPAUTHSEQ
    {
        [Key]
        public long PRAPPAUTH_ID { get; set; }
        public long PRID { get; set; }
        public long ADEMPCODE { get; set; }
        public short APP_SEQ { get; set; }
        public short STATUS { get; set; }
        public long ADDEDBY { get; set; }
        public System.DateTime ADDEDDATE { get; set; }
        public long? UPDATEBY { get; set; }
        public DateTime? UPDATEDATE { get; set; }
        public short APPTYPE { get; set; }
        public short?  PRINTORDER { get; set; }
        public short ISPARALLELAPP { get; set; }
        public string ACTIONFOR { get; set; }
        public short?  IS_SISPR { get; set; }
        public string APP_TYPEINFO { get; set; }
    }
}
