//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DGIT_POHEADER
    {

        [Key]    
        public long POHEADERID { get; set; }
        public string PONO { get; set; }
        public string VENDORID { get; set; }
        public string REMARK { get; set; }
        public short STATUS { get; set; }
        public short PROCESS_STATUS { get; set; }
        public string VENDORMAILID { get; set; }
        public System.DateTime DATEADDED { get; set; }
        public long ADDEDBY { get; set; }
        public Nullable<System.DateTime> UPDATEDATE { get; set; }
        public Nullable<long> UPDATEDBY { get; set; }
        public string CONTRACT_NO { get; set; }
        public string PO_DESC { get; set; }
        public short MAILCNT { get; set; }
        public string PLANTID { get; set; }
        public Nullable<short> VERSION_NO { get; set; }
        public Nullable<short> HIGH_URGENCY { get; set; }
    
       
        //public virtual ICollection<DGIT_PODETAIL> DGIT_PODETAIL { get; set; }
        //public virtual FINVENDORMASTERMST FINVENDORMASTERMST { get; set; }
    }
}
