//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class DGIT_SMOPERATION_MAP
    {
        [Key]
        public long SMMAP_MSTID { get; set; }
        public long ADORGLEVELID { get; set; }
        public long APPROVER1 { get; set; }
        public short ACTIVE { get; set; }
        public System.DateTime DATEADDED { get; set; }
        public long ADDEDBY { get; set; }
        public System.DateTime? DATELSTMOD { get; set; }
        public long? MODIFIEDBY { get; set; }
        public long STARTAMOUNT { get; set; }
        public long ENDAMOUNT { get; set; }
        public long? APPROVER2 { get; set; }
        public long SYKIID { get; set; }
        public short SESORMRN { get; set; }

        [ForeignKey("APPROVER1")]
        public virtual ADEMPLOYEE ADEMPLOYEE { get; set; }
        [ForeignKey("ADORGLEVELID")]
        public virtual ADORGLEVEL ADORGLEVEL { get; set; }
    }
}
