//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class DGIT_SESMRN_DTL
    {
        [Key]
        public long SMDTL_ID { get; set; }
        public long SMHEADERID { get; set; }
        public short STATUS { get; set; }
        public long ADDEDBY { get; set; }
        public System.DateTime ADDEDDATE { get; set; }
        public long? UPDATEDBY { get; set; }
        public DateTime? UPDATEDATE { get; set; }
        public string DOC_TYPE { get; set; }
        public string FILENAME { get; set; }
        public string ADDITIONAL_INFO { get; set; }
        public string SMMO { get; set; }

        [ForeignKey("SMHEADERID")]
        public virtual DGIT_SESMRN_HEADER DGIT_SESMRN_HEADER { get; set; }
    }
}
