//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DGIT_ICASSETREQHEADER
    {
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        //public DGIT_ICASSETREQHEADER()
        //{
        //    this.DGIT_ICASSETAPPAUTHSEQ = new HashSet<DGIT_ICASSETAPPAUTHSEQ>();
        //    this.DGIT_ICASSETAPPHISTORY = new HashSet<DGIT_ICASSETAPPHISTORY>();
        //    this.DGIT_ICASSETDOCDETAIL = new HashSet<DGIT_ICASSETDOCDETAIL>();
        //    this.DGIT_ICASSETREQ_SCHEDULE = new HashSet<DGIT_ICASSETREQ_SCHEDULE>();
        //}
        [Key]
        public long ICASSETREQID { get; set; }
        public string ICTITLE { get; set; }
        public string DEPARTMENT { get; set; }
        public string ICBACKGROUND { get; set; }
        public string ICA00 { get; set; }
        public string ICPURPOSE { get; set; }
        public string TARGET { get; set; }
        public string REQUIREMENT { get; set; }
        public string CONTENTOFEXE { get; set; }
        public decimal? BASIC_BUDGET { get; set; }
        public decimal? BASIC_PROPOSED { get; set; }
        public decimal? TAX_BUDGET { get; set; }
        public decimal? TAX_PROPOSED { get; set; }
        public long ADDEDBY { get; set; }
        public System.DateTime DATEADDED { get; set; }
        public long? MODIFIEDBY { get; set; }
        public System.DateTime? MODIFIEDDATE { get; set; }
        public short PROCESSSTATUS { get; set; }
        public short STATUS { get; set; }
        public string REMARK { get; set; }
        public long? ICCONFIGID { get; set; }
        public short? ISIBMREQUIRED { get; set; }
    
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<DGIT_ICASSETAPPAUTHSEQ> DGIT_ICASSETAPPAUTHSEQ { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<DGIT_ICASSETAPPHISTORY> DGIT_ICASSETAPPHISTORY { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<DGIT_ICASSETDOCDETAIL> DGIT_ICASSETDOCDETAIL { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<DGIT_ICASSETREQ_SCHEDULE> DGIT_ICASSETREQ_SCHEDULE { get; set; }
    }
}
