//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DGIT_PRBUYER_MAP
    {
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        //public DGIT_PRBUYER_MAP()
        //{
        //    this.DGIT_PRPURSTATUS = new HashSet<DGIT_PRPURSTATUS>();
        //}
        [Key]
        public long PRBUYERID { get; set; }
        public long PRHEADERID { get; set; }
        public long BUYER_ECODE { get; set; }
        public short STATUS { get; set; }
        public long ADDEDBY { get; set; }
        public System.DateTime DATEADDED { get; set; }
        public long? MODIFIEDBY { get; set; }
        public DateTime? MODIFIEDDATE { get; set; }
    
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<DGIT_PRPURSTATUS> DGIT_PRPURSTATUS { get; set; }
        //public virtual DGIT_PRHEADER DGIT_PRHEADER { get; set; }
    }
}
