//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DGIT_SIGNAUTHMAP
    {
        [Key]
        public long SIGNAUTHID { get; set; }
        public long OPERATIONID { get; set; }
        public long SIGNAUTHECODE { get; set; }
        public short SIGNAUTHLVL { get; set; }
        public short STATUS { get; set; }
        public System.DateTime ADDEDDATE { get; set; }
        public long ADDEDBY { get; set; }
        public long? MODIFIEDBY { get; set; }
        public DateTime? MODIFIEDDATE { get; set; }
    }
}
