//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class DGIT_ACRAPPHISTORY
    {
        [Key]
        public long ACRAPPHISTORY_ID { get; set; }
        public long ACRID { get; set; }
        public long ADEMPCODE { get; set; }
        public short APPROVAL_STATUS { get; set; }
        public string APPROVAL_REMARK { get; set; }
        public long ADDEDBY { get; set; }
        public System.DateTime ADDEDDATE { get; set; }
        public long? UPDATEBY { get; set; }
        public DateTime? UPDATEDATE { get; set; }
        public DateTime? APP_DATE { get; set; }
        public long?  APP_SEQ { get; set; }
        [ForeignKey("ACRAPPHISTORY_ID")]    
        
        public virtual DGIT_ACRHEADER DGIT_ACRHEADER { get; set; }
    }
}
