//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DGIT_ICCONFIG_MST
    {
        [Key]
        public long ICCONFIGID { get; set; }
        public System.DateTime ICMONTH { get; set; }
        public System.DateTime ICDATE { get; set; }
        public System.DateTime LASTSUBDT { get; set; }
        public short MAILTO { get; set; }
        public long ADDEDBY { get; set; }
        public System.DateTime DATEADDED { get; set; }
        public long? UPDATEDBY { get; set; }
        public System.DateTime? UPDATEDDATE { get; set; }
        public string MAILIDS { get; set; }
        public short? MAILSENTFLAG { get; set; }
        public short? STATUS { get; set; }
        public short ICMEETINGNO { get; set; }
        public string MEETING_LOC { get; set; }
        public string MEETING_TIME { get; set; }
        public string EMAIL_CONTACT { get; set; }
    }
}
