//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DGIT_ICMEMBER_MST
    {
        [Key]
        public long ICMEMBERMSTID { get; set; }
        public long ADEMPCODE { get; set; }
        public short APPTYPE { get; set; }
        public string APPHEADER { get; set; }
        public short ISPARRALLEL { get; set; }
        public short STATUS { get; set; }
        public System.DateTime DATEADDED { get; set; }
        public long ADDEDBY { get; set; }
        public short APP_SEQ { get; set; }
    }
}
