//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DGIT_PRPURSTATUS
    {
        [Key]
        public long PRPURSTATUSID { get; set; }
        public short STATUS { get; set; }
        public string REMARK { get; set; }
        public System.DateTime DATEADDED { get; set; }
        public long ADDEDBY { get; set; }
        public long PRBUYERID { get; set; }
        public long? MODIFIEDBY { get; set; }
        public DateTime? MODIFIEDDATE { get; set; }
    
        //public virtual DGIT_PRBUYER_MAP DGIT_PRBUYER_MAP { get; set; }
    }
}
