//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DGIT_ACR_PAYMENTADVISEMASTER
    {
        public string PAYMENTADVISE_NO { get; set; }
        [Key]
        public decimal ACR_NO { get; set; }
        public string DOCUMENT_PATH { get; set; }
        public short STATUS { get; set; }
        public short ISDELETE { get; set; }
        public string REMARK { get; set; }
        public System.DateTime DATEADDED { get; set; }
        public DateTime? UPDATEDDATE { get; set; }
        public long ADDEDBY { get; set; }
        public long? UPDATEBY { get; set; }
        public System.DateTime PA_DATE { get; set; }
        public int PAHEADER_ID { get; set; }
        public short?  ISSEND { get; set; }
    }
}
