//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DGIT_PRADDAUTH_MAP
    {
        [Key]
        public long PRADDAUTH_ID { get; set; }
        public short PRTYPEID { get; set; }
        public short ORGLVLID { get; set; }
        public long RES_ORGLVLID { get; set; }
        public long SYKI { get; set; }
        public long MODIFIEDBY { get; set; }
        public System.DateTime MODIFIEDDATE { get; set; }
    }
}
