//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DGIT_IOMAPPHISTORY
    {
        [Key]
        public long IOMAPPHISTORY_ID { get; set; }
        public long IOMHEADERID { get; set; }
        public long ADEMPCODE { get; set; }
        public short APPROVAL_STATUS { get; set; }
        public string APPROVAL_REMARK { get; set; }
        public long ADDEDBY { get; set; }
        public System.DateTime ADDEDDATE { get; set; }
        public Nullable<long> UPDATEBY { get; set; }
        public Nullable<System.DateTime> UPDATEDATE { get; set; }
        public Nullable<System.DateTime> APP_DATE { get; set; }
        public short APPTYPE { get; set; }
    }
}
