//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class DGIT_USERDETAIL
    {
        public decimal USRDTLID { get; set; }
        public decimal EMPCODE { get; set; }
        public string DSCTOKENID { get; set; }
    }
}
