//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DGIT_PRAPPHISTORY
    {
        [Key]
        public long PRAPPHISTORY_ID { get; set; }
        public long PRID { get; set; }
        public long ADEMPCODE { get; set; }
        public short APPROVAL_STATUS { get; set; }
        public string APPROVAL_REMARK { get; set; }
        public long ADDEDBY { get; set; }
        public System.DateTime ADDEDDATE { get; set; }
        public long? UPDATEBY { get; set; }
        public DateTime? UPDATEDATE { get; set; }
        public DateTime? APP_DATE { get; set; }
        public string ACTIONFOR { get; set; }
        public DateTime? HOLD_DATE { get; set; }
        public string HOLD_REMARKS { get; set; }
        public long? HOLD_BY { get; set; }
        public string APP_TYPEINFO { get; set; }
        public short APP_SEQ_HIS { get; set; }
       
    }
}
