//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DGIT_ACRHEADER
    {
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DGIT_ACRHEADER()
        {
            this.DGIT_ACRAPPAUTHSEQ = new HashSet<DGIT_ACRAPPAUTHSEQ>();
            this.DGIT_ACRAPPHISTORY = new HashSet<DGIT_ACRAPPHISTORY>();
            this.DGIT_ACRDETAIL = new HashSet<DGIT_ACRDETAIL>();
        }
        [Key]
        public long ACRHEADERID { get; set; }
        public string ACRNO { get; set; }
        public decimal? AMOUNT { get; set; }
        public string REMARK { get; set; }
        public short STATUS { get; set; }
        public short PROCESS_STATUS { get; set; }
        public System.DateTime DATEADDED { get; set; }
        public long ADDEDBY { get; set; }
        public DateTime? UPDATEDATE { get; set; }
        public long? UPDATEDBY { get; set; }
        public string ACR_DESC { get; set; }
        public string PO_NUMBER { get; set; }
        public string SUPPLIER_CODE { get; set; }
        public string SUPPLIER_NAME { get; set; }
        public short?  DOC_STATUS { get; set; }
        public DateTime? DOC_REV_DATE { get; set; }
        public long? DOC_REV_BY { get; set; }
        public short PA_GENERATED { get; set; }
        public long? SYSITEID { get; set; }
    
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DGIT_ACRAPPAUTHSEQ> DGIT_ACRAPPAUTHSEQ { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DGIT_ACRAPPHISTORY> DGIT_ACRAPPHISTORY { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DGIT_ACRDETAIL> DGIT_ACRDETAIL { get; set; }
    }
}
