//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DGIT_ICASSETREQ_SCHEDULE
    {
        [Key]
        public long ICASSETREQSCHID { get; set; }
        public long ICASSETREQID { get; set; }
        public string TARGET { get; set; }
        public System.DateTime SCHEDULE { get; set; }
        public long ADDEDBY { get; set; }
        public System.DateTime DATEADDED { get; set; }
        public long? MODIFIEDBY { get; set; }
        public System.DateTime? MODIFIEDDATE { get; set; }
    
        //public virtual DGIT_ICASSETREQHEADER DGIT_ICASSETREQHEADER { get; set; }
    }
}
