//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DGIT_IOMHEADER
    {
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        //public DGIT_IOMHEADER()
        //{
        //    this.DGIT_IOMDETAIL = new HashSet<DGIT_IOMDETAIL>();
        //}
        [Key]
        public long IOMHEADERID { get; set; }
        public string IOM_DESC { get; set; }
        public short STATUS { get; set; }
        public short PROCESS_STATUS { get; set; }
        public System.DateTime DATEADDED { get; set; }
        public long ADDEDBY { get; set; }
        public Nullable<System.DateTime> UPDATEDATE { get; set; }
        public Nullable<long> UPDATEDBY { get; set; }
        public short APP_TYPE { get; set; }
        public Nullable<long> IOMCATID { get; set; }

        //Added by TTL on 18th July 2025 against SR101913 > CR6738 - Start
        public string ARIBARFPID { get; set; }
        //Added by TTL on 18th July 2025 against SR101913 > CR6738 - End

        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<DGIT_IOMDETAIL> DGIT_IOMDETAIL { get; set; }
    }
}
