//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DGIT_PROPERATIONMAP
    {
        [Key]
        public long PROPMAPID { get; set; }
        public short PRCAT { get; set; }
        public long ADEMPCODE { get; set; }
        public long ADORGLVLID { get; set; }
        public System.DateTime DATEADDED { get; set; }
        public long? ADDEDBY { get; set; }
        public short STATUS { get; set; }
    }
}
