//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DGIT_PRADDAPP_MST
    {
        [Key]
        public long PRADDAPP_MST_ID { get; set; }
        public long ADORGLVLID { get; set; }
        public long APPROVER { get; set; }
        public long? FUNCTIONDESID { get; set; }
        public long? ACTUALDESGID { get; set; }
        public short ISPRINTREQUIRED { get; set; }
        public long ADDEDBY { get; set; }
        public System.DateTime ADDEDDATE { get; set; }
        public long? MODIFIEDBY { get; set; }
        public DateTime? MODIFIEDDATE { get; set; }
        public short STATUS { get; set; }
        public short ISPARALELLAPP { get; set; }
        public long? AMOUNTRANGE_FROM { get; set; }
        public long? AMOUNTRANGE_TO { get; set; }
        public short?  INDENTTYPE { get; set; }
        public short?  ISADDEDINLAST { get; set; }
        public short?  APPSEQ { get; set; }
        public string ACTIONFOR { get; set; }
        public short?  IS_SISPR { get; set; }
        public string APP_TYPEINFO { get; set; }

        public Nullable<long> PLANTID { get; set; }

        //public virtual ADORGLEVEL ADORGLEVEL { get; set; }
    }
}
