//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DGIT_SESMRN_HEADER
    {
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        //public DGIT_SESMRN_HEADER()
        //{
        //    this.DGIT_SESMRN_DTL = new HashSet<DGIT_SESMRN_DTL>();
        //    this.DGIT_SMAPPHISTORY = new HashSet<DGIT_SMAPPHISTORY>();
        //    this.DGIT_SMAPPAUTH_SEQ = new HashSet<DGIT_SMAPPAUTH_SEQ>();
        //}

        [Key]
        public long SMHEADERID { get; set; }
        public string SES_MRN_NO { get; set; }
        public string PONUMBER { get; set; }
        public decimal AMOUNT { get; set; }
        public string NATUREOFEXPENSE { get; set; }
        public short STATUS { get; set; }
        public short PROCESS_STATUS { get; set; }
        public System.DateTime DATEADDED { get; set; }
        public long ADDEDBY { get; set; }
        public DateTime? UPDATEDATE { get; set; }
        public long? UPDATEDBY { get; set; }
        public short SM_TYPE { get; set; }
        public string INVOICENO { get; set; }
        public DateTime? INVOICEDATE { get; set; }
        public decimal? INVAMOUNT { get; set; }
        public short?  INVSIGTYPE { get; set; }
        public string VENDORCODE { get; set; }
        public short?  DOC_STATUS { get; set; }
        public DateTime? DOC_REV_DATE { get; set; }
        public long? DOC_REV_BY { get; set; }
        public short PA_GENERATED { get; set; }
        public long? SYSITEID { get; set; }
        public short?  IS_IPRELATEDPR { get; set; }
    
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DGIT_SESMRN_DTL> DGIT_SESMRN_DTL { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DGIT_SMAPPHISTORY> DGIT_SMAPPHISTORY { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DGIT_SMAPPAUTH_SEQ> DGIT_SMAPPAUTH_SEQ { get; set; }
    }
}
