//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DGIT_SMIOCGBLOCK
    {
        [Key]
        public long SMIOCGBLOCKID { get; set; }
        public long ADORGLEVELID { get; set; }
        public short STATUS { get; set; }
        public long ADDEDBY { get; set; }
        public System.DateTime DATEADDED { get; set; }
        public long? UPDATEDBY { get; set; }
        public DateTime? UPDATEDDATE { get; set; }
    }
}
