//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DGIT_ACRAPPSKIP
    {
        [Key]
        public long ACRAPPSKIP_ID { get; set; }
        public long ACRID { get; set; }
        public long ADEMPCODE { get; set; }
        public short STATUS { get; set; }
        public string SKIPREMARK { get; set; }
        public long ADDEDBY { get; set; }
        public System.DateTime ADDEDDATE { get; set; }
    }
}
