//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class DGIT_TR_OP_LIST
    {
        public decimal ID { get; set; }
        public Nullable<long> OPID { get; set; }
        public string ADDEDBY { get; set; }
        public Nullable<System.DateTime> ADDEDDATE { get; set; }
        public Nullable<decimal> COUNT { get; set; }
        public Nullable<decimal> STATUS { get; set; }
    }
}
