//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DGIT_PRHEADER
    {
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        //public DGIT_PRHEADER()
        //{
        //    this.DGIT_PRDETAIL = new HashSet<DGIT_PRDETAIL>();
        //    this.DGIT_PRBUYER_MAP = new HashSet<DGIT_PRBUYER_MAP>();
        //}
        [Key]
        public long PRHEADERID { get; set; }
        public string INDENT_NO { get; set; }
        public System.DateTime INDENT_DATE { get; set; }
        public decimal INDENT_AMOUNT { get; set; }
        public string ITEM_DETAIL { get; set; }
        public string REMARK { get; set; }
        public short STATUS { get; set; }
        public short PROCESS_STATUS { get; set; }
        public System.DateTime DATEADDED { get; set; }
        public long ADDEDBY { get; set; }
        public DateTime? UPDATEDATE { get; set; }
        public long? UPDATEDBY { get; set; }
        public short PRTYE { get; set; }
        public short?  PRCAT { get; set; }
        public short?  IS_SISPR { get; set; }
        public short?  IS_NONSISPR { get; set; }
        public DateTime? CATUPDATEDATE { get; set; }
        public long? CATUPDATEDBY { get; set; }
        public short?  IS_IPRELATEDPR { get; set; }
        public string ARIBARFPID { get; set; }
        public short?  ARIBASTATUS { get; set; }
        public long? ARIBABUYER { get; set; }
        public string ARIBASRNO { get; set; }
        public Nullable<long> RELEASEPLANTID { get; set; }
        public Nullable<long> PRCATEGORY { get; set; }

        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<DGIT_PRDETAIL> DGIT_PRDETAIL { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<DGIT_PRBUYER_MAP> DGIT_PRBUYER_MAP { get; set; }
    }
}
