//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DGIT_ICREQHEADER
    {
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        //public DGIT_ICREQHEADER()
        //{
        //    this.DGIT_ICAPPAUTHSEQ = new HashSet<DGIT_ICAPPAUTHSEQ>();
        //    this.DGIT_ICAPPHISTORY = new HashSet<DGIT_ICAPPHISTORY>();
        //    this.DGIT_ICDOCDETAIL = new HashSet<DGIT_ICDOCDETAIL>();
        //    this.DGIT_ICREQ_SCHEDULE = new HashSet<DGIT_ICREQ_SCHEDULE>();
        //}
        [Key]
        public long ICREQID { get; set; }
        public string ICTITLE { get; set; }
        public string DEPARTMENT { get; set; }
        public string ICBACKGROUND { get; set; }
        public string ICA00 { get; set; }
        public string ICPURPOSE { get; set; }
        public string TARGET { get; set; }
        public string REQUIREMENT { get; set; }
        public string CONTENTOFEXE { get; set; }
        public long? PAYBACK_PERIOD { get; set; }
        public decimal? COSTSAVING { get; set; }
        public decimal? BASIC_BUDGET { get; set; }
        public decimal? BASIC_PROPOSED { get; set; }
        public decimal? TAX_BUDGET { get; set; }
        public decimal? TAX_PROPOSED { get; set; }
        public short? IMPORT_LOCAL { get; set; }
        public short? TAX_CREDIT_AVAIL { get; set; }
        public long ADDEDBY { get; set; }
        public System.DateTime DATEADDED { get; set; }
        public long? MODIFIEDBY { get; set; }
        public Nullable<System.DateTime> MODIFIEDDATE { get; set; }
        public short PROCESSSTATUS { get; set; }
        public short STATUS { get; set; }
        public string REMARK { get; set; }
        public string INVEST_EFFECT { get; set; }
        public short? ISIBMREQUIRED { get; set; }
        public long? ICCONFIGID { get; set; }
        public decimal? GAVAMT { get; set; }
        public decimal? NAVAMT { get; set; }
        public decimal? SRVAMT { get; set; }
        public decimal? NPLAMT { get; set; }
        public string AUCCODE { get; set; }
        public long? AUCCODEUPDBY { get; set; }
        public System.DateTime? AUCCODEUPDDATE { get; set; }
        public string AUCCODEREMARK { get; set; }
    
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<DGIT_ICAPPAUTHSEQ> DGIT_ICAPPAUTHSEQ { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<DGIT_ICAPPHISTORY> DGIT_ICAPPHISTORY { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<DGIT_ICDOCDETAIL> DGIT_ICDOCDETAIL { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<DGIT_ICREQ_SCHEDULE> DGIT_ICREQ_SCHEDULE { get; set; }
    }
}
