//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class EMP_LOGINDETAIL
    {
        [Key]
        public long EMP_LOGINDETAILID { get; set; }
        public long ECODE { get; set; }
        public long APPSYSTEMID { get; set; }
        public string LOGINIDCREATED { get; set; }
        public System.DateTime DATEADDED { get; set; }
        public long ADDEDBY { get; set; }
        public long? MODIFIEDBY { get; set; }
        public System.DateTime? MODIFIEDDATE { get; set; }
        public short STATUS { get; set; }
    
        //public virtual SYAPPLICATION SYAPPLICATION { get; set; }
    }
}
