<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="NSP_NEXTVAL_MODEL.cs" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="ePortalDBModel\" />
    <Folder Include="eportalDGIT\" />
    <Folder Include="ICProcessDBModel\" />
    <Folder Include="LCModel\" />
  </ItemGroup>

</Project>
