//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class FD_BOKKING_SLOT_MAP
    {
        [Key]
        public long ID { get; set; }
        public System.DateTime ALLOW_DATE { get; set; }
        public long SITE_ID { get; set; }
        public short STATUS { get; set; }
        public System.DateTime CREATED_ON { get; set; }
        public long CREATED_BY { get; set; }
        public System.DateTime? UPDATED_ON { get; set; }
        public long? UPDATED_BY { get; set; }
        public System.DateTime STARTDATE { get; set; }
        public System.DateTime ENDDATE { get; set; }
        public System.DateTime CANCELENDTIME { get; set; }
    }
}
