//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class FD_VISITBOOKING_DTL
    {
        [Key]
        public long BC_FAMILYMEALBOOKING_DTLID { get; set; }
        public long BC_FAMILY_BOOKINGID { get; set; }
        public string MEMBER_NAME { get; set; }
        public string RELATION_TYPE { get; set; }
        public long ADDEDBY { get; set; }
        public System.DateTime ADDEDDATE { get; set; }
        public long? LSTMODIFIEDBY { get; set; }
        public System.DateTime? LSTMODDATE { get; set; }
        public short STATUS { get; set; }
        public long? MEALS_AVAILABILITY_ID { get; set; }
        public long? MEALTYPEID { get; set; }
    }
}
