//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class FD_VISITBOOKING_TRN
    {
        [Key]
        public long BC_FAMILY_BOOKINGID { get; set; }
        public System.DateTime MEAL_BOOKED_DATE { get; set; }
        public short MEAL_STATUS { get; set; }
        public long ADDEDBY { get; set; }
        public System.DateTime ADDEDDATE { get; set; }
        public long? LSTMODIFIEDBY { get; set; }
        public System.DateTime? LSTMODDATE { get; set; }
        public long SLOTID { get; set; }
        public string TOKEN_CODE { get; set; }
        public short? ADMIN_STAUS { get; set; }
        public System.DateTime? ADMIN_DATE { get; set; }
        public long? ADMIN_ECODE { get; set; }
        public long? TRANSPORT_TYPE { get; set; }
        public long? VEHICLE_TYPE { get; set; }
        public Nullable<long> WHATSAPPNUMBER { get; set; } // #Upgrade Aumento added
        public string PERSONALEMAIL { get; set; } // #Upgrade Aumento added
    }
}
