//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class FINTBS_COST_CENTER_MST
    {
        [Key]
        public int COSTCENTERID { get; set; }
        public Nullable<int> STATEID { get; set; }
        public Nullable<int> OPERATIONID { get; set; }
        public string COSTCENTER { get; set; }
        public string PROFITCENTER { get; set; }
        public Nullable<System.DateTime> EFFECTIVEFORM { get; set; }
        public Nullable<System.DateTime> EFFECTIVETO { get; set; }
        public Nullable<int> STATUS { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public Nullable<int> CREATED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public Nullable<int> MODIFIED_BY { get; set; }
        public Nullable<int> OPERATIONID1 { get; set; }
    }
}
