//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class FINVENDORMASTERMST
    {
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        
        [Key]
        public string VENDORCODE { get; set; }
        public string VENDORACCOUNTGP { get; set; }
        public string NAME1 { get; set; }
        public string NAME2 { get; set; }
        public string NAME3 { get; set; }
        public string STREET1 { get; set; }
        public string STREET2 { get; set; }
        public string STREET3 { get; set; }
        public string STREET4 { get; set; }
        public string CITY { get; set; }
        public string REGION { get; set; }
        public string POSTALCODE { get; set; }
        public string COUNTRYID { get; set; }
        public string MOBILENO { get; set; }
        public string TELEPHONENO { get; set; }
        public string EMAIL1 { get; set; }
        public string EMAIL2 { get; set; }
        public string EMAIL3 { get; set; }
        public string MSMESTATUSINFO { get; set; }
        public string MSMECATEGORY { get; set; }
        public string MSMECERTIFICATENO { get; set; }
        public string BANKACCOUNTNO { get; set; }
        public string BANKNAME { get; set; }
        public string BANKADDRESS { get; set; }
        public string BANKCITY { get; set; }
        public string BANKREGIONID { get; set; }
        public string BANKCOUNTRYID { get; set; }
        public string BRANCHNAME { get; set; }
        public string TYPEOFACCOUNTID { get; set; }
        public string IFSCCODE { get; set; }
        public string BANKCATEGORY { get; set; }
        public string SCHEMAGROUP { get; set; }
        public string ORDERCURRENCY { get; set; }
        public string PANNO { get; set; }
        public string CSTREGNO { get; set; }
        public string LSTNO { get; set; }
        public string SERVICEREGNNO { get; set; }
        public string ECCNO { get; set; }
        public string EXCISEREGNNO { get; set; }
        public string EXCISERANGE { get; set; }
        public string EXCISEDIVISION { get; set; }
        public string COMMISTIONERATE { get; set; }
        public string SERVICEAGENTGROUP { get; set; }
        public short?  STATUS { get; set; }
        public short?  SUBMITTYPE { get; set; }
        public long? ADDEDBY { get; set; }
        public DateTime? ADDEDDATE { get; set; }
        public long? MODIFIEDBY { get; set; }
        public DateTime? MODIFIEDDATE { get; set; }
        public string GSTIN { get; set; }
        public string GSTCLASSIFICATION { get; set; }
    
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<DGIT_POHEADER> DGIT_POHEADER { get; set; }
    }
}
