//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class HMSIHOLIDAYS
    {
        [Key]
        public long HMSIHOLIDAYSID { get; set; }
        public System.DateTime MONTHDATEYEAR { get; set; }
        public string HOLIDAYDESCRIPTION { get; set; }
        public long SYSITEID { get; set; }
        public System.DateTime DATEADDED { get; set; }
        public DateTime? DATELSTMOD { get; set; }
        public long ADDEDBY { get; set; }
        public long? MODIFIEDBY { get; set; }
        public short ACTIVE { get; set; }
        public short?  ISHALFDAY { get; set; }
    }
}
