//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class HRSECURITYSURVEY
    {
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        //public HRSECURITYSURVEY()
        //{
        //    this.HRSECURITYSURVEYCOMMENT = new HashSet<HRSECURITYSURVEYCOMMENT>();
        //}

        [Key]
        public long HRSECURITYSURVEYID { get; set; }
        public string HRSURVEYDESC { get; set; }
        public string HRSURVEYDESCHINDI { get; set; }
        public string HRSURVEYDESCKANNADA { get; set; }
        public string HRSURVEYDESCGUJARATI { get; set; }
        public string HRSURVEYDESCJAPANESE { get; set; }
        public Nullable<System.DateTime> HRSURVEYSTARTDATE { get; set; }
        public Nullable<System.DateTime> HRSURVEYENDDATE { get; set; }
        public Nullable<System.DateTime> DATEADDED { get; set; }
        public Nullable<long> ADDEDBY { get; set; }
        public string HRSURVEYTITAL { get; set; }
        public Nullable<long> ACTIVE { get; set; }
        public Nullable<long> RETEST { get; set; }
        public Nullable<long> SURVEYRESULTMAIL { get; set; }
        public Nullable<long> FEEDBACKSTATUS { get; set; }
        public Nullable<long> PASSINGPERCENTAGE { get; set; }
        public Nullable<long> SURVEYID { get; set; }
        public string FUNCTIONAL_DESIGNATION { get; set; }
        public string LOCATION { get; set; }
        public string OPERATION { get; set; }
        public string DIVISION { get; set; }
        public string HRSURVEYHEADER { get; set; }
        public string HRSURVEYHEADERHINDI { get; set; }
        public string HRSURVEYHEADERKANNADA { get; set; }
        public string HRSURVEYHEADERGUJARATI { get; set; }
        public string HRSURVEYHEADERJAPANESE { get; set; }
        public Nullable<long> ISREMARKSMANDATORY { get; set; }
        public Nullable<long> SURVEYTYPE { get; set; }
        public Nullable<long> LOGINCNT { get; set; }
        public Nullable<long> ISHCGSURVEY { get; set; }
        public string HRSURVEYMODULETYPE { get; set; }

        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<HRSECURITYSURVEYCOMMENT> HRSECURITYSURVEYCOMMENT { get; set; }
    }
}
