//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class HRSECURITYANSLIST
    {
        [Key]
        public long HRSECURITYANSLISTID { get; set; }
        public long HRSECURITYQUSLISTID { get; set; }
        public string ANSDESCRIPTION { get; set; }
        public string ANSDESCRIPTIONHINDI { get; set; }
        public string ANSDESCRIPTIONKANNADA { get; set; }
        public string ANSDESCRIPTIONGUJARATI { get; set; }
        public string ANSDESCRIPTIONJAPANESE { get; set; }
        public Nullable<short> ACTIVE { get; set; }
        public Nullable<short> ISCORRECT { get; set; }
        public Nullable<System.DateTime> DATEADDED { get; set; }
        public Nullable<long> ADDEDBY { get; set; }
        public Nullable<System.DateTime> DATELSTMOD { get; set; }
        public Nullable<long> MODBY { get; set; }
        public long ISFAMILYDEC_REQ { get; set; }

        //public virtual HRSECURITYQUSLIST HRSECURITYQUSLIST { get; set; }
    }
}
