//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class HRSECURITYQUIZ
    {
        [Key]
        public long HRSECURITYQUIZID { get; set; }
        public Nullable<long> ADEMPCODE { get; set; }
        public Nullable<long> HRSECURITYQUSLISTID { get; set; }
        public Nullable<long> HRSECURITYANSLISTID { get; set; }
        public Nullable<System.DateTime> DATEADDED { get; set; }
        public string REMARKS { get; set; }
    
        //public virtual ADLOGINUSER ADLOGINUSER { get; set; }
    }
}
