//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class HRSECURITYQUSLIST
    {
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        //public HRSECURITYQUSLIST()
        //{
        //    this.HRSECURITYANSLIST = new HashSet<HRSECURITYANSLIST>();
        //}

        [Key]
        public long HRSECURITYQUSLISTID { get; set; }
        public Nullable<short> ACTIVE { get; set; }
        public string QUSDESCRIPTION { get; set; }
        public string QUSDESCRIPTIONHINDI { get; set; }
        public string QUSDESCRIPTIONKANNADA { get; set; }
        public string QUSDESCRIPTIONGUJARATI { get; set; }
        public string QUSDESCRIPTIONJAPANESE { get; set; }
        public Nullable<System.DateTime> DATEADDED { get; set; }
        public Nullable<decimal> ADDEDBY { get; set; }
        public Nullable<System.DateTime> DATELSTMOD { get; set; }
        public Nullable<decimal> MODBY { get; set; }
        public Nullable<long> HRSECURITYSURVEYID { get; set; }
        public string INITIALDESCRIP { get; set; }
        public string DESINATION { get; set; }
        public Nullable<short> OPTIONTYPE { get; set; }
        public Nullable<long> SUBQUESTIONPARENTID { get; set; }
        public Nullable<short> ISSUBQUESTION { get; set; }
        public string TRIGGEROPTIONIDS { get; set; }

        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<HRSECURITYANSLIST> HRSECURITYANSLIST { get; set; }
    }
}
