//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class HRSECURITYSURVEYSKIPCOUNT
    {
        [Key]
        public long HRSECURITYSURVEYSKIPID { get; set; }
        public Nullable<long> HRSECURITYSURVEYID { get; set; }
        public Nullable<long> ADEMPCODE { get; set; }
        public Nullable<System.DateTime> DATEADDED { get; set; }
        public Nullable<short> SKIPCOUNT { get; set; }
    }
}
