//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("ADORGLEVEL")]
    public partial class ICADORGLEVEL
    {
        [Key]
        public long ADORGLEVELID { get; set; }
        public string LEVELDESCRIP { get; set; }
        public long? PARENTLEVELID { get; set; }
        public long ADORGLEVELTYPEID { get; set; }
        public short?  SYKIID { get; set; }
        public short?  ACTIVE { get; set; }
        public DateTime? DATEADDED { get; set; }
        public long? ADDEDBY { get; set; }
        public DateTime? LSTMODDATE { get; set; }
        public long? LSTMODBY { get; set; }
        public decimal? ADORGLEVELSAPID_old { get; set; }
        public string COSTCENTRE { get; set; }
        public decimal? ADORGLEVELSAPID { get; set; }
        public long? PARENTLEVELID1 { get; set; }
    }
}
