//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ICIBM_TAXCREDITDASHBOARD
    {
        [Key]
        public long ICREQID { get; set; }
        public string ICTITLE { get; set; }
        public string DEPARTMENT { get; set; }
        public long ADEMPCODE { get; set; }
        public string ENAME { get; set; }
        public string OPERATION { get; set; }
        public System.DateTime LASTAPPROVAL { get; set; }
        public short PROCESSSTATUS { get; set; }
        public string REQUESTTYPE { get; set; }
        public string ICTYPE { get; set; }
        public decimal? STATUS { get; set; }
        public long SYPLANTID { get; set; }
    }
}
