//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class IMPACTTYPE
    {
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        //public IMPACTTYPE()
        //{
        //    this.RISKASSESSMENT = new HashSet<RISKASSESSMENT>();
        //    this.RISK_IMPACT_MASTER = new HashSet<RISK_IMPACT_MASTER>();
        //}

        [Key]
        public decimal IMAPECTTYPEID { get; set; }

        [Column("IMPACTTYPE")]
        public string? IMPACTTYPE1 { get; set; }
        public Nullable<decimal> STATUS { get; set; }
        public Nullable<decimal> CREATEDBY { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }

        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<RISKASSESSMENT> RISKASSESSMENT { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<RISK_IMPACT_MASTER> RISK_IMPACT_MASTER { get; set; }
    }
}
