//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVFORCAST
    {
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        //public INVFORCAST()
        //{
        //    this.A00INVFORCAST = new HashSet<A00INVFORCAST>();
        //}
    
        public long INVFORCASTID { get; set; }
        public string INCFORCASTDETAIL { get; set; }
        public short ACTIVE { get; set; }
        public long ADDEDBY { get; set; }
        public System.DateTime DATEADDEDID { get; set; }
        public Nullable<long> LSTMODBYID { get; set; }
        public Nullable<System.DateTime> LASTMODDATE { get; set; }
    
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public ICollection<A00INVFORCAST> A00INVFORCAST { get; set; }
    }
}
