//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ISMSHDRDTL
    {
        [Key]
        public long ISMSMAPPINGID { get; set; }
        public Nullable<long> ISMS_MST_SRNO { get; set; }
        public Nullable<long> STATUS { get; set; }
        public Nullable<long> APPAUTH_ECODE { get; set; }
        public Nullable<System.DateTime> APPAUTH_DATE { get; set; }
        public string APPAUTH_REMARKS { get; set; }
        public Nullable<long> CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public Nullable<long> MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public Nullable<long> APP_LEVEL { get; set; }
    }
}
