//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ISMSHDRMST
    {
        [Key]
        public long SRNO { get; set; }
        public byte[] ISMS_BLOB { get; set; }
        public string ISMS_CONTENTTYPE { get; set; }
        public string ISMS_UPLOAD { get; set; }
        public long? APP_AUTH1 { get; set; }
        public long? APP_AUTH2 { get; set; }
        public long? STATUS { get; set; }
        public System.DateTime? CREATED_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime? MODIFIED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
    }
}
