//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class KAIZEN_DEPT_COMMITTEE_MASTER
    {
        public long DEPT_COMMITTEE_ID { get; set; }
        public string COMMITTEE_NAME { get; set; }
        public Nullable<short> ACTIVE { get; set; }
        public Nullable<long> ADDEDBY { get; set; }
        public Nullable<System.DateTime> ADDEDDATE { get; set; }
        public Nullable<long> MODIFIEDBY { get; set; }
        public Nullable<System.DateTime> MODIFIEDDATE { get; set; }
        public string OPERATION_ID { get; set; }
        public Nullable<long> USER_ONE { get; set; }
        public Nullable<long> USER_TWO { get; set; }
        public Nullable<long> USER_THREE { get; set; }
        public Nullable<long> USER_FOUR { get; set; }
    }
}
