//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class KAIZENAPPAUTH
    {
        public long KAIZENAUTH_ID { get; set; }
        public Nullable<long> ADEMPCODE { get; set; }
        public Nullable<long> SITEID { get; set; }
        public Nullable<long> ADDEDBY { get; set; }
        public Nullable<System.DateTime> DATEADDED { get; set; }
        public Nullable<long> MODIFIEDBY { get; set; }
        public Nullable<System.DateTime> MODIFIEDDATE { get; set; }
        public Nullable<long> ACTIVE { get; set; }
    }
}
