//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class KAIZEN_FORM_STATUS
    {
        public string KAIZENID { get; set; }
        public string GRADE { get; set; }
        public Nullable<long> ADDEDBY { get; set; }
        public Nullable<System.DateTime> ADDEDDATE { get; set; }
        public Nullable<System.DateTime> UPDATEDATE { get; set; }
        public Nullable<long> STATUS { get; set; }
        public Nullable<long> REQSTATUS { get; set; }
        public Nullable<long> UPDATEDBY { get; set; }
        public string KAIZEN_MONTH_ID { get; set; }
        public long GRADE_ID { get; set; }
        public Nullable<long> TOTALSCORE { get; set; }
        public Nullable<long> OP_ID { get; set; }
        public Nullable<System.DateTime> DIV_COMMITTEE_SUBMIT_DATE { get; set; }
        public Nullable<System.DateTime> DEPT_COMMITTEE_SUBMIT_DATE { get; set; }
        public string SENDBACK_REMARK { get; set; }
        public Nullable<long> KAIZEN_DIV_RANK { get; set; }
        public Nullable<long> SYKI { get; set; }
        public Nullable<long> KAIZEN_DIV_FINAL_RANK { get; set; }
    }
}
