//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class KAIZEN_DIV_COMMITTEE_USERS
    {
        [Key]
        public long DIV_COMMITTEE_USER_ID { get; set; }
        public long? DIV_COMMITTEE_ID { get; set; }
        public string KAIZENID { get; set; }
        public long? ADEMPCODE { get; set; }
        public long? CREATIVITY { get; set; }
        public long? APPLICABILITY { get; set; }
        public long? EFFORT { get; set; }
        public long? SAFETY { get; set; }
        public long? ENIVRONMENT { get; set; }
        public long? CONVENIENCE { get; set; }
        public long? QUALITY { get; set; }
        public long? COSTSAVING { get; set; }
        public long? TOTALSCORE { get; set; }
        public long? ADDEDBY { get; set; }
        public DateTime? ADDEDDATE { get; set; }
        public long? MODIFIEDBY { get; set; }
        public DateTime? MODIFIEDDATE { get; set; }
        public short? ISCOSTVERIFIED { get; set; }
        public short? STATUS { get; set; }
        public short? DUPLICATE_IDEA { get; set; }
    }
}
