//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class LC_DETAIL_TEMP
    {
        [Key]
        public long SRNO { get; set; }
        public Nullable<long> ASOFFODID { get; set; }
        public Nullable<long> TEMPID { get; set; }
        public Nullable<long> EMPCODE { get; set; }
        public string EMPNAME { get; set; }
        public Nullable<System.DateTime> DATEOFEXPENDITURE { get; set; }
        public string PURPOSE { get; set; }
        public string FROMCITY { get; set; }
        public string TOCITY { get; set; }
        public Nullable<long> FROMCITYID { get; set; }
        public Nullable<long> TOCITYID { get; set; }
        public string TIMEIN { get; set; }
        public string TIMEOUT { get; set; }
        public Nullable<decimal> NOOFHOURS { get; set; }
        public string MODEOFTRAVEL { get; set; }
        public Nullable<decimal> KMCOVERED { get; set; }
        public Nullable<decimal> RATEPERKM { get; set; }
        public Nullable<decimal> TRAVELREIMBURSEMENT { get; set; }
        public Nullable<decimal> REFRESHMENTMEALALLOWANCE { get; set; }
        public Nullable<decimal> TOLLTAXMISCAMOUNT { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
        public string DT { get; set; }
        public Nullable<long> ADDEDBY { get; set; }
        public Nullable<System.DateTime> ADDEDON { get; set; }
        public Nullable<long> UPDATEDBY { get; set; }
        public Nullable<System.DateTime> UPDATEDON { get; set; }
        public Nullable<long> ISSUBMITTED { get; set; }
        public Nullable<decimal> FUEL_REIMBURSMENT { get; set; }
        public string MODEOFTRAVEL_OTHER { get; set; }
        public string FROMCITY_OTHER { get; set; }
        public string TOCITY_OTHER { get; set; }
        public string MEAL_REFRE_ALLW_CLAIM { get; set; }
        public string FUEL_ALLW_CLAIM { get; set; }
        public string STATUS { get; set; }
        public string DINNER_ALLW_CLAIM { get; set; }
        public string LUNCH_ALLW_CLAIM { get; set; }
        public Nullable<decimal> DINNER_ALLW_AMOUNT { get; set; }
        public Nullable<decimal> LUNCH_ALLW_AMOUNT { get; set; }
        public Nullable<decimal> TOURSTARTFROMHOMEKM { get; set; }
    }
}
