//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class LC_EXCEPTION_C_TABLE_LOG
    {
        [Key]
        public long SRNO { get; set; }
        public Nullable<long> EMPCODE { get; set; }
        public Nullable<decimal> FUEL_REIMBUR_PER_LTR { get; set; }
        public Nullable<System.DateTime> FROMDATE { get; set; }
        public Nullable<System.DateTime> TODATE { get; set; }
        public Nullable<long> ADDEDBY { get; set; }
        public Nullable<System.DateTime> ADDEDON { get; set; }
        public Nullable<long> UPDATEDBY { get; set; }
        public Nullable<System.DateTime> UPDATEDON { get; set; }
        public string EMPNAME { get; set; }
        public string REMARKS { get; set; }
        public Nullable<short> ACTIVE { get; set; }
        public string LOGMODE { get; set; }
        public Nullable<int> MAINTBLSRNO { get; set; }
    }
}
