//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class LC_HEAD
    {
        [Key]
        public long SRNO { get; set; }
        public Nullable<long> EMPCODE { get; set; }
        public Nullable<long> LCTRANNO { get; set; }
        public Nullable<System.DateTime> LCTRANDATE { get; set; }
        public string PURPOSE { get; set; }
        public Nullable<decimal> TOTAL_AMOUNT { get; set; }
        public string TOTAL_AMT_IN_WORD { get; set; }
        public Nullable<long> APPROVER_USER { get; set; }
        public string APPROVER_STATUS { get; set; }
        public Nullable<System.DateTime> APPROVER_DATETIME { get; set; }
        public Nullable<long> ADMIN_USER { get; set; }
        public string ADMIN_STATUS { get; set; }
        public Nullable<System.DateTime> ADMIN_DATETIME { get; set; }
        public Nullable<long> FINANCE_USER { get; set; }
        public string FINANCE_STATUS { get; set; }
        public Nullable<System.DateTime> FINANCE_DATETIME { get; set; }
        public Nullable<decimal> FUAL { get; set; }
        public Nullable<decimal> REQUIRED_AMOUNT { get; set; }
        public Nullable<long> ADDEDBY { get; set; }
        public Nullable<System.DateTime> ADDEDON { get; set; }
        public Nullable<long> UPDATEDBY { get; set; }
        public Nullable<System.DateTime> UPDATEDON { get; set; }
        public Nullable<decimal> TOTAL_NOOFHOURS { get; set; }
        public Nullable<decimal> TOTAL_KMCOVERED { get; set; }
        public string DESIGNATION { get; set; }
        public string EMPNAME { get; set; }
        public string APPROVER_REMARKS { get; set; }
        public string ADMIN_REMARKS { get; set; }
        public string FINANCE_REMARKS { get; set; }
        public Nullable<decimal> APPROVED_FUEL { get; set; }
        public Nullable<long> RECOMM_USER { get; set; }
        public string RECOMM_STATUS { get; set; }
        public Nullable<System.DateTime> RECOMM_DATETIME { get; set; }
        public Nullable<System.DateTime> POSTINGDATE { get; set; }
        public string FINAL_STATUS { get; set; }
        public string RECOMM_REMARKS { get; set; }
        public Nullable<decimal> TOTAL_MEAL_AMOUNT { get; set; }
        public Nullable<decimal> TOTAL_CONV_AMOUNT { get; set; }
        public string PDF_NAME { get; set; }
        public string SAP_DOC_NO { get; set; }
        public Nullable<long> PPPLANT { get; set; }
        // START :: SR107643 :: LC ENHANCEMENT ::  AUMENTO
        public Nullable<long> ADMINFUEL_DH_USER { get; set; }
        public string ADMINFUEL_DH_STATUS { get; set; }
        public string ADMINFUEL_DH_REMARKS { get; set; }
        public Nullable<System.DateTime> ADMINFUEL_DH_DATETIME { get; set; }
        public Nullable<long> ADMINFUEL_OH_USER { get; set; }
        public string ADMINFUEL_OH_STATUS { get; set; }
        public string ADMINFUEL_OH_REMARKS { get; set; }
        public Nullable<System.DateTime> ADMINFUEL_OH_DATETIME { get; set; }
        public string ADMINFUEL_DOC { get; set; }
        public string ADMIN_APPROVAL_TYPE { get; set; }
        // END :: SR107643 :: LC ENHANCEMENT ::  AUMENTO
    }
}
