//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class LC_ROLEMASTER
    {
        [Key]
        public int SRNO { get; set; }
        public Nullable<int> PLANTID { get; set; }
        public string ROLE { get; set; }
        public Nullable<int> EMPCODE { get; set; }
        public Nullable<System.DateTime> ADDEDON { get; set; }
        public Nullable<int> ADDEDBY { get; set; }
        public Nullable<System.DateTime> UPDATEDON { get; set; }
        public Nullable<int> UPDATEDBY { get; set; }
    }
}
