//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class LC_REIMBURSEMENT_B_TABLE
    {
        [Key]
        public long SRNO { get; set; }
        public string DESIGNATION { get; set; }
        public string VEHICLE_ENTITLEMENT { get; set; }
        public Nullable<decimal> FUEL_REIMBUR_PER_LTR { get; set; }
        public Nullable<long> REFRESH_ALLOW_PER_DAY { get; set; }
        public Nullable<long> MEAL_ALLOWANCE { get; set; }
        public Nullable<System.DateTime> FROMDATE { get; set; }
        public Nullable<System.DateTime> TODATE { get; set; }
        public Nullable<long> ADDEDBY { get; set; }
        public Nullable<System.DateTime> ADDEDON { get; set; }
        public Nullable<long> UPDATEDBY { get; set; }
        public Nullable<System.DateTime> UPDATEDON { get; set; }
        public Nullable<long> DESIGNATIONID { get; set; }
        public Nullable<short> ACTIVE { get; set; } // SR107643 :: LC ENHANCEMENT ::  AUMENTO
    }
}
