//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class LC_ZTABLE_LOG
    {
        [Key]
        public long SRNO { get; set; }
        public string STATE { get; set; }
        public Nullable<decimal> FOURWHEELER_RATE { get; set; }
        public Nullable<decimal> TWOWHEELER_RATE { get; set; }
        public Nullable<System.DateTime> FROMDATE { get; set; }
        public Nullable<System.DateTime> TODATE { get; set; }
        public Nullable<long> ADDEDBY { get; set; }
        public Nullable<System.DateTime> ADDEDON { get; set; }
        public Nullable<long> UPDATEDBY { get; set; }
        public Nullable<System.DateTime> UPDATEDON { get; set; }
        public Nullable<long> STATEID { get; set; }
        public Nullable<long> SYSITEID { get; set; }
        public string SYSITENAME { get; set; }
        public string LOGMODE { get; set; }
        public Nullable<short> ACTIVE { get; set; }
        public long MAINTBLSRNO { get; set; }
    }
}
