//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class MEDINS_APPHISTORY
    {
       
        //public MEDINS_APPHISTORY()
        //{
        //    this.MEDINS_DEPENDENTS_DTL_HIS = new HashSet<MEDINS_DEPENDENTS_DTL_HIS>();
        //    this.MEDINS_EMPLOYEE_DTL_HIS = new HashSet<MEDINS_EMPLOYEE_DTL_HIS>();
        //}

        [Key]
        public long APPROVALID { get; set; }
        public long EMP_CODE { get; set; }
        public short APPROVAL_STATUS { get; set; }
        public DateTime? APPROVAL_DATE { get; set; }
        public long? APPROVAL_BY { get; set; }
        public long? MODIFIED_BY { get; set; }
        public DateTime? MODIFIED_DATE { get; set; }
        public short REQUESTTYPE { get; set; }
        public string APPROVAL_REMARK { get; set; }
        public long CREATEDBY { get; set; }
        public DateTime? CREATEDDATE { get; set; }
        
      
        //public  ICollection<MEDINS_DEPENDENTS_DTL_HIS> MEDINS_DEPENDENTS_DTL_HIS { get; set; }
        
        //public  ICollection<MEDINS_EMPLOYEE_DTL_HIS> MEDINS_EMPLOYEE_DTL_HIS { get; set; }
    }
}
