//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class MEDINS_DEPENDENTS_DTL_HIS
    {
        [Key]
        public long MI_DEPENDENTIDHIS { get; set; }
        public long APPROVALID { get; set; }
        public long EMP_CODE { get; set; }
        public string DEP_NAME { get; set; }
        public short? DEP_GENDER { get; set; }
        public DateTime? DEP_DOB { get; set; }
        public byte[] DEP_PHOTO { get; set; }
        public string DEP_PHOTO_CONTYPE { get; set; }
        public string DEP_RELATIONSHIP { get; set; }
        public short STATUS { get; set; }
        public short POLICYTYPE { get; set; }
        public short? DEP_PAIDTYPE { get; set; }
        public short? CHANGETYPE { get; set; }
        public DateTime? CREATED_DATE { get; set; }
        public long? CREATED_BY { get; set; }
        public long? MODIFIED_BY { get; set; }
        public DateTime? MODIFIED_DATE { get; set; }
        public string REMARKS { get; set; }
        public string PREVIOUS_DEP_NAME { get; set; }
        public short? PREVIOUS_DEP_GENDER { get; set; }
        public DateTime? PREVIOUS_DEP_DOB { get; set; }
        public string PREVIOUS_DEP_RELATIONSHIP { get; set; }
    
        
    }
}
