//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class MEDINS_POLICYTYPE_MST
    {

        [Key]    
        public long POLICYTYPE_ID { get; set; }
        public string TYPECODE { get; set; }
        public string TYPE_DESC { get; set; }
        public short STATUS { get; set; }
        public long CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public short ISDEPENDENTREQ { get; set; }
    
        //public  ICollection<MEDINS_TYPEPLANT_MAP> MEDINS_TYPEPLANT_MAP { get; set; }
    }
}
