//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class MEDINS_EMPLOYEE_DTL
    {
        [Key]
        public long MI_EMPDETAILID { get; set; }
        public long EMP_CODE { get; set; }
        public string EMP_NAME { get; set; }
        public short GENDER { get; set; }
        public DateTime DOB { get; set; }
        public short EMP_STATUS { get; set; }
        public DateTime? EMP_MODIFIEDDATE { get; set; }
        public string NOMINEE_NAME { get; set; }
        public DateTime NOMINEE_DOB { get; set; }
        public string NOMINEE_RELATION { get; set; }
        public DateTime? NOMINEE_MODIFIEDDATE { get; set; }
        public short NOMINEE_STATUS { get; set; }
        public short NOMINEE_GENDER { get; set; }
        public string PREVIOUS_EMP_NAME { get; set; }
        public DateTime? PREVIOUS_EMPDOB { get; set; }
        public short? PREVIOUS_NOMINEE_GENDER { get; set; }
        public DateTime? PREVIOUS_NOMINEE_DOB { get; set; }
        public string PREVIOUS_NOMINEE_NAME { get; set; }
        public string PREVIOUS_NOMINEE_RELATION { get; set; }
        public DateTime? DOM { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public long CREATED_BY { get; set; }
        public long? MODIFIEDBY { get; set; }
    
        //public  ADEMPLOYEE ADEMPLOYEE { get; set; }
    }
}
