//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class MEDINS_EMPPOLICYLOC
    {
        [Key]
        public long EMPPOLICYLOC_ID { get; set; }
        public long ADEMPCODE { get; set; }
        public short PLANTID { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public Nullable<long> CREATEDBY { get; set; }
        public Nullable<short> STATUS { get; set; }
    }
}
