//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class MEDINS_DESG_POLICYTYPE_MAP
    {
        [Key]
        public long DESGMAPPINGID { get; set; }
        public long MAPPINGID { get; set; }
        public long DESG_ID { get; set; }
        public short STAUS { get; set; }
        public long CREATEDBY { get; set; }
        public System.DateTime CREATEDDATE { get; set; }
        public long? MODIFIEDBY { get; set; }
        public DateTime? MODIFIEDDATE { get; set; }
    
        //public virtual ADDESIGNATION ADDESIGNATION { get; set; }
        //public virtual MEDINS_TYPEPLANT_MAP MEDINS_TYPEPLANT_MAP { get; set; }
    }
}
