//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class MEDINS_RENEWAL_SETTING
    {
        [Key]
        public long RENEWALID { get; set; }
        public decimal SYKIID { get; set; }
        public short PLANTID { get; set; }
        public System.DateTime PERIOD_FROM { get; set; }
        public System.DateTime PERIOD_TO { get; set; }
        public short STATUS { get; set; }
        public DateTime? CREATEDDATE { get; set; }
        public long? CREATEDBY { get; set; }
        public DateTime? MODIFIEDDATE { get; set; }
        public long? MODIFIEDBY { get; set; }
        public short USERTYPE { get; set; }
    
        //public virtual SYPLANT SYPLANT { get; set; }
        //public virtual SYKI SYKI { get; set; }
    }
}
