//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class MEDINS_TYPEPLANT_MAP
    {

        [Key]
    
        public long MAPPINGID { get; set; }
        public short PLANTID { get; set; }
        public long POLICYTYPE_ID { get; set; }
        public short COMPANYPAID_CNT { get; set; }
        public short ASSOCIATEPAID_CNT { get; set; }
        public short STATUS { get; set; }
        public long CREATEDBY { get; set; }
        public DateTime? CREATEDDATE { get; set; }
        public long? MODIFIEDBY { get; set; }
        public DateTime? MODIFIEDDATE { get; set; }
           
        //public  ICollection<MEDINS_DESG_POLICYTYPE_MAP>? MEDINS_DESG_POLICYTYPE_MAP { get; set; }
        //public virtual MEDINS_POLICYTYPE_MST MEDINS_POLICYTYPE_MST { get; set; }
        //public virtual SYPLANT SYPLANT { get; set; }
    }
}
