//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class NEWSLETTERS
    {
        [Key]
        public long ID { get; set; }
        public string DESCRIPTION { get; set; }
        public string DOCUMENT_NAME { get; set; }
        public string STATUS { get; set; }
        public string ADDED_BY { get; set; }
        public DateTime? ADDED_DATE { get; set; }
        public string UPDATED_BY { get; set; }
        public DateTime? UPDATED_DATE { get; set; }
    }
}
