//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class NSP_APPROVAL_AUTHORITY
    {
        [Key]
        public int APPROVALID { get; set; }
        public Nullable<int> HEADERID { get; set; }
        public Nullable<int> APPSEQ { get; set; }
        public Nullable<int> EMPCODE { get; set; }
        public string APPROVALTYPE { get; set; }
        public string DESIGNATION { get; set; }
        public string EMPHEAD { get; set; }
        public Nullable<short> APPROVAL_STATUS { get; set; }
        public string EMP_NAME { get; set; }
        public string APPREMARK { get; set; }
        public Nullable<int> ADDEDBY { get; set; }
        public Nullable<System.DateTime> ADDEDON { get; set; }
        public Nullable<int> UPDATEDBY { get; set; }
        public Nullable<System.DateTime> UPDATEDON { get; set; }
        public string DEPARTMENT { get; set; }
    }
}
