//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class NSP_PAYMENT_DETAIL
    {
        [Key]
        public int DETAILID { get; set; }
        public Nullable<int> HEADERID { get; set; }
        public Nullable<System.DateTime> INVOICEDATE { get; set; }
        public string INVOICENO { get; set; }
        public string DESCRIPTION { get; set; }
        public string CURRENCY { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public string PO_DOCUMENT { get; set; }
        public string INVOICE_DOCUMENT { get; set; }
        public string APPROVALNOTE_DOCUMENT { get; set; }
        public string OTHER_DOCUMENT { get; set; }
        public Nullable<int> ADDEDBY { get; set; }
        public Nullable<System.DateTime> ADDEDON { get; set; }
        public Nullable<int> UPDATEDBY { get; set; }
        public Nullable<System.DateTime> UPDATEDON { get; set; }
        public Nullable<decimal> APPROVED_AMOUNT { get; set; }
        public Nullable<decimal> BASE_AMOUNT { get; set; }
        public string TAX_TYPE { get; set; }
        public string GST_TYPE { get; set; }
        public Nullable<decimal> CGSTRATE { get; set; }
        public Nullable<decimal> CGSTAMOUNT { get; set; }
        public Nullable<decimal> SGSTRATE { get; set; }
        public Nullable<decimal> SGSTAMOUNT { get; set; }
        public Nullable<decimal> IGSTRATE { get; set; }
        public Nullable<decimal> IGSTAMOUNT { get; set; }
        public Nullable<decimal> TOTAL_GST_AMOUNT { get; set; }
        public Nullable<decimal> TOTAL_AMOUNT { get; set; }
        public string NILGSTREASON { get; set; }
        public string NILTDSREASON { get; set; }
        public Nullable<decimal> TDS_BASE_AMOUNT { get; set; }
        public string TDS { get; set; }
        public Nullable<decimal> TDSRATE { get; set; }
        public Nullable<decimal> TDS_AMOUNT { get; set; }
        public Nullable<decimal> TOTAL_NET_AMOUNT { get; set; }
        public string TDS_TYPE { get; set; }
        public string ISPOSTED { get; set; }
        public string ISREVERSEPOSTED { get; set; }
        public string POSTDOCNO { get; set; }
        public Nullable<System.DateTime> POSTDOCDATE { get; set; }
        public string REVERSEPOSTDOCNO { get; set; }
        public Nullable<System.DateTime> REVERSEPOSTDOCDATE { get; set; }
        public string POSTREVERSEMESSAGE { get; set; }
        public string GSTTAXCODE { get; set; }
        public string COMMISSION { get; set; }
        public Nullable<decimal> COMMISSIONAMOUNT { get; set; }
        public Nullable<decimal> CESSRATE { get; set; }
        public Nullable<decimal> CESSAMOUNT { get; set; }
        public string IS_ESI { get; set; }
        public Nullable<decimal> ESI_RATE { get; set; }
        public Nullable<decimal> ESI_AMOUNT { get; set; }
        public Nullable<decimal> DISCOUNT_AMOUNT { get; set; }
    }
}
