//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class NSP_ROLE_MASTER
    {
        [Key]
        public int SRNO { get; set; }
        public string DEPARTMENT { get; set; }
        public Nullable<long> SYSITEID { get; set; }
        public Nullable<long> ECODE { get; set; }
        public Nullable<long> ADDEDBY { get; set; }
        public Nullable<System.DateTime> ADDEDON { get; set; }
        public Nullable<long> UPDATEDBY { get; set; }
        public Nullable<System.DateTime> UPDATEDON { get; set; }
        public string DESIGNATION { get; set; }
        public Nullable<decimal> SEQUENCE_NO { get; set; }
        public string SYSITTDESCRIPTION { get; set; }
        public string POST { get; set; }
        public string REVERSE { get; set; }
        public Nullable<short> ACTIVE { get; set; }
    }
}
