//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class NSP_FIN_BUSINESS_PROFIT_CENTER_MASTER
    {
        [Key]
        public int SRNO { get; set; }
        public string BUSINESS_CENTER { get; set; }
        public string BUSINESS_PLACE { get; set; }
        public string PROFIT_CENTER { get; set; }
        public Nullable<long> ADDEDBY { get; set; }
        public Nullable<System.DateTime> ADDEDON { get; set; }
        public Nullable<long> UPDATEDBY { get; set; }
        public Nullable<System.DateTime> UPDATEDON { get; set; }
        public Nullable<short> ACTIVE { get; set; }
    }
}
