//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class NSP_PAYMENT_HEADER
    {
        [Key]
        public int HEADERID { get; set; }
        public Nullable<int> REQUESTREFNO { get; set; }
        public Nullable<System.DateTime> REQUESTDATE { get; set; }
        public string CATEGORY { get; set; }
        public string LOCATION { get; set; }
        public string COSTCENTRE { get; set; }
        public string BUDGETED { get; set; }
        public string PURPOSEOFEXPENSES { get; set; }
        public string VENDORCODE { get; set; }
        public string VENDORNAME { get; set; }
        public string VENDORPANNO { get; set; }
        public string VENDORADDRESS { get; set; }
        public string BANKNAME { get; set; }
        public string BANKACCOUNTNO { get; set; }
        public string BANKIFSCCODE { get; set; }
        public string FY_REQUESTTYPE { get; set; }
        public Nullable<decimal> FY_EXRATE { get; set; }
        public Nullable<System.DateTime> FY_EXRATEDATE { get; set; }
        public string FY_TAXATION { get; set; }
        public string FY_GSTTYPE { get; set; }
        public string FY_GST { get; set; }
        public Nullable<decimal> FY_SGSTRATE { get; set; }
        public string FY_TDS { get; set; }
        public Nullable<decimal> FY_TDSRATE { get; set; }
        public string FY_TDSREASON { get; set; }
        public Nullable<int> ADDEDBY { get; set; }
        public Nullable<System.DateTime> ADDEDON { get; set; }
        public Nullable<int> UPDATEDBY { get; set; }
        public Nullable<System.DateTime> UPDATEDON { get; set; }
        public Nullable<short> STATUS { get; set; }
        public Nullable<decimal> TOTALNETAMOUNT { get; set; }
        public string TOTALNETAMOUNTINWORD { get; set; }
        public Nullable<decimal> CGSTAMOUNT { get; set; }
        public string CURRENCYTYPE { get; set; }
        public string REQUESTTYPE { get; set; }
        public Nullable<decimal> FY_CGSTRATE { get; set; }
        public string FINANCEREMARK { get; set; }
        public Nullable<decimal> FY_TDS_AMOUNT { get; set; }
        public Nullable<decimal> FY_IGSTRATE { get; set; }
        public Nullable<decimal> SGSTAMOUNT { get; set; }
        public Nullable<decimal> IGSTAMOUNT { get; set; }
        public Nullable<decimal> TOTAL_GST_AMOUNT { get; set; }
        public string FY_GSTREASON { get; set; }
        public Nullable<System.DateTime> POSTING_DATE { get; set; }
        public string SAP_DOCNO { get; set; }
        public string BUDGETED_ATTACH { get; set; }
        public string PAY_PRO_LOCATION { get; set; }
        public Nullable<int> PAY_PRO_LOCATIONID { get; set; }
        public Nullable<int> LOCATIONID { get; set; }
        public Nullable<decimal> FINAL_TOTAL { get; set; }
        public Nullable<decimal> APPROVED_FINAL_TOTAL { get; set; }
        public string TAXATIONREMARK { get; set; }
        public string GSTIN { get; set; }
        public string TDS_UNDER_SECTIONCODE { get; set; }
        public Nullable<decimal> TDSBASEAMOUNT { get; set; }
        public string SAP_STATUS { get; set; }
    }
}
