//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class NSP_GST_TAX_MASTER
    {
        [Key]
        public int SRNO { get; set; }
        public string TYPE { get; set; }
        public string TAXCODE { get; set; }
        public Nullable<decimal> VATRATE1 { get; set; }
        public Nullable<decimal> VATRATE2 { get; set; }
        public Nullable<long> GLACC1 { get; set; }
        public Nullable<long> GLACC2 { get; set; }
        public Nullable<long> ADDEDBY { get; set; }
        public Nullable<System.DateTime> ADDEDON { get; set; }
        public Nullable<long> UPDATEDBY { get; set; }
        public Nullable<System.DateTime> UPDATEDON { get; set; }
        public string PROFITCENTER { get; set; }
        public string TAXTYPE { get; set; }
        public string ISDEDUCTED { get; set; }
        public Nullable<long> PAYABLE_GLACC1 { get; set; }
        public Nullable<decimal> CESS_RATE { get; set; }
        public Nullable<long> CESS_GLACC { get; set; }
        public Nullable<long> PAYABLE_GLACC2 { get; set; }
        public Nullable<short> ACTIVE { get; set; }
    }
}
