//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class NSP_TDS_TAX_TYPE_MASTER_LOG
    {
        [Key]
        public int SRNO { get; set; }
        public string TAX_TYPE { get; set; }
        public string WITHHOLDING_TAX_NAME { get; set; }
        public Nullable<long> ADDEDBY { get; set; }
        public Nullable<System.DateTime> ADDEDON { get; set; }
        public Nullable<long> UPDATEDBY { get; set; }
        public Nullable<System.DateTime> UPDATEDON { get; set; }
        public Nullable<decimal> RATE { get; set; }
        public Nullable<long> GLACC { get; set; }
        public Nullable<short> ACTIVE { get; set; }
        public Nullable<long> MAINTBLSRNO { get; set; }
        public string LOGMODE { get; set; }
    }
}
