//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class NSP_POSTING_DETAIL
    {
        [Key]
        public int SRNO { get; set; }
        public Nullable<int> HEADERID { get; set; }
        public Nullable<int> DTID { get; set; }
        public string INVOICENO { get; set; }
        public string DOCTYPE { get; set; }
        public string POSTMODE { get; set; }
        public string BUSINESSCENTER { get; set; }
        public string COSTCENTER { get; set; }
        public string PROFITCENTER { get; set; }
        public string ALLOCNUMBER { get; set; }
        public string ITEMTEXT { get; set; }
        public string LIFNR { get; set; }
        public string GLACCOUNT { get; set; }
        public string TAXCODE { get; set; }
        public string ZTYPE { get; set; }
        public decimal AMOUNTDOCUMENTCURRENCY { get; set; }
        public string WTTYPE { get; set; }
        public string WTCODE { get; set; }
        public string SPGLIND { get; set; }
        public string CURRENCY { get; set; }
        public string HEADERTEXT { get; set; }
        public string REFDOCNO { get; set; }
        public Nullable<int> POSTEDBY { get; set; }
        public Nullable<System.DateTime> POSTEDON { get; set; }
        public string POSTDOCNO { get; set; }
        public string BUSINESSPLACE { get; set; }
        public string KUNNR { get; set; }
        public Nullable<decimal> DISCOUNT_AMOUNT { get; set; }
        public Nullable<decimal> TDS_BASE_AMOUNT { get; set; }
        public Nullable<System.DateTime> DOCDATE { get; set; }
    }
}
