//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class RISK_FREQUENCY_IMPACT_MAP_MAST
    {
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        //public RISK_FREQUENCY_IMPACT_MAP_MAST()
        //{
        //    this.RISKASSESSMENT = new HashSet<RISKASSESSMENT>();
        //    this.RISKASSESSMENT1 = new HashSet<RISKASSESSMENT>();
        //    this.RISKASSESSMENT2 = new HashSet<RISKASSESSMENT>();
        //}

        [Key]
        public decimal ID { get; set; }
        public Nullable<decimal> FREQUENCY { get; set; }
        public Nullable<decimal> IMPACT { get; set; }
        public string? RESULT { get; set; }
        public Nullable<decimal> STATUS { get; set; }
        public Nullable<decimal> CREATEDBY { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public Nullable<decimal> LEVELID { get; set; }

        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<RISKASSESSMENT> RISKASSESSMENT { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<RISKASSESSMENT> RISKASSESSMENT1 { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<RISKASSESSMENT> RISKASSESSMENT2 { get; set; }
    }
}
