//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class RISK_REGISTER_COMMONEXIST
    {
        [Key]
        public decimal ID { get; set; }
        public Nullable<decimal> SYKIID { get; set; }
        public Nullable<decimal> USERID { get; set; }
        public Nullable<decimal> ACTIVE { get; set; }
        public Nullable<System.DateTime> CREATIONDATE { get; set; }
        public Nullable<decimal> ACTIONTYPE { get; set; }
    }
}
