//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class RISK_POTENTIAL_MASTER
    {
        public decimal POTENTIALID { get; set; }
        public string POTENTIAL { get; set; }
        public Nullable<decimal> CATEGORYID { get; set; }
    }
}
