//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class RISK_USER_MAPPING
    {
        [Key]
       public decimal RISKUSERMAPPINGID { get; set; }
        public Nullable<decimal> SYKIID { get; set; }
        public Nullable<decimal> DIVISIONID { get; set; }
        public Nullable<decimal> OLDDIVISIONEMPCODE { get; set; }
        public Nullable<decimal> NEWDIVISIONEMPCODE { get; set; }
        public Nullable<decimal> OPRATIONID { get; set; }
        public Nullable<decimal> OLDOPERATIONHEADCODE { get; set; }
        public Nullable<decimal> NEWOPERATIONHEADCODE { get; set; }
        public Nullable<decimal> OLDISSC_MEMBERCODE { get; set; }
        public Nullable<decimal> NEWISSC_MEMBERCODE { get; set; }
        public Nullable<decimal> CREATEDBY { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public Nullable<decimal> MODIFYBY { get; set; }
        public Nullable<System.DateTime> MODIFIEDDATE { get; set; }
    }
}
