//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class RISKASSESSMENT
    {
        [Key]
        public decimal ID { get; set; }
        public Nullable<decimal> SKYID { get; set; }
        public Nullable<decimal> PRIMARY_ASSETID { get; set; }
        public Nullable<decimal> RISK_CATEGORYID { get; set; }
        public Nullable<decimal> POTENTIAL_RISKID { get; set; }
        public Nullable<decimal> RISK_LEADID { get; set; }
        public Nullable<decimal> FREQUENCYID_RISKIDENTIFICATION { get; set; }
        public Nullable<decimal> IMAPCTID_RISKIDENTIFICATION { get; set; }
        public Nullable<decimal> DEG_LEVELID_RISKIDENTIFICATION { get; set; }
        public string RISK_OWNER { get; set; }
        public string CM_TOPRE_POTENTIAL_RISK { get; set; }
        public Nullable<decimal> CURRENT_MEASURES_LEVELID { get; set; }
        public Nullable<decimal> FREQUENCYID { get; set; }
        public Nullable<decimal> IMAPCTID { get; set; }
        public Nullable<decimal> CURRENT_DEGREE_RISK_LEBELID { get; set; }
        public Nullable<decimal> TREATMENT_FOR_RISK_LEVELID { get; set; }
        public string ACTION_ITEM { get; set; }
        public string RESPONSBILITY { get; set; }
        public Nullable<System.DateTime> TARGET_DATE { get; set; }
        public Nullable<decimal> STATUS { get; set; }
        public Nullable<decimal> RISK_STATUS { get; set; }
        public Nullable<decimal> FREQUENCYID_RRA { get; set; }
        public Nullable<decimal> IMAPCTID_RRA { get; set; }
        public Nullable<decimal> RISK_DEGREE_LEVELID_RRA { get; set; }
        public Nullable<decimal> ACTIVE { get; set; }
        public Nullable<decimal> ISSC_MEMBER_STATUS { get; set; }
        public Nullable<decimal> DIVISION_HEAD_ID { get; set; }
        public Nullable<decimal> DIVISION_STATUS { get; set; }
        public Nullable<decimal> OPERATING_HEAD_ID { get; set; }
        public Nullable<decimal> OPERATING_STATUS { get; set; }
        public Nullable<System.DateTime> SUBMIT_DATE_ISSCMEMBER { get; set; }
        public Nullable<System.DateTime> SUBMIT_DATE_DIVISIONHEAD { get; set; }
        public Nullable<System.DateTime> SUBMIT_DATE_OPERATINGHEAD { get; set; }
        public string REVIEW_REMARK_DIVISIONHEAD { get; set; }
        public string REVIEW_REMARK_OPERATINGHEAD { get; set; }
        public Nullable<decimal> APRROVE_STATUS { get; set; }
        public Nullable<decimal> RISK_CREATEDBY { get; set; }
        public Nullable<System.DateTime> RISK_CREATEDDATE { get; set; }
        public Nullable<decimal> RISK_UPDATEDBY { get; set; }
        public Nullable<System.DateTime> RISK_UPDATEDDATE { get; set; }
        public Nullable<decimal> IMPACTTYPEID { get; set; }
        public string OTHERPOTENTIAL { get; set; }

        //public virtual ASSET_REGISTER_ASSETDETAILS ASSET_REGISTER_ASSETDETAILS { get; set; }
        //public virtual IMPACTTYPE IMPACTTYPE { get; set; }
        //public virtual RISK_CATEGORY_MASTER RISK_CATEGORY_MASTER { get; set; }
        //public virtual RISK_CURRENTMEASURE_LVL RISK_CURRENTMEASURE_LVL { get; set; }
        //public virtual RISK_FREQUENCY_IMPACT_MAP_MAST RISK_FREQUENCY_IMPACT_MAP_MAST { get; set; }
        //public virtual RISK_FREQUENCY_IMPACT_MAP_MAST RISK_FREQUENCY_IMPACT_MAP_MAST1 { get; set; }
        //public virtual RISK_FREQUENCY_IMPACT_MAP_MAST RISK_FREQUENCY_IMPACT_MAP_MAST2 { get; set; }
        //public virtual RISK_FREQUENCY_MASTER RISK_FREQUENCY_MASTER { get; set; }
        //public virtual RISK_FREQUENCY_MASTER RISK_FREQUENCY_MASTER1 { get; set; }
        //public virtual RISK_FREQUENCY_MASTER RISK_FREQUENCY_MASTER2 { get; set; }
        //public virtual RISK_IMPACT_MASTER RISK_IMPACT_MASTER { get; set; }
        //public virtual RISK_IMPACT_MASTER RISK_IMPACT_MASTER1 { get; set; }
        //public virtual RISK_IMPACT_MASTER RISK_IMPACT_MASTER2 { get; set; }
        //public virtual RISK_LEADTO_BREACH RISK_LEADTO_BREACH { get; set; }
        //public virtual RISK_STATEMENT_MASTER RISK_STATEMENT_MASTER { get; set; }
        //public virtual RISK_TREATMENT_RISK_LVL RISK_TREATMENT_RISK_LVL { get; set; }
    }
}


