//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class RISK_APPROVAL_DETAILS
    {
        public decimal RISK_APPROVAL_ID { get; set; }
        public Nullable<decimal> RISK_ID { get; set; }
        public Nullable<decimal> STATUS { get; set; }
        public Nullable<decimal> ACTION_BY { get; set; }
        public string REMARKS { get; set; }
        public Nullable<System.DateTime> ACTION_DATE { get; set; }
        public Nullable<decimal> SKYID { get; set; }
    }
}
