//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class RISK_LEADTO_BREACH
    {
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        //public RISK_LEADTO_BREACH()
        //{
        //    this.RISKASSESSMENT = new HashSet<RISKASSESSMENT>();
        //}

        [Key]
        public decimal RISKLEADID { get; set; }
        public string? RISKLEADTYPE { get; set; }
        public decimal? POTENTIALID { get; set; }

        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<RISKASSESSMENT> RISKASSESSMENT { get; set; }
    }
}
