//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;    
   
    public partial class RISK_ASSESSMENT_DEFICIENCY
    {
        public decimal ID { get; set; }
        public Nullable<decimal> OPERATIONID { get; set; }
        public Nullable<decimal> DIVISIONID { get; set; }
        public Nullable<decimal> PRIMARYASSETID { get; set; }
        public Nullable<decimal> RISKCATEGORYID { get; set; }
        public string FEEDBACK { get; set; }
        public Nullable<decimal> ISSCEMPCODE { get; set; }
        public Nullable<System.DateTime> CREATIONDATE { get; set; }
        public Nullable<decimal> CREATEDBY { get; set; }
    }
}
