//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class RISK_ASSESSMENT_ITGRC_PERIOD
    {
        [Key]
        public decimal ID { get; set; }
        public Nullable<decimal> SKIID { get; set; }
        public Nullable<decimal> OPERATIONID { get; set; }
        public Nullable<decimal> DIVISIONID { get; set; }
        public Nullable<System.DateTime> STARTDATE { get; set; }
        public Nullable<System.DateTime> ENDDATE { get; set; }
        public Nullable<decimal> CREATEDBY { get; set; }
        public Nullable<System.DateTime> CREATIONDATE { get; set; }
        public Nullable<decimal> ACTIVE { get; set; }
        public Nullable<decimal> UPDATEDBY { get; set; }
        public Nullable<System.DateTime> UPDATIONDATE { get; set; }
    }
}
