//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class RISK_IMPACT_MASTER
    {
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        //public RISK_IMPACT_MASTER()
        //{
        //    this.RISKASSESSMENT = new HashSet<RISKASSESSMENT>();
        //    this.RISKASSESSMENT1 = new HashSet<RISKASSESSMENT>();
        //    this.RISKASSESSMENT2 = new HashSet<RISKASSESSMENT>();
        //}

        [Key]
        public decimal RISK_LEVEL { get; set; }
        public string? DEGREE_OF_IMPACT { get; set; }
        public Nullable<decimal> IMPACTTYPEID { get; set; }

        //public virtual IMPACTTYPE IMPACTTYPE { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<RISKASSESSMENT> RISKASSESSMENT { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<RISKASSESSMENT> RISKASSESSMENT1 { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<RISKASSESSMENT> RISKASSESSMENT2 { get; set; }
    }
}
