//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class RISK_REGISTER_ASSETDETAILS
    {
        [Key]
        public decimal ID { get; set; }
        public Nullable<decimal> SKIID { get; set; }
        public string PRIMARY { get; set; }
        public string SECONDARY { get; set; }
        public Nullable<decimal> ASSETID { get; set; }
        public string LOCATION { get; set; }
        public string OWNER { get; set; }
        public string CUSTODIAN { get; set; }
        public string ASSETUSER { get; set; }
        public Nullable<decimal> CLASSIFICATIONID { get; set; }
        public string RETENTION { get; set; }
        public Nullable<decimal> CREATEDBY { get; set; }
        public Nullable<System.DateTime> CREATIONDATE { get; set; }
        public Nullable<decimal> UPDATEDBY { get; set; }
        public Nullable<System.DateTime> UPDATIONDATE { get; set; }
        public Nullable<decimal> ACTIONTYPE { get; set; }
        public Nullable<decimal> ACTIVE { get; set; }
        public Nullable<decimal> SAVE { get; set; }
        public Nullable<decimal> ISSCMEMBER_STATUS { get; set; }
        public Nullable<decimal> DIVISIONHEAD_ID { get; set; }
        public Nullable<decimal> DIVISION_STATUS { get; set; }
        public Nullable<decimal> OPERATINGHEAD_ID { get; set; }
        public Nullable<decimal> OPERATIONG_STATUS { get; set; }
        public Nullable<System.DateTime> FINALSUBMITDATE_ISSCMEMBER { get; set; }
        public Nullable<System.DateTime> FINALSUBMITDATE_DIVISIONHEAD { get; set; }
        public Nullable<System.DateTime> FINALSUBMITDATE_OPERATINGHEAD { get; set; }
        public string REVIEW_REMARKS_DIVISIONHEAD { get; set; }
        public string REVIEW_REMARKS_OPERATINGHEAD { get; set; }
        public string ISSC_MEMBER_REASON { get; set; }
        public string RETENTION_REMARK { get; set; }
        public Nullable<decimal> ASSET_REG_STATUS { get; set; }
    }
}
