//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class RISK_ASSESSMENT_MEMNOMINATION
    {
        public decimal ID { get; set; }
        public Nullable<decimal> PERIODSETTINGID { get; set; }
        public Nullable<decimal> SYKIID { get; set; }
        public Nullable<decimal> DIVISIONID { get; set; }
        public Nullable<decimal> OPERATIONID { get; set; }
        public Nullable<decimal> ISSCEMPCODE { get; set; }
        public Nullable<decimal> STATUS { get; set; }
        public Nullable<decimal> ACTIVE { get; set; }
        public Nullable<decimal> ADDEDBY { get; set; }
        public Nullable<System.DateTime> ADDEDDATE { get; set; }
        public Nullable<decimal> UPDATEDBY { get; set; }
        public Nullable<System.DateTime> UPDATEDDATE { get; set; }
    }
}
