//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SIS_AST_PARAM_MST
    {
        [Key]
        public long SIS_AST_PARAM_MSTID { get; set; }
        public string PARAMNAME { get; set; }
        public string PARAMDESCRIPTION { get; set; }
        public string PARAMVALUETYPE { get; set; }
        public string PARAMTYPE { get; set; }
        public short ACTIVE { get; set; }
        public System.DateTime DATEADDED { get; set; }
        public long ADDEDBY { get; set; }
        public DateTime? DATELSTMOD { get; set; }
        public long? MODIFIEDBY { get; set; }
        public string DISPLAY_LABEL { get; set; }
    }
}
