//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SIS_AST_ERROR_MST
    {
        [Key]
        public long SIS_AST_ERROR_MSTTID { get; set; }
        public string ERRORCODE { get; set; }
        public string ERRORDESCRIPTION { get; set; }
        public short ACTIVE { get; set; }
        public System.DateTime DATEADDED { get; set; }
        public long ADDEDBY { get; set; }
        public System.DateTime DATELSTMOD { get; set; }
        public long MODIFIEDBY { get; set; }
    }
}
