//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SIS_AST_PROCESSSTATUS_MST
    {
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        //public SIS_AST_PROCESSSTATUS_MST()
        //{
        //    this.SIS_AST_DISPOSALHEADER = new HashSet<SIS_AST_DISPOSALHEADER>();
        //}
        [Key]
        public long SIS_AST_PROCESSSTATUS_MSTID { get; set; }
        public string STATUSDESCRIPTION { get; set; }
        public short STATUS_LEVEL { get; set; }
        public short CATEGORY { get; set; }
        public string DISPLAY_MSG { get; set; }
        public short ACTIVE { get; set; }
        public System.DateTime DATEADDED { get; set; }
        public long ADDEDBY { get; set; }
        public DateTime? DATELSTMOD { get; set; }
        public long? MODIFIEDBY { get; set; }
        public short? SEQ_NUMBER { get; set; }

        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<SIS_AST_DISPOSALHEADER> SIS_AST_DISPOSALHEADER { get; set; }
    }
}
