//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SIS_AST_DISPOSALCUSTDETAIL
    {
        [Key]
        public long DISPOSALCUSTDETAILID { get; set; }
        public long DISPOSALHEADERID { get; set; }
        public string CUSTOMERCODE { get; set; }
        public string CUSTOMERNAME { get; set; }
        public string CUSTADDRESS { get; set; }
        public string CUSTGSTIN { get; set; }
        public decimal BASICVALUE { get; set; }
        public string GSTRATE { get; set; }
        public string PAYMENTDETAILS { get; set; }
        public short ACTIVE { get; set; }
        public System.DateTime DATEADDED { get; set; }
        public long ADDEDBY { get; set; }
        public DateTime? DATELSTMOD { get; set; }
        public long? MODIFIEDBY { get; set; }

        //public virtual SIS_AST_DISPOSALHEADER SIS_AST_DISPOSALHEADER { get; set; }
    }
}
