//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SIS_AST_DISPOSALDETAIL
    {
        [Key]
        public long DISPOSALDETAILID { get; set; }
        public long DISPOSALHEADERID { get; set; }
        public string ASSETCODE { get; set; }
        public string ASSETDESCRIPTION { get; set; }
        public string VENDORNAME { get; set; }
        public string VENDORCODE { get; set; }
        public string INVOICENO { get; set; }
        public DateTime? INVOICEDATE { get; set; }
        public string BILLENTRY { get; set; }
        public string LICENSENO { get; set; }
        public DateTime? PURCHASEDDATE { get; set; }
        public decimal? ORIGINALCOST { get; set; }
        public decimal? DEPRECIATIONCOST { get; set; }
        public decimal? SALESPRICE { get; set; }
        public short? MGF_QLTYSTATUS { get; set; }
        public short? EVNSTATUS { get; set; }
        public short? TAXTION_STATUS { get; set; }
        public short? ASSET_CATEGORY { get; set; }
        public short? CONDITIONID { get; set; }
        public short? VIBRATION_SENSOR { get; set; }
        public short? PARTIAL_FULL { get; set; }
        public string VALUATION_GST { get; set; }
        public decimal? TENTATIVE { get; set; }
        public short ACTIVE { get; set; }
        public System.DateTime DATEADDED { get; set; }
        public long ADDEDBY { get; set; }
        public DateTime? DATELSTMOD { get; set; }
        public long? MODIFIEDBY { get; set; }
        public short? MAINTENANCEDEPT_STATUS { get; set; }
        public short? IC_STATUS { get; set; }
        public short? IBM_STATUS { get; set; }
        public string SERIALNUMBER { get; set; }
        public long? PLANTID { get; set; }
        public string PONUMBER { get; set; }
        public DateTime? CAPTALIZED_DATE { get; set; }

        //public virtual SIS_AST_DISPOSALHEADER SIS_AST_DISPOSALHEADER { get; set; }
    }
}
