//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SIS_AST_DISPOSALHEADER
    {
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        //public SIS_AST_DISPOSALHEADER()
        //{
        //    this.SIS_AST_DISPOSALAPPHISTORY = new HashSet<SIS_AST_DISPOSALAPPHISTORY>();
        //    this.SIS_AST_DISPOSALCUSTDETAIL = new HashSet<SIS_AST_DISPOSALCUSTDETAIL>();
        //    this.SIS_AST_DISPOSALDETAIL = new HashSet<SIS_AST_DISPOSALDETAIL>();
        //}
        [Key]
        public long DISPOSALHEADERID { get; set; }
        public long ADEMPCODE { get; set; }
        public long ASSETTYPEID { get; set; }
        public string? BACKUP_ATTACHMENT { get; set; }
        public string? TRANSFERSLIP_ATTACHMENT { get; set; }
        public string? MUTILATION_ATTACHMENT { get; set; }
        public long? SYKI { get; set; }
        public long PROCESSSTATUSID { get; set; }
        public string? REMARKS { get; set; }
        public string? INVOICE_ATTACHMENT { get; set; }
        public string? ASSETDISPOSALINVOICE { get; set; }
        public short? ISPLANTREQUIRED { get; set; }
        public short? P1F_APPSTATUS { get; set; }
        public short? P2F_APPSTATUS { get; set; }
        public short? P3F_APPSTATUS { get; set; }
        public short? P4F_APPSTATUS { get; set; }
        public short ACTIVE { get; set; }
        public System.DateTime DATEADDED { get; set; }
        public long ADDEDBY { get; set; }
        public DateTime? DATELSTMOD { get; set; }
        public long? MODIFIEDBY { get; set; }
        public string P1F_ATTACHMENT { get; set; }
        public string P2F_ATTACHMENT { get; set; }
        public string P3F_ATTACHMENT { get; set; }
        public string P4F_ATTACHMENT { get; set; }
        public short? ISUPLOADINV_BYTAXATION { get; set; }
        public long? PLANTID { get; set; }
        public DateTime? IBM_APPDATE { get; set; }
        public string ICMONTH { get; set; }
        public string IMPLEMENTMONTH { get; set; }

        //public virtual ADEMPLOYEE ADEMPLOYEE { get; set; }
        //public virtual SIS_ASSETTYPE_MST SIS_ASSETTYPE_MST { get; set; }
        ////[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<SIS_AST_DISPOSALAPPHISTORY> SIS_AST_DISPOSALAPPHISTORY { get; set; }
        ////[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<SIS_AST_DISPOSALCUSTDETAIL> SIS_AST_DISPOSALCUSTDETAIL { get; set; }
        ////[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<SIS_AST_DISPOSALDETAIL> SIS_AST_DISPOSALDETAIL { get; set; }
        //public virtual SIS_AST_PROCESSSTATUS_MST SIS_AST_PROCESSSTATUS_MST { get; set; }
    }
}
