//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SIS_AST_APPAUTH_MST
    {
        [Key]
        public long SIS_AST_APPAUTH_MSTID { get; set; }
        public long EMPCODE { get; set; }
        public long? SYSITEID { get; set; }
        public long ADORGLEVELID { get; set; }
        public long APPROVALTYPE { get; set; }
        public short ACTIVE { get; set; }
        public System.DateTime DATEADDED { get; set; }
        public long ADDEDBY { get; set; }
        public DateTime? DATELSTMOD { get; set; }
        public long? MODIFIEDBY { get; set; }

        //public virtual ADEMPLOYEE ADEMPLOYEE { get; set; }
        //public virtual ADORGLEVEL ADORGLEVEL { get; set; }
    }
}
