//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SIS_AST_MGFPLANTAPPROVAL
    {
        [Key]
        public long MGFPLANTAPPID { get; set; }
        public long? DISPOSALDETAILID { get; set; }
        public string C1F_CONDITION { get; set; }
        public string C2F_CONDITION { get; set; }
        public string C3F_CONDITION { get; set; }
        public string C4F_CONDITION { get; set; }
        public long? C1F_APPROVEBY { get; set; }
        public long? C2F_APPROVEBY { get; set; }
        public long? C3F_APPROVEBY { get; set; }
        public long? C4F_APPROVEBY { get; set; }
        public short ACTIVE { get; set; }
        public System.DateTime DATEADDED { get; set; }
        public long ADDEDBY { get; set; }
        public DateTime? DATELSTMOD { get; set; }
        public long? MODIFIEDBY { get; set; }
    }
}
