//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SIS_AST_DISPOSALAPPHISTORY
    {
        [Key]
        public long APPROVALHISTORYID { get; set; }
        public long DISPOSALHEADERID { get; set; }
        public long APPCODE { get; set; }
        public long PROCESSSTATUSID { get; set; }
        public string REMARKS { get; set; }
        public string ATTACHMENT { get; set; }
        public short APPROVALSTATUS { get; set; }
        public System.DateTime DATEADDED { get; set; }
        public long ADDEDBY { get; set; }

        //public virtual SIS_AST_DISPOSALHEADER SIS_AST_DISPOSALHEADER { get; set; }
    }
}
