//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SM_DIVISIONWISESEATDETAILS
    {
        [Key]
        public long DWS_DTLID { get; set; }
        public long FLOOR_OPMAPPID { get; set; }
        public long ADORGLEVELID { get; set; }
        public short PHYSICALSEAT { get; set; }
        public short STATUS { get; set; }
        public long ADDEDBY { get; set; }
        public System.DateTime ADDEDON { get; set; }
        public long? UPDATEDBY { get; set; }
        public DateTime? UPDATEDON { get; set; }

        public string? ISSEATAUTOUPDATED { get; set; }

        //public virtual SM_FLOOR_OPMAP SM_FLOOR_OPMAP { get; set; }
    }
}
