//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class SM_EMP_ACTIVEINACTIVEFORROSTER_LOG
    {
        public long ACTIVEINACTIVE_HIS_ID { get; set; }
        public long RID { get; set; }
        public long ADEMPCODE { get; set; }
        public short ACTIVITY_STATUS { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public long ADDED_BY { get; set; }
        public System.DateTime UPDATED_DATE { get; set; }
        public long UPDATED_BY { get; set; }
    }
}
