//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SM_FLOORSEATMST
    {
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        //public SM_FLOORSEATMST()
        //{
        //    this.SM_SEATALLOCATION_TRN = new HashSet<SM_SEATALLOCATION_TRN>();
        //    this.SM_FIXSEATMAP = new HashSet<SM_FIXSEATMAP>();
        //}

        [Key]
        public long SEATMSTID { get; set; }
        public long FLOORID { get; set; }
        public string SEATNAME { get; set; }
        public string SEATNO { get; set; }
        public short STATUS { get; set; }
        public long ADDEDBY { get; set; }
        public DateTime ADDEDON { get; set; }
        public long? UPDATEDBY { get; set; }
        public DateTime? UPDATEDON { get; set; }
    
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<SM_SEATALLOCATION_TRN> SM_SEATALLOCATION_TRN { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<SM_FIXSEATMAP> SM_FIXSEATMAP { get; set; }
        //public virtual SM_FLOORMASTER SM_FLOORMASTER { get; set; }
    }
}
