//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SM_FLOORMASTER
    {
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        //public SM_FLOORMASTER()
        //{
        //    this.SM_FLOOR_OPMAP = new HashSet<SM_FLOOR_OPMAP>();
        //    this.SM_FLOORSEATMST = new HashSet<SM_FLOORSEATMST>();
        //}

        [Key]
        public long SM_FLOOR_ID { get; set; }
        public long SITEID { get; set; }
        public string BUILDING { get; set; }
        public string FLOOR_NAME { get; set; }
        public short STATUS { get; set; }
        public long ADDEDBY { get; set; }
        public DateTime ADDEDDATE { get; set; }
        public long? UPDATEDBY { get; set; }
        public DateTime? UPDATEDDATE { get; set; }
        public string MAP_FILE_NAME { get; set; }
    
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<SM_FLOOR_OPMAP> SM_FLOOR_OPMAP { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<SM_FLOORSEATMST> SM_FLOORSEATMST { get; set; }
    }
}
