//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SM_FLOOR_OPMAP
    {
        [Key]
        public long FLOOR_OPMAPPID { get; set; }
        public long FLOORID { get; set; }
        public long OPERATIONID { get; set; }
        public short SEATCAPACITY { get; set; }
        public short STATUS { get; set; }
        public long ADDEDBY { get; set; }
        public DateTime ADDEDDATE { get; set; }
        public long? UPDATEDBY { get; set; }
        public DateTime? UPDATEDDATE { get; set; }
        public long SYKIID { get; set; }
        public string? ISSEATAUTOUPDATED { get; set; }

        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<SM_DIVISIONWISESEATDETAILS> SM_DIVISIONWISESEATDETAILS { get; set; }
        //public virtual SM_FLOORMASTER SM_FLOORMASTER { get; set; }
    }
}
