//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SM_ROSTER_TRN
    {
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        //public SM_ROSTER_TRN()
        //{
        //    this.SM_SEATALLOCATION_TRN = new HashSet<SM_SEATALLOCATION_TRN>();
        //}
        [Key]   
        public long RSTTRNID { get; set; }
        public long ADEMPCODE { get; set; }
        public System.DateTime ROSTER_DATE { get; set; }
        public short STATUS { get; set; }
        public long ADDEDBY { get; set; }
        public System.DateTime ADDEDON { get; set; }
        public long? UPDATEDBY { get; set; }
        public DateTime? UPDATEDON { get; set; }
        public short? IS_OHACTION { get; set; }
        public Nullable<short> IS_NEWJOINEEDAY { get; set; } //SR102091

        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<SM_SEATALLOCATION_TRN> SM_SEATALLOCATION_TRN { get; set; }
    }
}
