//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SM_SEATALLOCATION_TRN
    {
        [Key]
        public long ALLOCATIONTRNID { get; set; }
        public long RSTTRNID { get; set; }
        public long SEATMSTID { get; set; }
        public short STATUS { get; set; }
        public long ADDEDBY { get; set; }
        public System.DateTime ADDEDON { get; set; }
        public Nullable<long> UPDATEDBY { get; set; }
        public Nullable<System.DateTime> UPDATEDON { get; set; }
    
        //public virtual SM_FLOORSEATMST SM_FLOORSEATMST { get; set; }
        //public virtual SM_ROSTER_TRN SM_ROSTER_TRN { get; set; }
    }
}


