//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class SM_WFOMANDATORYDAYS_LOG
    {
        public long HISTORY_ID { get; set; }
        public long DAY_VALUE { get; set; }
        public long MODIFIED_BY { get; set; }
        public System.DateTime MODIFIED_DATE { get; set; }
        public string PARAM_NAME { get; set; }
    }
}
