//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SYAPPLICATION
    {
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        //public SYAPPLICATION()
        //{
        //    this.EMP_LOGINDETAIL = new HashSet<EMP_LOGINDETAIL>();
        //    this.EMP_APPLICATIONMAP_AD = new HashSet<EMP_APPLICATIONMAP_AD>();
        //}

        [Key]
        public long SYAPPLICATIONID { get; set; }
        public string CODE { get; set; }
        public string DESCRIP { get; set; }
        public short ACTIVE { get; set; }
        public System.DateTime DATEADDED { get; set; }
        public long ADDEDBY { get; set; }
        public System.DateTime? DATELSTMOD { get; set; }
        public long? MODIFIEDBY { get; set; }
    
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<EMP_LOGINDETAIL> EMP_LOGINDETAIL { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<EMP_APPLICATIONMAP_AD> EMP_APPLICATIONMAP_AD { get; set; }
    }
}
