//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SYKI
    {
        [Key]
        public decimal SYKIID { get; set; }
        public string KICODE { get; set; }
        public string FINANCIALYEAR { get; set; }
        public decimal ACTIVE { get; set; }
        public System.DateTime DATEADDED { get; set; }
        public decimal ADDEDBY { get; set; }
        public Nullable<System.DateTime> DATELSTMOD { get; set; }
        public Nullable<decimal> MODIFIEDBY { get; set; }
        public string REMARKS { get; set; }
    }
}
