//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("SYPARAMETERS")]
    public partial class SYPARAMETERS_LC
    {
        [Key]
        public long SYPARAMETERSID { get; set; }
        public string PARAMNAME { get; set; }
        public string PARAMDESCRIPTION { get; set; }
        public string PARAMVALUE { get; set; }
        public System.DateTime DATEADDED { get; set; }
        public long ADDEDBY { get; set; }
        public Nullable<long> MODIFIEDBY { get; set; }
        public Nullable<System.DateTime> DATELSTMOD { get; set; }
        public string USED_IN { get; set; }
        public string MODULE { get; set; }
    }
}
