//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("SYPLANT")]
    public partial class SYPLANT_LC
    {
        [Key]
        public short SYPLANTID { get; set; }
        public string PLANTNAME { get; set; }
        public string PLANTADDRESS { get; set; }
        public Nullable<short> ACTIVE { get; set; }
        public Nullable<System.DateTime> DATEADDED { get; set; }
        public Nullable<long> ADDEDBY { get; set; }
        public Nullable<System.DateTime> DATELSTMOD { get; set; }
        public Nullable<long> MODBY { get; set; }
        public string SAPDESC { get; set; }
        public string PROFIT_CENTER { get; set; }
        public string ORDERNO { get; set; }
    }
}
