//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SYSITESHIFT
    {
        [Key]
        public long SYSHIFTID { get; set; }
        public string CODE { get; set; }
        public string DESCRIP { get; set; }
        public System.DateTime DATEADDED { get; set; }
        public long ADDEDBY { get; set; }
        public Nullable<System.DateTime> DATELSTMOD { get; set; }
        public Nullable<long> MODIFIEDBY { get; set; }
        public short ACTIVE { get; set; }
        public long SYSITEID { get; set; }
        public Nullable<System.DateTime> START_TIME { get; set; }
        public Nullable<System.DateTime> END_TIME { get; set; }
        public string SAPSIFTDESC { get; set; }
        public Nullable<decimal> HALFDAYHOUR { get; set; }
    
        public virtual SYSITE SYSITE { get; set; }
    }
}
