//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("SYSITE")]
    public partial class SYSITE_LC
    {
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        //public SYSITE_LC()
        //{
        //    this.ADEMPLOYEEs = new HashSet<ADEMPLOYEE_LC>();
        //}
        [Key]
        public long SYSITEID { get; set; }
        public string DESCRIP { get; set; }
        public decimal ACTIVE { get; set; }
        public System.DateTime DATEADDED { get; set; }
        public long ADDEDBY { get; set; }
        public Nullable<System.DateTime> DATELSTMOD { get; set; }
        public Nullable<long> MODIFIEDBY { get; set; }
        public string SAPDESC { get; set; }
        public string SITEADDRESS { get; set; }
        public Nullable<short> PROFIT_CENTER { get; set; }
    
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<ADEMPLOYEE_LC> ADEMPLOYEEs { get; set; }
    }
}
