//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SYSITE_DGIT
    {
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        //public SYSITE_DGIT()
        //{
        //    this.ADEMPLOYEE = new HashSet<ADEMPLOYEE_DGIT>();
        //}
        [Key]
        public long SYSITEID { get; set; }
        public string DESCRIP { get; set; }
        public decimal ACTIVE { get; set; }
        public System.DateTime DATEADDED { get; set; }
        public long ADDEDBY { get; set; }
        public DateTime? DATELSTMOD { get; set; }
        public long? MODIFIEDBY { get; set; }
        public string SAPDESC { get; set; }
        public string SITEADDRESS { get; set; }
        public short? PROFIT_CENTER { get; set; }
    
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<ADEMPLOYEE_DGIT> ADEMPLOYEE { get; set; }
    }
}
