//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYUSERTYPE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SYUSERTYPE()
        {
            this.ADEMPLOGIN = new HashSet<ADEMPLOGIN>();
        }
    
        public long SYUSERTYPEID { get; set; }
        public string DESCRIP { get; set; }
        public System.DateTime DATEADDED { get; set; }
        public Nullable<System.DateTime> DATELSTMODE { get; set; }
        public long ADDEDBY { get; set; }
        public Nullable<long> MODIFIEDBY { get; set; }
        public short ACTIVE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ADEMPLOGIN> ADEMPLOGIN { get; set; }
    }
}
