//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TP_EMP_DETAIL
    {
        [Key]
        public long TPID { get; set; }
        public long EMPCODE { get; set; }
        public string ASSOCIATENAME { get; set; }
        public string DESIGNATION { get; set; }
        public string COMPANYNAME { get; set; }
        public string ASSCOMPANYID { get; set; }
        public string PROJECTMANAGERNAME { get; set; }
        public string PROJECTMANAGERMAILID { get; set; }
        public string ACCOUNTMANAGERNAME { get; set; }
        public string ACCOUNTMANAGERMAILID { get; set; }
        public long? CREATEDBY { get; set; }
        public DateTime? CREATEDDATE { get; set; }
        public long? MODIFIEDBY { get; set; }
        public DateTime? MODIFIEDDATE { get; set; }
        public long OWNERSHIP { get; set; }
        public short IS_DEBOARDED { get; set; }
    }
}
