//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class VPF_ENTRYDETAILS
    {
        [Key]
        public int ID { get; set; }
        public long EMPLOYEECODE { get; set; }
        public Nullable<short> REQUESTTYPE { get; set; }
        public Nullable<int> VPFCONTRIBUTION { get; set; }
        public Nullable<System.DateTime> EFFECTIVEDATE { get; set; }
        public string CANCELREMARKS { get; set; }
        public Nullable<short> STATUS { get; set; }
        public Nullable<System.DateTime> DATEADDED { get; set; }
        public Nullable<System.DateTime> MODIFIEDDATE { get; set; }
        public Nullable<long> MODIFIEDBY { get; set; }
        public Nullable<long> APPROVESTATUS { get; set; }
        public Nullable<long> APPROVALAUTHID { get; set; }
        public Nullable<System.DateTime> APPROVALDATE { get; set; }
        public string APPROVALREMARKS { get; set; }
        public Nullable<long> KI { get; set; }
    }
}
