//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_ASSOCIATELVLDETAILS_DGIT
    {
        public long ADEMPCODE { get; set; }
        public long? SYKI { get; set; }
        public long? SUPERVISOREMPCODE { get; set; }
        public long? SUPSUPERVISOREMPCODE { get; set; }
        public long? ADDESIGNATIONID { get; set; }
        public string FUNCTIONALDESIGNATION { get; set; }
        public long? ADFUNCTIONALDESIGNATIONID { get; set; }
        public long? SYSITEID { get; set; }
        public long? SYPLANTID { get; set; }
        public string ZONE { get; set; }
        public long? SYLOCATIONID { get; set; }
        public short ACTIVE { get; set; }
        public long? SECTIONID { get; set; }
        public string SECTION { get; set; }
        public string SEC_COSTCENTRE { get; set; }
        public long? DEPARTMENTID { get; set; }
        public string DEPARTMENT { get; set; }
        public string DEPT_COSTCENTRE { get; set; }
        public long? DIVISIONID { get; set; }
        public string DIVISION { get; set; }
        public string DIV_COSTCENTRE { get; set; }
        public long? OPERATIONID { get; set; }
        public string OPERATION { get; set; }
        public string OP_COSTCENTRE { get; set; }
        public decimal? OPERATIONID_1 { get; set; }
        public string OPERATION_1 { get; set; }
        public string OP1_COSTCENTRE { get; set; }
        public string ADDITIONALDESG { get; set; }
    }
}
