//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class VW_DGIT_POREPORT
    {
        [Key]
        public long POHEADERID { get; set; }
        public string PONO { get; set; }
        public string VENDORID { get; set; }
        public string REMARK { get; set; }
        public short STATUS { get; set; }
        public short PROCESS_STATUS { get; set; }
        public string VENDORMAILID { get; set; }
        public System.DateTime DATEADDED { get; set; }
        public decimal SYKIID { get; set; }
        public string KICODE { get; set; }
        public long ADDEDBY { get; set; }
        public System.DateTime? UPDATEDATE { get; set; }
        public long? UPDATEDBY { get; set; }
        public string CONTRACT_NO { get; set; }
        public string PO_DESC { get; set; }
        public short? HIGH_URGENCY { get; set; }
        public short MAILCNT { get; set; }
        public string PLANTID { get; set; }
        public short? VERSION_NO { get; set; }
        public long? OPERATIONID { get; set; }
        public string OPERATION { get; set; }
        public long? DIVISIONID { get; set; }
        public string DIVISION { get; set; }
        public long? DEPARTMENTID { get; set; }
        public string DEPARTMENT { get; set; }
        public long? SECTIONID { get; set; }
        public string SECTION { get; set; }
        public string ADDEDBYNAME { get; set; }
        public string VENDORNAME { get; set; }
    }
}
