//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class VW_DGIT_ACRHEADER
    {
        [Key]
        public long ACRHEADERID { get; set; }
        public string ACRNO { get; set; }
        public decimal AMOUNT { get; set; }
        public string REMARK { get; set; }
        public short STATUS { get; set; }
        public short PROCESS_STATUS { get; set; }
        public System.DateTime DATEADDED { get; set; }
        public long ADDEDBY { get; set; }
        public DateTime? UPDATEDATE { get; set; }
        public long? UPDATEDBY { get; set; }
        public string ACR_DESC { get; set; }
        public string PO_NUMBER { get; set; }
        public string SUPPLIER_CODE { get; set; }
        public string SUPPLIER_NAME { get; set; }
        public short?  DOC_STATUS { get; set; }
        public DateTime? DOC_REV_DATE { get; set; }
        public long? DOC_REV_BY { get; set; }
        public short?  PA_GENERATED { get; set; }
        public long? SYKIID { get; set; }
        public long? SYSITEID { get; set; }
    }
}
