//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_DGIT_PODASHBOARD
    {
        public long POHEADERID { get; set; }
        public string PONO { get; set; }
        public string VENDORNAME { get; set; }
        public string PRNO { get; set; }
        public long ADDEDBY { get; set; }
        public string ADDEDBYNAME { get; set; }
        public System.DateTime UPDATEDATE { get; set; }
        public string FILENAME { get; set; }
        public string PLANTID { get; set; }
        public Nullable<short> VERSION_NO { get; set; }
    }
}
