//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_MEDINS_EMPDETAIL
    {
        
        public long SNO { get; set; }
        public string REQUESTTYPE { get; set; }
        public long? EMP_CODE { get; set; }
        public string ENAME { get; set; }
        public string TMOBILE { get; set; }
        public string PERNAME { get; set; }
        public string GENDER { get; set; }
        public DateTime? DOB { get; set; }
        public string RELATIONSHIP { get; set; }
        public string RECTYPE { get; set; }
        public string DESIGNATION { get; set; }
        public string CHANGETYPE { get; set; }
        public string PAIDTYPE { get; set; }
    }
}
