//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_PRUSERDASHBOARD
    {
        public string ADDEDBYNAME { get; set; }
        public System.DateTime DATEADDED { get; set; }
        public decimal INDENT_AMOUNT { get; set; }
        public string INDENT_NO { get; set; }
        public long PRHEADERID { get; set; }
        public string ITEM_DETAIL { get; set; }
        public long? OPERATIONID { get; set; }
        public long? DIVISIONID { get; set; }
        public long? DEPARTMENTID { get; set; }
        public long? SECTIONID { get; set; }
        public long ADDEDBY { get; set; }
        public DateTime? UPDATEDATE { get; set; }
        public DateTime? PRAPPDATE { get; set; }
        public string POAPPROVALSTATUS { get; set; }
        public string PONO { get; set; }
        public short?  POSTATUS { get; set; }
        public string BUYERNAME { get; set; }
        public string BUYERSTATUS { get; set; }
        public DateTime? POAPPDATE { get; set; }
        public string DEPARTMENT { get; set; }
        public string DIVISION { get; set; }
        public string OPERATION { get; set; }
        public string SECTION { get; set; }
        public short?  IS_IPRELATEDPR { get; set; }
        public long? BUYSITEID { get; set; }
        public string ARIBARFPID { get; set; }
        public short?  ARIBASTATUS { get; set; }
        public long? ARIBABUYER { get; set; }
        public string ARIBASRNO { get; set; }
    }
}
