//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePortal.DomainClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_SMIOCGAPPROVER_LIST
    {
        public long SMMAP_MSTID { get; set; }
        public long ADORGLEVELID { get; set; }
        public string ORGNAME { get; set; }
        public long APPROVER1 { get; set; }
        public short ACTIVE { get; set; }
        public DateTime? UPDDATE { get; set; }
        public long? UPDBY { get; set; }
        public long STARTAMOUNT { get; set; }
        public long ENDAMOUNT { get; set; }
        public long SYKIID { get; set; }
        public short SESORMRN { get; set; }
        public long? APPROVER2 { get; set; }
        public string ORGLEVEL_1 { get; set; }
        public string ORGLEVEL_2 { get; set; }
        public string APP1_NAME { get; set; }
        public string APP2_NAME { get; set; }
        public string ORGLEVEL_3 { get; set; }
        public long? OPERID { get; set; }
        public long? DIVID { get; set; }
        public long? DEPTID { get; set; }
        public long? SECID { get; set; }
    }
}
